### ISSUE TITLE
Tapping the icon in Home App kicks in Auto Mode

### ISSUE THREAD

**Issue by CooperCGN** [lukasroegner/homebridge-dyson-pure-cool#1]
First thank you for this awesome plugin. Finally not a fan icon for a purifier!

Now my problem :) Whenever I turn one of my DP04s off and then on again by just tapping the icon in the home app it doesn't return to the previous fan speed but kicks in Auto mode. Is this the way it is meant to be?

Also I realized something weird about the controls in the details popup. They jump around, fan speed and mode switch even disappear. Maybe this is a HomeKit related bug, not sure about it. I have attached some screenshots.
![IMG_0052](https://user-images.githubusercontent.com/29116509/59993763-b5e96500-9651-11e9-8946-2a1a6573d632.png)
![IMG_0053](https://user-images.githubusercontent.com/29116509/59993764-b5e96500-9651-11e9-9f3f-8187eec2280e.png)
![IMG_0051](https://user-images.githubusercontent.com/29116509/59993765-b5e96500-9651-11e9-95d4-3bbddb7bb8e7.png)

**Comment by lukasroegner** [comment]
First issue: Auto-mode when enabling the purifier
I also noticed that and it seems that the Home app automatically switches to "Auto". I don't think that this is the expected behavior of the user, I'll try to prevent switching to "Auto" if the purifier has just been turned on.

Second issue: jumping control in the Home app
I've also noticed this behavior, however, this is a bug in the Home app. I think it is not that important as we'll get a new experience with iOS 13.

**Comment by CooperCGN** [comment]
I already thought so that it is a Home app bug. Although I must say that the new experience in iOS 13 at least until now is horrible with the buttons having no names. 

One question: have you ever experienced that your Dyson fails and displays an exclamation mark in the display in a triangle and becomes completely unresponsive? I then have to pull the power cord and restart it but also have to restart Homebridge. I still couldn’t figure out what exactly is the reason for this but it seems that a certain combination of commands or sending command a to fast is the reason.

**Comment by lukasroegner** [comment]
Ok, I didn't try the beta yet.

I've never experienced that in daily use, however, it occurred while I was resetting the devices (had some serious network issues) several times.

**Comment by CooperCGN** [comment]
I just installed the public beta on a “spare” iPad and this is what it looks like with only night mode exposed as a switch. Now imagine you have an accessory with several switches, or just add Auto mode. It becomes a kind of trial and error game as the switches have no names.

![1BF8FCFE-552F-4BAD-8E80-C87213EE9F0C](https://user-images.githubusercontent.com/29116509/60157085-3e9d0800-97ee-11e9-9f7b-28079e27d42a.jpeg)

Regarding my exclamation mark problem I think it’s the home app’s fault. I had the Dysons on the home screen and while updating the status I think it sends data back to the fan which might lead to contradicting statuses. Removed them from there for now but will keep an eye on it.

**Comment by CooperCGN** [comment]
> I've never experienced that in daily use, however, it occurred while I was resetting the devices (had some serious network issues) several times.

I am still troubleshooting. As you were saying you had network issues I wonder if that is the reason here too. I have hundreds of log entries as following. Homebridge does this sometimes for over 5 minutes for one or both of the two fans and suddenly the connection is established again. Now I wonder is that a Dyson problem (maybe dropping the wi-fi randomly) or should I start looking somewhere else. I mean I usually have no problems here with anything else; I just have no idea what is causing this.

```
[6/29/2019, 7:35:06 AM] [DysonPureCoolPlatform] VW2-EU-KDA0190A - MQTT disconnected.
[6/29/2019, 7:35:07 AM] [DysonPureCoolPlatform] VW2-EU-KDA0190A - MQTT reconnecting.
```

**Comment by lukasroegner** [comment]
I also have those connection drops from time to time. I assumed it is an issue with my wifi configuration (Amplifi Mesh network) where the devices occasionally change the access points. Didn't look into that as the devices have always responded to commands quickly.

Now, I also installed the iOS Beta 3 on my iPad, looks really weird how the air purifier and the two switches are merged into one device. I think I'm going to separate the air purifier accessory from the two switches (thus they'll be displayed as separate devices in the Home app).

**Comment by CooperCGN** [comment]
Maybe wait till the next beta comes out, it seems that they added back titles to accessories combined into one. By the way, I have two AmpliFi HD running here and was thinking the same that itbhas something to do with changing the access point.

**Comment by CooperCGN** [comment]
Last beta didn’t bring any improvement, I think it would be better to separate the accessories. Now if you want to change some settings of the Dyson it needs three to four steps till you’re there.

**Comment by lukasroegner** [comment]
Totally agree, it annoys me every time I want to enable/disable oscillation. I hope I find some time to work on it within the next weeks.

**Comment by lukasroegner** [comment]
Finally, labels are supported in the latest iOS beta. I'm gonna try to play around with the arrangement and see if it depends on the order in which services are added to an accessory. If that doesn't help and the UI still looks ugly, I'm considering to add the night mode and jet focus options as completely separate accessories.

**Comment by CooperCGN** [comment]
So “labels” is something new coming with iOS 13 to the HomeKit standard? Just asking as I have another plugin running that has the same problems and this might be a solution.

**Comment by lukasroegner** [comment]
Seems so, I didn't notice it at first, don't know when they added it.

![IMG_2442](https://user-images.githubusercontent.com/16758848/61941063-0593b700-af97-11e9-8168-838a2f578bae.jpeg)

**Comment by CooperCGN** [comment]
Weird, what beta are you running? I can’t see any of them. Or is it something that has to be added to the code?
![C3292120-C3EF-42B8-A936-30C8FB602277](https://user-images.githubusercontent.com/29116509/61941350-92d70b80-af97-11e9-9b53-1385fc6a0b10.jpeg)

**Comment by lukasroegner** [comment]
I'm on the latest Dev Beta, I think it's Beta 4.

**Comment by CooperCGN** [comment]
Hmm, seems then that dev beta and public are different. Mine is 13.0 (17A5534f) which was released mid last week.

**Comment by lukasroegner** [comment]
@CooperCGN currently working on the plugin. First step is to prevent switching to AUTO mode when changing the fan speed. Afterwards, I'll try to separate the air purifier accessory from the night mode/jet focus switches.

**Comment by CooperCGN** [comment]
Great to hear, as my experiments with iOS 13 once again seem to have corrupted my HomeKit installation (I really need to leave my hands from betas 😀) I will now wait till 13 gets released to make another setup from the ground. I have some pretty neat automations going with the Dysons like automatic night mode and stuff but don’t want to recreate that before the separations aren’t done.

**Comment by lukasroegner** [comment]
I know these kinds of situations. You get a beta, it doesn't work that well, finally there is the official major update and you swear to never download a beta again...six months later, you are so hyped that so download it anyway.

I hope to add separate controls within this week or the next week.

**Comment by lukasroegner** [comment]
@CooperCGN Issue with AUTO mode is fixed in latest version. I'll open a separate issue for iOS13 Home app layout.

**Comment by CooperCGN** [comment]
Sounds good, now I just need to get back internet, offline since two days and ISP hasn’t come up with a solution yet.

**Comment by CooperCGN** [comment]
One thing not working as expected: for example I turn mine on in the evening and then switch it to night mode when going to bed. When turning night mode off in the morning auto mode kicks in again.

**Comment by lukasroegner** [comment]
Can you provide the specific states of the device when you switch night mode, i.e. which mode (auto/manual), on/off?

**Comment by Krocko** [comment]
Hi @lukasroegner. 
Is there anything you can do about the missing labels?

**Comment by lukasroegner** [comment]
@Krocko please use #6 for this issue.

**Comment by CooperCGN** [comment]
@lukasroegner 
Dyson is turned on and switched to normal mode, I turn on night mode and turn it off again a bit later (in the morning). Auto mode kicks in.

Attached is the log of the simulated events
[log.txt](https://github.com/lukasroegner/homebridge-dyson-pure-cool/files/3512143/log.txt)

**Comment by CooperCGN** [comment]
Weird, it does that only on one of my Dysons, I start to wonder if it has something do to with my HK setup, which had some problems that seemed to be solved but I am not so sure about it anymore.

**Comment by lukasroegner** [comment]
I took a quick look at your log: from the log, it seems that the Home app automatically enabled AUTO mode when you switch off night mode...which would be really weird, as the night mode switch is not a default characteristic/service of an air purifier. I will try to simulate it with my devices (TP04 and DP04).

**Comment by CooperCGN** [comment]
If you can't reproduce it and everything works as intended with yours don't bother any further now. I will reset my HK config next week and start adding the things in question first to see if that solves some problems. I had the Arlo Cams and a PowerView hub added and they were behaving strange too. I can't get rid of the feeling that one of my iOS devices or hubs doesn't sync properly and produces weird things resulting in these problems.

**Comment by CooperCGN** [comment]
We can close this, I found the mistake in one of the automations. Apple Home App seems to have added the auto mode without me recognizing it.
