### ISSUE TITLE
MQTT Error - not authorized

### ISSUE THREAD

**Issue by CooperCGN** [lukasroegner/homebridge-dyson-pure-cool#10]
I suddenly get this, until this morning before installing the new version everything worked normal, any idea what this might be?

```
Sep 02 09:39:25 raspberrypi homebridge[9644]: [9/2/2019, 9:39:25 AM] Homebridge is running on port 51855.
Sep 02 09:39:26 raspberrypi homebridge[9644]: [9/2/2019, 9:39:26 AM] [DysonPureCoolPlatform] Signed in.
Sep 02 09:39:27 raspberrypi homebridge[9644]: [9/2/2019, 9:39:27 AM] [DysonPureCoolPlatform] VW2-EU-KDA0190A - MQTT connection requested for 10.0.1.211.
Sep 02 09:39:27 raspberrypi homebridge[9644]: [9/2/2019, 9:39:27 AM] [DysonPureCoolPlatform] VW2-EU-KDA1200A - MQTT connection requested for 10.0.1.78.
Sep 02 09:39:27 raspberrypi homebridge[9644]: [9/2/2019, 9:39:27 AM] [DysonPureCoolPlatform] Got devices from the Dyson API.
Sep 02 09:39:27 raspberrypi homebridge[9644]: [9/2/2019, 9:39:27 AM] [DysonPureCoolPlatform] VW2-EU-KDA1200A - MQTT error: Error: Connection refused: Not authorized
Sep 02 09:39:27 raspberrypi homebridge[9644]: [9/2/2019, 9:39:27 AM] [DysonPureCoolPlatform] VW2-EU-KDA0190A - MQTT error: Error: Connection refused: Not authorized
```

**Comment by CooperCGN** [comment]
Already restarted both Dysons by unplugging them, IPs are correct, I can reach them over the Dyson app.

**Comment by CooperCGN** [comment]
OK, now this is weird. When I add the bridge back to HomeKit (have the Dysons running on a seperate instance) I get this:
![IMG_0019](https://user-images.githubusercontent.com/29116509/64098289-c9f2c680-cd66-11e9-91fd-6b8877ef87da.png)

**Comment by lukasroegner** [comment]
Yes, expected. The accessories are cached per HomeBridge instance, that‘s why mapping the accessories to the devices does not work properly.

In order to remove all accessories, clear the devices array in the config.json file and restart homebridge. This will remove all accessories the plugin has created. Then, you can start again by adding them back into the devices array.

You could also revert to a previous version of the plugin after all accessories are removed to check if the authorization issue occurs in the latest version (I don't think so, as I didn’t change anything in the mechanism).

Did you update the firmware of your devices?

**Comment by CooperCGN** [comment]
this is what I did now.

1. stopped homebridge
2. removed array and persist and accessories folder
3. restarted
4. stopped
5. added array back in
6. restarted

At least the number of devices is now correct. :)

MQTT error persists, firmware according to Dyson app is ECG2P.02.06.002.0001

**Comment by CooperCGN** [comment]
That firmware update is weeks ago if I remember correctly, there have been several restarts of the pi inbetween

**Comment by lukasroegner** [comment]
Ok, so this is obviously not the issue. Have you tried an earlier version of the plugin?

Btw, thank you for your patience and help! This should be the last update with major changes.

**Comment by CooperCGN** [comment]
on version 0.3.0 without device array the plugin reports missing IP info for both devices:

```
Sep 02 10:17:34 raspberrypi homebridge[4907]: [9/2/2019, 10:17:34 AM] [DysonPureCoolPlatform] Adding new accessory with serial number VW2-EU-KDA0190A.
Sep 02 10:17:34 raspberrypi homebridge[4907]: [9/2/2019, 10:17:34 AM] [DysonPureCoolPlatform] No IP address provided for device with VW2-EU-KDA0190A.
Sep 02 10:17:34 raspberrypi homebridge[4907]: [9/2/2019, 10:17:34 AM] [DysonPureCoolPlatform] Adding new accessory with serial number VW2-EU-KDA1200A.
Sep 02 10:17:34 raspberrypi homebridge[4907]: [9/2/2019, 10:17:34 AM] [DysonPureCoolPlatform] No IP address provided for device with VW2-EU-KDA1200A.
```

on 1.0.1 I only get it for one and then logging stops, maybe it has something to do with me having two of them?:
`Sep 02 10:22:13 raspberrypi homebridge[8264]: [9/2/2019, 10:22:13 AM] [DysonPureCoolPlatform] No IP address provided for device with VW2-EU-KDA0190A.
`

after cleaning cache and everything reinstalled 0.3.0 and it works

**Comment by CooperCGN** [comment]
Is it maybe mixing up the authorizations?

**Comment by lukasroegner** [comment]
Yeah, this has been the issue (mixed up loop variables). In my case it did not happen as the order of devices in the config and the order of devices from the API were identical.

New version on NPM.

**Comment by CooperCGN** [comment]
Working now :) thank you very much

**Comment by marmitol** [comment]
Please i need Help.

I've installed and I can't see the devices in homebrige.
The following messages appear in the log

[2/17/2020, 4:40:20 PM] [DysonPureCoolPlatform] Signed in.
[2/17/2020, 4:40:23 PM] [DysonPureCoolPlatform] No IP address provided for device with serial number VS8-EU-KGA1234A.
[2/17/2020, 4:40:24 PM] [DysonPureCoolPlatform] Got devices from the Dyson API.

******************************************************************************************************
        {
            "platform": "DysonPureCoolPlatform",
            "username": "username",
            "password": "password@",
            "countryCode": "ES",
            "devices": [
                {
                    "ipAddress": "192.168.0.10",
                    "serialNumber": "V58-EU-KGA1234A",
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false
                },
***************************************************************************************************


Thank.

**Comment by dps098** [comment]
>         "countryCode": "ES",

>                 "serialNumber": "V58-EU-KGA1234A",

I'm not certain, but I think countryCode must match the two letter code in the serial number, so "EU".  For example mine is  -US- and I used countryCode "US".  If I used "EN" mine could not be found.  Good luck!

**Comment by lukasroegner** [comment]
@marmitol I'm really sorry, I haven't seen your post as the issue was already closed.

You have a typo in the serial number, it should be `VS8` instead of `V58`.

**Comment by marmitol** [comment]
>Tanks
