### ISSUE TITLE
PureCool TP02 - No Rotation (Oscillation) by turning switch in Home-App 

### ISSUE THREAD

**Issue by gintonic4all** [lukasroegner/homebridge-dyson-pure-cool#100]
Hi, 
I've just installed this Homebridge Plugin for my Dyson TP02. Everything seems to work - but the oscillation (rotation) around its vertical axis, when turning on the switch in the iOS Home-App.

The circular switch on the left-hand-side turns the fan on, the switch on the right, that I think is supposed to turn on the rotation, doesn't seem to work. In the homebridge journal no message occurs indicating the command has been sent - while the other commands (on/off, fan speed) do so.

Could you help me, please?

Thanks in advance,
gintonic4all

**Comment by lukasroegner** [comment]
Can you provide a screenshot of the app you are using? It doesn't seem to be the Apple Home app?

**Comment by gintonic4all** [comment]
Jupp, here you are:
![58282F65-61AC-4964-AF55-5E2DCD9A8E17](https://user-images.githubusercontent.com/59410845/85845318-5661f000-b7a4-11ea-90ff-c5e6e1dde3ee.png)
![B64AE037-3108-4DC5-A69E-C126797B92DD](https://user-images.githubusercontent.com/59410845/85845332-595ce080-b7a4-11ea-9db7-35c5f3dbde6d.png)

**Comment by gintonic4all** [comment]
Funny Fact, I just realized: in the eve app everything works fine... 

![image](https://user-images.githubusercontent.com/59410845/85849472-4dc0e800-b7ab-11ea-981b-154b93ac32cc.png)

**Comment by gintonic4all** [comment]
Besides this issue: why do there appear the sensors twice? There's always a slight difference between the correspoding sensor values....

**Comment by lukasroegner** [comment]
You've chosen to expose the device in "single accessory mode", which means, all services are exposed in a single accessory. Thus, the oscillation toggle is "hidden" in the home app. If you click on the "Devices" button in the details view and then open the details view for the actual air purifier, you can see the oscillation button in the lower section). As stated in the README, I wouldn't recommend the "single accessory mode" if you use the Apple Home app.

When you expose separate accessories, the oscillation toggle is directly presented in the lower section in the details view.

**Comment by gintonic4all** [comment]
Ah... that's nothing to do with the config.json, but with the option "show as single field" in the Home-App: Deactivating the option "show as single field" results in the view you mentioned. 

Thank you! :-)

**Comment by lukasroegner** [comment]
> Ah... that's nothing to do with the config.json

Actually, you can configure how the plugin should expose services to HomeKit:

> **isSingleAccessoryModeEnabled:** If set to true, all services are exposed to HomeKit in a single accessory instead of multiple accessories. If set to true, the single sensor accessory mode has no effect. Use this mode if you are using a third-party HomeKit app and want all services grouped into a single accessory. Defaults to false.
```

Based on your screenshot from the Apple Home app, I assume that you have this mode set to `true`.

**Comment by gintonic4all** [comment]
Nope. Here's the snapshot of my config.json. In the beginning when I've installed the plugin, I've set it to true. But then changed it to false. But in this meantime I also entered the credentials... 
Here's a snapshot of my config.json: 

{
            "username": "x@y.com",
            "password": "xypassword",
            "countryCode": "DE",
            "devices": [
                {
                    "ipAddress": "192.123.123.123",
                    "serialNumber": "MyDyson1",
                    "credentials": "DingDong42",
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false
                }
            ],
            "updateInterval": 10000,
            "platform": "DysonPureCoolPlatform"
        }

**Comment by lukasroegner** [comment]
>  In the beginning when I've installed the plugin, I've set it to true. But then changed it to false.

This is also the reason why sensors are shown multiple times: some services are not properly removed from HomeKit. To clean it all up, you can:
1. Stop homebridge
2. Set an empty array for the devices in your config (e.g. `devices: []`) and save
3. Restart homebridge
4. Stop homebridge
5. Add the removed devices to your config again and save
6. Start homebridge

Starting the plugin without devices in the array will remove all accessories exposed by the plugin.

**Comment by gintonic4all** [comment]
Excellent. That's the solution. First, with the upper config.json the sensors didn't appear - as configured. Afterwards, I've changed their SensorEnabled-flags to true. Now they appear separately from the control-field of the Dyson-fan, where all "steering-elements" - also the oscillation switch - are subsumed.   

Thank you, again!
