### ISSUE TITLE
[Feature request] Monitoring Switch

### ISSUE THREAD

**Issue by mczac** [lukasroegner/homebridge-dyson-pure-cool#101]
Could you please add optional monitoring switch.
This option is available in the mobile Dyson.app that allows fan to constantly monitor the air, however if there is a need to make the Dyson Pure Cool be completely silent at night, turning off monitoring mode would help.

key to use is rhtm
pay attention that to turn on monitoring you can send just rhtm: "ON"
but to turn off you need to send fmod:"OFF", rhtm: "OFF"

**Comment by lukasroegner** [comment]
New version 1.7.10 has the property `isContinuousMonitoringEnabled` in the configuration. If set to `true`, a switch is exposed to enable/disable monitoring.
