### ISSUE TITLE
Verzweigung mit anderen Geräten

### ISSUE THREAD

**Issue by ldiekmann** [lukasroegner/homebridge-dyson-pure-cool#103]
Hallo,

ich habe mittlerweile das Steuern des Dyson über das Homekit mit der Homebridge und dem Plugin hinbekommen.
Ich möchte eine Anbindung an meine Haussteuerung schaffen. Diese ist von Loxone. Dieses Plugin habe ich auch installiert und habe über einen Schalter das Ein- und Ausschalten durch Loxone hinbekommen. Weiß jemand, wie ich die Messwerte und Rückmeldung an meine Haussteuerung schicken kann? Der Loxone kann auch per http angesprochen werden.
Ich bin noch neu auf dem Gebiet Homebridge.

Vielen Dank im Voraus.
Lars

**Comment by lukasroegner** [comment]
Hi @ldiekmann,

GitHub is intended to be the place for devs to upload and manage their code, as well as issue tracking. Issues are not intended to be used to discuss general questions, they should be used to report bugs or request specific features.

I would highly recommend to post your question on reddit or use the largest HomeKit community in Germany: [smartapfel.de](https://forum.smartapfel.de/forum/). There you will find others which would love to discuss your question.
