### ISSUE TITLE
Rotate to angle

### ISSUE THREAD

**Issue by simonstuck** [lukasroegner/homebridge-dyson-pure-cool#104]
First of all: thanks for putting this together and for also continuously adding features! I've got it running with my DP04 and it works as advertised — good stuff! 

One thing the official Dyson app can do is to have the fan rotate to a particular angle. Neither this nor any other libraries I can find seem to be able to do this. Is this purely because none has needed it or because it's technically not supported (either by Homekit or the fan API itself)? 

Would love to be able to rotate the fan to a particular position via automation.

**Comment by simonstuck** [comment]
Well, I may be answering my own question here: https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/71 

Is this still an issue in iOS 14 if you've had the chance to take a look yet?

**Comment by lukasroegner** [comment]
@simonstuck I highly doubt that there is a new feature in the iOS 14 beta, as the [HAP-NODEJS](https://github.com/homebridge/HAP-NodeJS) project has already added the changes of the first beta.
