### ISSUE TITLE
[Feature Request] Timer Setting

### ISSUE THREAD

**Issue by Katalam** [lukasroegner/homebridge-dyson-pure-cool#105]
First of all, I really appreciate your work. I‘m really surprised how good the homebridge thing works. But I have one problem. I‘m using the timer function quiet often because I’m super forgetful to turn this off. I would be very happy if it’s possible to add the timer function to home, because I’m forced to use the original app atm.

**Comment by lukasroegner** [comment]
Can you come up with an idea on how to expose it to HomeKit? Which accessories/services to use for the timer?

**Comment by Katalam** [comment]
You could set the time by a slider and add an on/ off button for to enable it and slightly remove the values from the slider (if it based on 0 - 100) and turn the fan off if 0 is reached. But to be honest I have no clue about HomeKit services/ accessories.

**Comment by lukasroegner** [comment]
This is not how HomeKit works. You have to use accessories, services and characteristics, which are all predefined by Apple.
A "time" characteristic that is displayed as a slider or anything like that does not exist.

There is a concept of custom characteristics, however, this is only supported in third-party HomeKit apps. 
So, if you are planning to using the Apple Home app, this cannot be implement properly. If you are using the Eve app, there is a way to implement it via a custom characteristic.

**Comment by lukasroegner** [comment]
@Katalam Do you use the Apple Home app or a third-party app? It only really makes sense to implement it if you're not using the Apple Home app.

**Comment by Katalam** [comment]
@lukasroegner I'm using the Apple Home app. I thought there was an easy way to do it and I would like to stay at the original app.

**Comment by lukasroegner** [comment]
Currently, there isn't. Maybe Apple adds a new characteristic/service that can be used for general-purpose timers in the future. I'm closing this for now.

As I also want to have this feature (but also want to use the Apple Home app), it will be implemented as soon as there is a way to do so.
