### ISSUE TITLE
Oscillation on/off

### ISSUE THREAD

**Issue by kalunde78** [lukasroegner/homebridge-dyson-pure-cool#106]
Is there something to configure to get the Oscillation on/off button? I don't have it in Homebridge nor Homekit.

**Comment by lukasroegner** [comment]
It is there. I assume you have the single accessory mode or any other configuration option enabled that merges multiple services into a single accessory (see #79 and #100). As soon as the default configuration (AirPurifier as separate accessory) is enabled, you'll find the oscillation setting in the lower section of the accessory details.

**Comment by kalunde78** [comment]
Thx Lukas. Any plan to create a dedicated switch for this function, which can be understood by Siri? If you start the fan with siri, you can't activate oscillation - as far as I figured out.

**Comment by lukasroegner** [comment]
In #72, a user found I nice workaround for the issue: https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/72#issuecomment-623168358

**Comment by kalunde78** [comment]
great, thx a lot!
