### ISSUE TITLE
[Feature Request] Reverse Airflow

### ISSUE THREAD

**Issue by Rigoninho** [lukasroegner/homebridge-dyson-pure-cool#107]
Is ist possible to integrate a switch for the changing of airflow direction? I usually do that before I go to bed, and I would love to integrate it in my HomeKit routine (so I don’t have to use the Dyson App anymore).
Thank you for your awesome work, I really appreciate your project.

**Comment by lukasroegner** [comment]
Already integrated, it's the switch called "Jet Focus".

**Comment by Rigoninho** [comment]
I’m sorry I forgot to activate it.
