### ISSUE TITLE
Device name in Jet Focus and Night Mode

### ISSUE THREAD

**Issue by joppuyo** [lukasroegner/homebridge-dyson-pure-cool#108]
![image](https://user-images.githubusercontent.com/1595438/87338191-6cfe9a00-c54d-11ea-9646-be5ddd6d6c5a.png)

When you have multiple devices would it be possible to add the device name to night mode and jet focus switches? Right now they are *all* named "Jet Focus" and "Night Mode" which makes it difficult to assign them to rooms in the Home app because you don't know what device they correspond to.

Best would be if they would be named "Bedroom Night Mode" and "Living Room Night Mode" and so on.

Thanks!

**Comment by joppuyo** [comment]
As it turns out, you can actually rename the devices the Homebridge UI. But it seems like the name is not carried out to the Home app so this doesn't really help much in this situation.

**Comment by lukasroegner** [comment]
Why don‘t you rename them in the Home app?

**Comment by joppuyo** [comment]
Well, when you first set up the Homebridge it will ask you to assign the devices to rooms. It's easy for the air purifier and humidifier devices because they have the room name as the device name, for example, "Bedroom" is the bedroom humidifier device.

All my 3 night mode switches are called just "Night Mode" instead of something like "Bedroom Night Mode" or "Living Room Night Mode" so I can't tell which room to assign them. Same with the Jet Focus.

The only thing the Home app gives you is the serial number if you dig into the settings which I have to cross-reference with the Dyson app to get the device names.

Of course, I can do that but it would be nice if the devices had more descriptive names from the start.

If you want I could try to put together a PR to do that.

**Comment by lukasroegner** [comment]
New version 1.7.11 adds the actual device name to the switch names.

**Comment by joppuyo** [comment]
Thank you for the quick release, I just updated to the latest version and it works just the way I wanted 👍
