### ISSUE TITLE
400 and 429 login error

### ISSUE THREAD

**Issue by rubyonone** [lukasroegner/homebridge-dyson-pure-cool#110]
Hi, I'm getting 400 and 429 login errors at startup and retry. 

I'm in the UK using a PH01 

Anything I can do?

Can I get my credentials for a local connection to the machine?

Thanks

Chris

**Comment by lukasroegner** [comment]
Hi @rubyonone,

Please check for existing issues before opening a new one to a topic that has already been discussed:
#102, #96, #57 

TL;DR:
- Use GB as country code
- Wait some hours before retrying with the correct country code, 429 means too many requests to the Dyson API

**Comment by rubyonone** [comment]
Many thanks

that has worked and the fan is now connected 👍

**Comment by lukasroegner** [comment]
If you use the feature to store the credentials, the plugin no longer needs to communicate with the Dyson API when Homebridge is restarted, which prevents 429 errors.
