### ISSUE TITLE
Oscillation

### ISSUE THREAD

**Issue by bunique2k** [lukasroegner/homebridge-dyson-pure-cool#112]
I had the option to switch on and off oscillation within the home sol but after changing settings in homebridge to expose as one switch the option has disappeared from my setup. Want to avoid deleting it.

**Comment by lukasroegner** [comment]
If you merge the accessories via the single accessory mode, the oscillation switch is hidden in the actual air purifier device. You can access it if you open the details tab of the single accessory in the Home app, then scroll down and open the "devices" menu item. Choose the air purifier, now you can see the oscillation button in the details.

The single accessory mode is not recommended when using the Apple Home app, as it hides settings in menus.
