### ISSUE TITLE
Device list empty

### ISSUE THREAD

**Issue by mbuskirk5** [lukasroegner/homebridge-dyson-pure-cool#114]
I am having an issue with the plugin not discovering my device. I only have one device on my Dyson Link account. Should it find them on it's own or do I need to add them manually? Thanks.

**Comment by lukasroegner** [comment]
@mbuskirk5 All devices that you want to use have to be added to the config of the plugin.

**Comment by mbuskirk5** [comment]
Got it working. Thanks.
