### ISSUE TITLE
Clarifaction on country code

### ISSUE THREAD

**Issue by rediphone** [lukasroegner/homebridge-dyson-pure-cool#116]
Hi there, thanks for this plug in - its working great for me. I had some problems getting setup however due to the country code, i dont think its an issue with your code but I wanted to point it out and wasnt sure where... sorry if this is the wrong place

I am from the UK and the serial number for the device i have has UK in the middle of it so I assumed that the code for the country code would match that, however i was getting 400s. looking at the documentation EN was suggested so i tried that. When that didnt work i eventually tried GB and that worked! 

not sure if EN was supposed to represent ENGLAND but i wanted to point out if anyone else from the UK has the same issue. 

thanks agaain for maaking this plugin

**Comment by lukasroegner** [comment]
Thanks for reporting, I fixed the sample for the country code in the README!
