### ISSUE TITLE
Status code:429

### ISSUE THREAD

**Issue by toinou37130** [lukasroegner/homebridge-dyson-pure-cool#117]
Hi,
I have the error with signing in. 
Here are the homebridge logs for the Dyson plugin:
`[8/18/2020, 11:55:47] [DysonPureCoolPlatform] Error while signing in. Status Code: 429
[8/18/2020, 11:55:47] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.`

How to solve the problem ? I have checked the information several times and everything is ok.

**Comment by rediphone** [comment]
first you willneed to drop the retry requests, I thinkthe api is ignoring your attempts now that its spammed the connection. 

once you get a 400 response you can try troubleshooiting again -im not sure how long that takes but it took sometime for me. I think the timer starts again if you try and its not stopped ignoring you yet

**Comment by lukasroegner** [comment]
This has been discussed several times in the issues: #110, #102, #57, #33, #94 

- Make sure the country code is correct
- Make sure your credentials are correct
- Check whether the name of the device in the Dyson app contains any special characters

If you provide more information (sanitized config), I can take a deeper look.

**Comment by toinou37130** [comment]
Danke, es klappt !
