### ISSUE TITLE
Error code 401 + API could not be reached

### ISSUE THREAD

**Issue by newuser12341** [lukasroegner/homebridge-dyson-pure-cool#118]
Hi - not sure if there is an easy solution to this (probably the case) but I'm getting

[DysonPureCoolPlatform] Error while signing in. Status Code: 401
[DysonPureCoolPlatform] API could not be reached. Retry is disabled.

The country code is set to HK, but I have two devices and only one of them has a 'HK' in the serial number (neither one shows up in the HOOBS interface).

Any ideas?

**Comment by lukasroegner** [comment]
Please check your credentials for mistakes, see #26.

**Comment by newuser12341** [comment]
Did - they are correct (I've even reset the password)

**Comment by lukasroegner** [comment]
And those credentials work correctly in the Dyson app?

**Comment by newuser12341** [comment]
Yep. I am using a complex password though if that's a problem?

**Comment by lukasroegner** [comment]
I dont't think so, I also use a generated password from a password manager, and it works for me.
Maybe there is an issue with the country code. This is the country code of the country that you selected when creating the Dyson account in the Dyson app.

**Comment by newuser12341** [comment]
Oh dear lord... I have no idea what I selected at the time... I live in Hong Kong, but generally I choose UK (language issues). Do you know how I can find out what I picked?

**Comment by lukasroegner** [comment]
I don't think that there is a way to look it up in the Dyson app (didn't find any information on that). If you want to try, the country code for the UK is "GB".

**Comment by newuser12341** [comment]
Tried that. Also tried HKG (three letters instead of two).

Tried to log out of the app and log back in again. Now it says my account is locked.... and the Dyson support team sent me a password reset link that doesn't work.... *sigh* Will try again in a couple of days when the idiots have fixed that particular issue as it seems the website username/password is completely different to the app...

**Comment by lukasroegner** [comment]
Yes, the credentials for the shop are not the same as those for the Dyson app. I also don't think that there is any kind of account management for the Dyson app account.

**Comment by newuser12341** [comment]
Got it working. Basically had to create a new account and re-map the devices to it. All good!
