### ISSUE TITLE
[Feature Request] PH01/PH02 - Please expose humidity sensor to Climate screen in iOS 15.x

### ISSUE THREAD

**Issue by sweetw0r** [lukasroegner/homebridge-dyson-pure-cool#119]
Hi,

Can humidity sensor be exposed for devices w/ humidifier? It would make it consistent in a new iOS 14 climate feature. Attaching a screenshot

![44E0EC1E-5694-428E-BF3A-65E43563CBDB](https://user-images.githubusercontent.com/12688470/91958026-a769f500-ecbb-11ea-98fc-745c79fc4dc1.jpeg)

**Comment by lukasroegner** [comment]
The humidifier service already has a built-in "sensor" as it shows the current humidity in the accessory details (and, also shows the value in the room status as I can see on your screenshot). Can you further explain what you want me to implement?

**Comment by sweetw0r** [comment]
Hi @lukasroegner I agree that Home page widget looks perfect and there is nothing to fix. But when user taps it, it feels like on that new "Climate" screen (under Bedroom section) there should be sensor information. So Humidity rather than Humidifier. Living room section depicts exactly what would be expected here.

**Comment by thumax** [comment]
@sweetw0r Have you tried setting isHumiditySensorEnabled to true?

**Comment by sweetw0r** [comment]
@thumax I have it on. But the feature request stands as description says the config applies only for non humidifier devices. PH01 is a humidifier device.

**Comment by gabemunro** [comment]
Swinging by to second this. It would be great. Currently just seeing what my PH02 is set to, but would be great to have a separate sensor exposed showing current relative humidity.

Also, thank you for building this. You're truly a rockstar for sharing this with us.

**Comment by Ioan-Popovici** [comment]
Yes there are indeed some problems with PH1:
* Humidity is not displayed
* Oscillation does not work
* It would be nice if air flow direction switch (forward/backward) could be exposed.
Everything else works flawless for me.

Thanks for all your hard work and for making this possible!

**Comment by gabemunro** [comment]
Both oscillation and focus work fine for me. Make sure you have your settings right in config.json

**Comment by Ioan-Popovici** [comment]
@gabemunro thanks for the tip for focus mode, I didn't know that Airflow direction is called focus mode.
The oscillation option for PH1 is different than the one for PH2. It does not have 360 degrees. Maybe that's the problem.

This is my config:
```
"enableAutoModeWhenActivating": true,
"enableOscillationWhenActivating": true,
"isNightModeEnabled": true,
"isJetFocusEnabled": true,
"isContinuousMonitoringEnabled": false,
"isTemperatureSensorEnabled": true,
"isHumiditySensorEnabled": true,
"isAirQualitySensorEnabled": true,
"isSingleSensorAccessoryModeEnabled": true,
"isSingleAccessoryModeEnabled": true,
"isFullRangeHumidity": true,
"isHeatingDisabled": true
```

![IMG_310C068ABD14-1](https://user-images.githubusercontent.com/17069425/108513372-30590500-72cb-11eb-82f7-234c2023a873.jpeg)

The oscillation stays off in the dyson link app and device if I toggle the oscillate button.

Thanks for the focus mode tip :)

**Comment by sweetw0r** [comment]
@lukasroegner this is a friendly follow up. 

Expected:
Humidifier switch should be replaced by Humidifier sensor in the Climate sensor screen.

![IMG_0310](https://user-images.githubusercontent.com/12688470/118391102-792d0b00-b5e7-11eb-8257-1f5434ea156f.PNG)

**Comment by sweetw0r** [comment]
Follow up on this. It's been a year

**Comment by lukasroegner** [comment]
Added in version 2.7.0. Set the property `isHumiditySensorEnabled` to `true` so that an additional humidity sensor is exposed for humidifiers.
