### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by D-a-n-e** [lukasroegner/homebridge-dyson-pure-cool#12]
Hi,
thanks for this great plugin! 🥇 
I've been using it for a few days with a Dyson Pure Cool Link Tower (TP02) 🙂

I'm a bit confused about a button label.
The button "Stärke" brings you to the selection of the operating mode (on or off).

I think it should be called "Mode", like tado thermostats. See the screenshots below.

![HomeKit-Bedroom](https://user-images.githubusercontent.com/55045838/64485432-2fd8c580-d221-11e9-97bd-86ccb4846d11.jpg)

![HomeKit-DysonSettings-1](https://user-images.githubusercontent.com/55045838/64485442-42eb9580-d221-11e9-9328-643c11f7c306.jpg)

![HomeKit-DysonSettings-2](https://user-images.githubusercontent.com/55045838/64485444-4d0d9400-d221-11e9-92b1-34453a24eae9.jpg)

![HomeKit-TadoSettings-1](https://user-images.githubusercontent.com/55045838/64485446-5860bf80-d221-11e9-9cce-0cebf4b9df5f.jpg)

![HomeKit-TadoSettings-2](https://user-images.githubusercontent.com/55045838/64485450-61519100-d221-11e9-9913-c2c69eb220c7.jpg)

**Comment by lukasroegner** [comment]
You have to submit this issue to Apple, this is built in and can‘t be changed 😉

**Comment by D-a-n-e** [comment]
Okay, I'll wait for iOS 13. 😜
