### ISSUE TITLE
[Feature Request] Rearrange Accessory tile switches so fan speed shows as primary status

### ISSUE THREAD

**Issue by blantrOn** [lukasroegner/homebridge-dyson-pure-cool#122]
Would it be possible to make an adjustment to how the accessory tile is configured, such that the fan speed is the first option? What I'm hoping for is that, when I look at the tile on the Room screen or in the control panel that it shows the fan speed % right there. I've seen this on a different Dyson homebridge plugin, but your plugin is much better overall so i prefer it but would love to see this if possible!

**Comment by lukasroegner** [comment]
I'm sorry, developers cannot change the UI in the details view of accessories in the Home app, this is all done by the Home app.

I also don't like the large on/off switch and it really seems like a bug in the Home app, let's see if they fix it in the next updates (should be a small rounded on/off button).
