### ISSUE TITLE
"Invalid device credentials for device" for devices with UTF-8 name

### ISSUE THREAD

**Issue by timdream** [lukasroegner/homebridge-dyson-pure-cool#126]
Hi,

Great plug-in! My Dyson fan is named with a non-ASCII name and the `toString('ascii')` call will throw because of that.

https://github.com/lukasroegner/homebridge-dyson-pure-cool/blob/36fd365bc87cf9cea63540b6fec66a6919501685/src/dyson-pure-cool-platform.js#L263

I changed this call to `toString('utf8')` (and the one on line 275) locally and it fixes my problem. I figured you would want to fix it here.

Thanks!

**Comment by lukasroegner** [comment]
Thanks for reporting! I fixed it in the latest version.
