### ISSUE TITLE
Adding support for PH02

### ISSUE THREAD

**Issue by vall002** [lukasroegner/homebridge-dyson-pure-cool#128]
Hi, 
   I appreciate all the effort you put into creating and maintaining this plugin. I am new to homebridge and am planning to come up with my own plugins.

I got a Dyson pure cool with Cryptomatic (PH02) but it should be very close or exactly the same as PH01. 
When I do a provisioning service get API, they see the "ProductType": "358" which is same as PH02. With this in mind, I started to set the env and started using them.  
Below are the issues I see:

1.  Air Quality sensor information says Unknown

![IMG_08120B440AE2-1](https://user-images.githubusercontent.com/60719516/97087022-f154c480-15f4-11eb-9201-0ec5bce6db73.jpeg)

2. setting a mode to "auto", humidity or off shows "set to" on the tile but that doesn't say "set to Auto" or something.
![IMG_0022](https://user-images.githubusercontent.com/60719516/97087015-e6019900-15f4-11eb-8796-d578b4f8b953.jpg)

3. The option to set temperature in Fahrenheit. If you see in the screenshot, my other sensor is forcing F on me, and this plugin forces C, this will show my final room temperature as 32-74, which is not useful.

![IMG_0021](https://user-images.githubusercontent.com/60719516/97087010-dc783100-15f4-11eb-9fe8-f1607c912157.jpg)

4. I would like if individual statuses like, Humidifier, purifier, is shown in the top status rather than a button that says multiple is [on.](url)

Thanks
Uday

**Comment by lukasroegner** [comment]
Please check the logs (start Homebridge with parameter `-D` for error messages with the MQTT communication. If you don't find the cause of your problem, please post the log messages here.
