### ISSUE TITLE
Air Quality problem

### ISSUE THREAD

**Issue by patrickda** [lukasroegner/homebridge-dyson-pure-cool#129]
Hi 
my Dyson app shows me the Air quality as "good" while Homebridge shows me "Poor" (=5 in the details). Any idea what I have to change so that the readings fit (I got a Dyson Pure Cool Link) ?
And help would be appreciated.

**Comment by lukasroegner** [comment]
The air quality is not exposed by the Dyson devices in a human-readable way (the devices only provide you with the actual readings). I've come up with my own "algorithm" to translate the readings to the states that HomeKit offers for air quality.
You can check the translating code in [dyson-pure-cool-platform.js](https://github.com/lukasroegner/homebridge-dyson-pure-cool/blob/master/src/dyson-pure-cool-platform.js) starting at line 449.

If you have suggestions for enhancing the code, feel free to post it here.

**Comment by codyc1515** [comment]
I’m not seeing any of the metrics coming through, like VOC or PM2.5. The rest of the accessory works as intended.

**Comment by codyc1515** [comment]
Working again now. Not sure what changed. Seemed to be affected by a restart of Homebridge.
