### ISSUE TITLE
Night Mode activates manual mode

### ISSUE THREAD

**Issue by D-a-n-e** [lukasroegner/homebridge-dyson-pure-cool#13]
Hi,

I noticed the following.
The starting point is a TP02 which is in automatic mode.
If I now activate the night mode via the HomeKit switch ("isNightModeEnabled": true), the TP02 will switch to manual mode.
But if I activate the night mode via the Dyson app, the TP02 stays in automatic mode.
Is this behavior also possible via HomeKit? That would be awesome!

![DysonApp-AutomaticMode+NightMode](https://user-images.githubusercontent.com/55045838/64490861-c2995480-d261-11e9-93d9-da2c85023117.jpg)

**Comment by lukasroegner** [comment]
@D-a-n-e Please check out the `development` branch and test if your requested behavior is working.

**Comment by D-a-n-e** [comment]
@lukasroegner Perfect, it works! Thank you!

**Comment by lukasroegner** [comment]
Merged into master in #15, new version 1.0.5 on NPM.
