### ISSUE TITLE
Disable Night Mode and Jet Focus Switch.

### ISSUE THREAD

**Issue by BioExorzist** [lukasroegner/homebridge-dyson-pure-cool#130]
No matter if you set "isNightModeEnabled" and "isJetFocusEnabled" to "true" or "false", the switches stay in.

Version 1.8.1

**Comment by lukasroegner** [comment]
Can you please provide your config?

**Comment by BioExorzist** [comment]
Sure:

{
    "bridge": {
        "name": "Homebridge",
        "username": "USERNAME"
        "port“: PORT,
        "pin“: "PIN"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port“: PORT,
            "platform": "config"
        },
        {
            "username": "USERNAME",
            "password": "PASSWORD",
            "devices": [
                {
                    "ipAddress": "IP",
                    "serialNumber": "SERIAL",
                    "credentials": null,
                    "enableAutoModeWhenActivating": true,
                    "enableOscillationWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false
                }
            ],
            "platform": "DysonPureCoolPlatform"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "hosts": [
                „IP"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": false,
            "users": {
                "CODE": "CODE"
            },
            "platform": "Hue"
        }
    ]
}

**Comment by lukasroegner** [comment]
Config looks fine. Please start Homebridge in debug mode (parameter `-D`). If the switch accessory (for Night Mode and Jet Focus) is enabled, you should see the following log entry:
```
Adding new accessory with serial number XXX and kind SwitchAccessory.
```

If the switch accessory is disabled (as with your config), you should see this:
```
Removing unused accessory with serial number XXX and kind SwitchAccessory
```

**Comment by BioExorzist** [comment]
Have both entries:
[37m[10/31/2020, 7:07:19 PM] [39m[36m[DysonPureCoolPlatform] [39mAdding new accessory with serial number SERIAL and kind SwitchAccessory.
[37m[10/31/2020, 7:13:53 PM] [39m[36m[DysonPureCoolPlatform] [39mRemoving unused accessory with serial number SERIAL and kind SwitchAccessory.

**Comment by lukasroegner** [comment]
The entries were from two different runs?

When you take a look at
https://github.com/lukasroegner/homebridge-dyson-pure-cool/blob/47d9ca02d3fad7fb0ec94e1a22d01cb6542db3cc/src/dyson-pure-cool-device.js#L162
you can see that the switch accessory is only added if either `isNightModeEnabled`, `isContinuousMonitoringEnabled` or `isJetFocusEnabled` is enabled. As all of the three settings are disabled according to your config, you should not see the log entry
```
Adding new accessory with serial number SERIAL and kind SwitchAccessory
```

I cannot think of the cause why it is added in your setting. Are you sure that you have installed the latest version of the plugin, and that the config file is the one that is actually used?

**Comment by BioExorzist** [comment]
This is the current configuration which I can view in the "Homebridge Configuration Editor". The two entries from the log file I just selected after restarting the whole Docker container. But right, now I also notice that these two entries are the only ones that were created in the last 9 days. Though I restarted several times, even in debug mode. So there were no new entries about the switch.

Homebridge 1.2.3. is installed and homebridge-dyson-pure-cool v1.8.1

**Comment by lukasroegner** [comment]
If you restarted several times, you should see way more logs from the plugin. Maybe an issue with your Docker environment?

**Comment by BioExorzist** [comment]
Now I solved it like this: Delete the complete Docker Container, empty the directory of the container and reinstall everything. Then I loaded the old Config and now it works.
But I had to downgrade to version 1.1.6. Otherwise my HomeKit would not work with Homebridge anymore, for whatever reason. Before it worked with 1.2.3...

**Comment by lukasroegner** [comment]
It really sounds like your old container did not restart Homebridge properly. Glad that you could solve the issue.
