### ISSUE TITLE
No Accessory Loaded in Homekit App

### ISSUE THREAD

**Issue by ReggiePhilippe** [lukasroegner/homebridge-dyson-pure-cool#131]
The homebridge log returns the following message, but when I go to add an accessory to HomeKit, nothing shows up.

**[DysonPureCoolPlatform] Signed in.
[DysonPureCoolPlatform] Got devices from the Dyson API.**

Configuration settings for my HP04 (Dyson Pure Hot+Cool).
For the product type, I've tried '455' and '527' and got the same result.

{
    "bridge": {
        "name": "HomeBridge",
        "username": "XXX",
        "port": 51980,
        "pin": "XXX-XX-XXX",
        "restart": "sudo -n systemctl restart homebridge",
        "sudo": true
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "sudo": true,
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
{
            "platform": "DysonPureCoolPlatform",
            "username": "email@icloud.com",
            "password": "account password",
            "countryCode": "US",
            "devices": [
                {
                    "ipAddress": "192.XXX.XX.XX",
                    "serialNumber": "ZZ4-US-XXXXXXXX",
                    "ProductType": "358",
                    "enableAutoModeWhenActivating": true,
                    "enableOscillationWhenActivating": true,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": true,
                    "isContinuousMonitoringEnabled": true,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false
                }
            ],
            "updateInterval": 60000,
            "retrySignInInterval": 0

**Comment by a211212abc** [comment]
Same here. It works several weeks ago, but stopped working somehow recently.

**Comment by lukasroegner** [comment]
There is no property `ProductType` for this plugin. Start homebridge in debug mode (parameter `-D`)  to get all logs of the plugin.
