### ISSUE TITLE
No Action

### ISSUE THREAD

**Issue by Benardos** [lukasroegner/homebridge-dyson-pure-cool#135]
I Have successfully added both Dyson Pure Cool units, I get no log issues and see the controls in Homekit.  I can prompt Siri and get a successful response, but neither of the devices activate.

I can control the devices with the Dyson app and can see them in my Lan Scan.  

No sure where I went wrong.

**Comment by lukasroegner** [comment]
Stat homebridge in debug mode (parameter `-D`) and check the logs for MQTT connection entries. Those will tell you whether the plugin can establish a connection to your device.
