### ISSUE TITLE
Automation Auto Mode

### ISSUE THREAD

**Issue by KibosJ** [lukasroegner/homebridge-dyson-pure-cool#136]
Love this plugin! Everything is working great apart from one small issue that is bugging me.

If I tap the icon to turn the fan on, it turns on auto mode as set in the configuration.

I have an automation set to turn the fan on at a certain time, but it always triggers manual mode, no matter what I set in the automation ☹️ It does the same for the second automation too, when turning on the fan and setting night mode, it puts the fan on manual rather than auto

```"enableAutoModeWhenActivating": true,
"enableOscillationWhenActivating": true,
"isNightModeEnabled": true,
"isJetFocusEnabled": false,
"isContinuousMonitoringEnabled": true,
"isTemperatureSensorEnabled": true,
"isHumiditySensorEnabled": true,
"isAirQualitySensorEnabled": true,
"isSingleSensorAccessoryModeEnabled": true,
"isSingleAccessoryModeEnabled": false,
"isFullRangeHumidity": false
```
<img width="516" alt="CleanShot 2020-12-04 at 5 42 55@2x" src="https://user-images.githubusercontent.com/29429479/101196071-2f172500-3658-11eb-832d-9febb3058302.png">

<img width="514" alt="CleanShot 2020-12-04 at 5 45 12@2x" src="https://user-images.githubusercontent.com/29429479/101196323-7ef5ec00-3658-11eb-9516-1e410c32e61b.png">

**Comment by gabemunro** [comment]
Just came for the same issue. This behavior varies from device to device. I tried adjusting the automation a few times for my DP04 and it randomly started enabling auto mode when I test the automation. It seems to work fine on my TP02. I can't for the life of me get it to work on my PH01 though.

**Comment by lukasroegner** [comment]
There is a simple fix: don't use the Apple Home app to create automations. The Apple Home app adds actions so the automation that are not clearly visible to the user. I recommend opening our automation with a third-party HomeKit app (e.g. Controller for HomeKit or Home+ 4). You will see that the Apple Home app added more actions than you wanted to set in your automation.

**Comment by KibosJ** [comment]
I didn't really want to pay for an app, but I've got it sorted now with Eve Home, which is free 🙂 Thanks for your help
