### ISSUE TITLE
API error with TP02

### ISSUE THREAD

**Issue by ndwong** [lukasroegner/homebridge-dyson-pure-cool#139]
Getting these error messages: 
[12/12/2020, 13:25:56] [DysonPureCoolPlatform] Error while signing in. Status Code: 429
[12/12/2020, 13:25:56] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.

I've triple-checked the email/username/countrycode/serial.
Any response on what 429 represents?

**Comment by jfrobs** [comment]
Same problem....TP02 not work with the plugin...but my DP04 work fine

**Comment by lukasroegner** [comment]
As stated several times in the issues:
- Make sure you have installed the latest version of the plugin
- Make sure the country code is correct
- Make sure your credentials are correct
- Check whether the name of the device in the Dyson app contains any special characters

If you provide more information (sanitized config), I can take a deeper look.

**Comment by jfrobs** [comment]
Its ok now, the name of the device work fine with other home bridge plugin but with this I must delete the DYSON- before and the -475 after the serial.

**Comment by no-Legend** [comment]
> Its ok now, the name of the device work fine with other home bridge plugin but with this I must delete the DYSON- before and the -475 after the serial.

Can you please show me a screenshot how you setted everything up.
I'm not able to get my TP02 working.

**Comment by no-Legend** [comment]
Looks like the plugin is not supporting an special characters in the password.
I now use a password without any special characters, only letters and numbers.
now the login is possible.
