### ISSUE TITLE
Disable Heat

### ISSUE THREAD

**Issue by Rajan-matsec** [lukasroegner/homebridge-dyson-pure-cool#140]
Hi - thank you for building this plugin, it's really high quality work.
Is there anyway to disable the heat functionality on devices that support heat. My use case is:
I only want to turn on my radiant heat in each room.
I use Siri with the command "Set living room to xx" where xx is the temperature I'd like
The Dyson supports heat so it also turns on with a target temperature of xx

I'd like to disable the heat function on the Dyson so it does not turn on. Something like:
`isHeatEnabled:` 
with a value of `true` or `false`

`true` will expose the heat controls to homekit
`false` will hide the heat controls from homekit

Thanks very much!

**Comment by lukasroegner** [comment]
Implemented in 1.8.4
