### ISSUE TITLE
[Request] Switch to use Airflow direction

### ISSUE THREAD

**Issue by DJay-X** [lukasroegner/homebridge-dyson-pure-cool#143]
I just installed the plugin and as always from the work of @lukasroegner it worked instantly with my Dyson Pure Humidify+Cool (PH01). Thanks for this.

However, I miss a Switch to control Airflow direction.
![Bildschirmfoto 2020-12-30 um 10 56 36](https://user-images.githubusercontent.com/3874239/103344783-e5233280-4a8f-11eb-9582-253041ffd7cc.png)

Use case is, that I want to switch the airflow to the back of the device when sitting on the sofa in winter time. During the day it can blow to the front. At the moment this is only possible via the physical remote. 

Any chance to have this in a next plugin update?

Thanks again.

**Comment by lukasroegner** [comment]
Hi @DJay-X, this is the "Jet Focus" switch.

**Comment by DJay-X** [comment]
😅 Oh.. yap. That did work. Sorry and thanks. 😬
