### ISSUE TITLE
Misleading error message: No IP address provided for device with serial number

### ISSUE THREAD

**Issue by jasongerbes** [lukasroegner/homebridge-dyson-pure-cool#145]
When a device hasn't been configured (or in my case the serial number has been incorrectly entered), the plugin is logging a `"No IP address provided for device with serial number..."` warning message.

This is due to following code, from lines 203 - 208 of `dyson-pure-cool-platform.js`:

```js
// Gets the corresponding device configuration
let config = platform.config.devices.find(function(d) { return d.serialNumber === apiConfig.Serial; });
if (!config) {
    platform.log.warn('No IP address provided for device with serial number ' + apiConfig.Serial + '.');
    continue;
}
```

This warning should be updated to read more like:

```js
platform.log.warn('No configuration provided for device with serial number ' + apiConfig.Serial + '.');
```

**Comment by lukasroegner** [comment]
Thanks for reporting, will be fixed in the next version.
