### ISSUE TITLE
Error 403 when attempting to sign in

### ISSUE THREAD

**Issue by petercockroach** [lukasroegner/homebridge-dyson-pure-cool#146]
Nothing has changed on the Dyson side of things but my fans are no longer responding. Checking the logs, I'm getting a 403 error when attempting to sign in. I've tried changing my password (and changing it in the config to match) and I'm still getting the same error.

[1/13/2021, 1:26:13 PM] [DysonPureCoolPlatform] Signing in.
[1/13/2021, 1:26:13 PM] [DysonPureCoolPlatform] Error while signing in. Status Code: 403
[1/13/2021, 1:26:13 PM] [DysonPureCoolPlatform] API could not be reached. Trying again soon...

**Comment by s1rc** [comment]
Having the same issue as well now. I used HomeKit with my fans earlier this morning, seems to have changed at some point today for me.

**Comment by brian-su** [comment]
Having the same issue as of 2 hours ago. 

I've tried testing the API calls to the two login URLS below with my credentials via postman on my laptop and CURL from my Pi that runs my homebridge server; both work fine. But for some reason the call that the plugin makes gets blocked. 

- https://appapi.cp.dyson.com/v1/userregistration/authenticate?country=XX
- https://appapi.cp.dyson.com/v2/provisioningservice/manifest

**Comment by iadamrodriguez** [comment]
Brand new to Homebridge as of yesterday.  Had This plug in up and working great last night.  Today having the same issues as everyone else.

**Comment by ryanngo0911** [comment]
Any fix to the 403 error? Read about headers issue but have no clue how to include it to config settings. Thanks.

**Comment by awfy** [comment]
@ryanngo0911 once it’s merged and published you’ll be able to update the plugin from Homebridge. Not sure how long it’ll be before it’s available though.

**Comment by brian-su** [comment]
There is a way around the API calls that are made to login. If you can go back far enough in your homebridge logs to where it last worked then you should see a token like mine below. You can grab that and put it into the credentials section of the config. 

Otherwise the only option is to wait for the PR to be merged and published.

<img width="1022" alt="Screenshot 2021-01-14 at 14 57 47" src="https://user-images.githubusercontent.com/13001723/104607693-fcaa1000-5678-11eb-989b-3d1b36838c52.png">

**Comment by Marvive** [comment]
Also having this issue. Also relatively new to hb. Can someone direct me to where I can find the logs for home bridge? I tried googling around with no luck. I'm running hb in a screen with my raspberry pi.
