### ISSUE TITLE
Request: Expose fan as a standalone accessory

### ISSUE THREAD

**Issue by epheterson** [lukasroegner/homebridge-dyson-pure-cool#149]
Having the fan within the air purifier controls is nice, but a standalone fan tile is a bit simpler to interact with in the home app. Could you consider adding an option to expose the fan as a standalone accessory, which will allow seeing what % it's at on the tile, and modifying the speed more easily?

**Comment by lukasroegner** [comment]
This plugin does not use the FAN type of HomeKit. All controls that you can see in the UI are part of the AIR PURIFIER type. Currently, there is no option to influence the way those controls are displayed in the Apple Home app.

**Comment by epheterson** [comment]
Hey, I realize it doesn't currently use the fan service but saw you have options to expose several extras as additional services to HomeKit. If you had an option to also expose a fan, we could use the Fan UI and Siri controls to more easily control it. The other Dyson plugin works this way, and I tried yours after theirs had an API issue (now resolved) and noticed this main difference.

**Comment by lukasroegner** [comment]
You are right, this is one of the main differences. Adding an option to switch the main accessory (air purifier) to use the fan type would mean that large parts of the source code would have to be rewritten. Thus, I won't even consider adding such an option in the future.
