### ISSUE TITLE
Plug-in seems to crash homebridge and .local cannot be accessed

### ISSUE THREAD

**Issue by iadamrodriguez** [lukasroegner/homebridge-dyson-pure-cool#150]
Has anyone had issues the last 24 hours where the plug in will work one minute, then it will not work the next?  I have double checked settings, uninstalled and reinstalled plug in without any luck.  I bet if I check within the next hour, it will work again.

All other devices using other plugs work flawlessly.

UPDATE:  I was running homebridge using the official image.  I thought since I was new I was having some kind of user error so I tried using HOOBS.  Same thing happened.  Everything was working perfectly until I installed this Dyson plug-in.  Now the server isn't responding and I cannot access homebridge.local or with my new setup hoobs.local.

Again, any help would be much appreciated.

Thanks in advance.

**Comment by lukasroegner** [comment]
Please provide detailed logs (start Homebridge with parameter `-D`) so that I can check whether there is a communication issue between Homebridge and your devices.

>  the plug in will work one minute, then it will not work the next?

What does "will not work" mean? Is the Apple Home app showing the accessories? Are they not responding to your commands?

**Comment by iadamrodriguez** [comment]
I reached out to Hoobs and they told me to access the "dashboard" using the IP address and that seemed to fix the issue.  I think it might be related to me using a Xfinity router.  Anyway, everything seems to be working properly now.  Will reach back out if I continue having issues with detailed logs.

Just an FYI, what I meant by "will not work" is that the devices would all show up properly in the home app, but when trying to turn on the Dyson device, it would just pin wheel and nothing would happen.  There would be no "no response" error or anything like that.  It was weird.  Then when I would try to go to homebridge.local or hoobs.local for each of the installation types respectively, it would state the server couldn't be reached even though everything would be working perfectly for the first 5 minutes or so using this method.

Anyway, seems like accessing the pi homebridge server using the IP address seems to fix everything.

Thanks again.
