### ISSUE TITLE
No more environmental data

### ISSUE THREAD

**Issue by schaelo** [lukasroegner/homebridge-dyson-pure-cool#151]
I noticed that no more environmental data (temperature and humidity) is communicated between my Pure Cool Link Tower and Homebridge. I tried going back to 1.8.1 and reinstalling the plugin but nothing seems to work. 
I can still control the Pure Cool Link tower but all the other data is not being updated.

**Comment by lukasroegner** [comment]
Please provide logs (start Homebridge with parameter `-D`), so that I can check whether the data arrived at the plugin correctly. The important log entries start with "MQTT"

**Comment by schaelo** [comment]
I reconfigured everything and it works now. Not sure what the problem was but thanks!
