### ISSUE TITLE
API doesn’t work anymore

### ISSUE THREAD

**Issue by HerrSpigot** [lukasroegner/homebridge-dyson-pure-cool#152]
Hi, I get this error constantly:

[2021-1-28 21:13:38] [DysonPureCoolPlatform] Signing in.
[2021-1-28 21:13:38] [DysonPureCoolPlatform] Error while signing in. Status Code: 403
[2021-1-28 21:13:38] [DysonPureCoolPlatform] API could not be reached. Trying again soon...

**Comment by Andybishop** [comment]
I'm getting the same, just stopped working today.  exactly the same errors.

**Comment by HerrSpigot** [comment]
It’s good to know I’m not alone. I thought the setup of my HomePod mini was the problem, because it just happened in time.

**Comment by thomas-4321** [comment]
Good to know, I´m not the only one with this 403 Status Code problem. Yesterday it worked great, today it´s not working.

**Comment by twentworth12** [comment]
+1

**Comment by felix-r9** [comment]
Same for me.

**Comment by pureflo** [comment]
![Screen Shot 2021-01-29 at 5 42 50 pm](https://user-images.githubusercontent.com/1269402/106241032-6f121700-6259-11eb-8ee6-e080354d014f.png)
Also the same going on here.

**Comment by mike4president** [comment]
Having the same issue...

29.1.2021, 08:18:08 [DysonPureCoolPlatform] Error while signing in. Status Code: 403
29.1.2021, 08:18:08 [DysonPureCoolPlatform] API could not be reached. Retry is disabled.

**Comment by PeterHsieh** [comment]
+1

**Comment by oripaamoni** [comment]
+1 same issue here

**Comment by jasonrig** [comment]
I updated the user agent as shown in PR #153 which appears to resolve the issue for me. I found this was used in the Dyson Link APK for Android.

**Comment by mike4president** [comment]
Sonos there going to be an update for the plug-in or what do I have to do to get it working again?

**Comment by jasonrig** [comment]
@mike4president you should be able to update now https://github.com/lukasroegner/homebridge-dyson-pure-cool/pull/153#issuecomment-769716792

**Comment by mike4president** [comment]
ok, after updating to 1.8.6 it is working again. thanks a lot!!

**Comment by sensationunddesign** [comment]
got this problem right now…
[1/29/2021, 2:43:23 PM] [DysonPureCoolPlatform] C4H-EU-NFC0431A - MQTT disconnected.
[1/29/2021, 2:43:24 PM] [DysonPureCoolPlatform] C4H-EU-NFC0431A - MQTT reconnecting.
recognized it, as the Dyson wasn't shut down after opening the window as usual.
can anybody help? Plugin V 1.8.6 - maybe @lukasroegner

**Comment by infinitedr** [comment]
I'm getting also getting the  same disconnected/reconnecting issue after updating to v1.8.6
[1/30/2021, 3:25:59 PM] [DysonPureCoolPlatform] VT8-KR-KBA4197A - MQTT disconnected.
[1/30/2021, 3:26:00 PM] [DysonPureCoolPlatform] VT8-KR-KBA4197A - MQTT reconnecting.
[1/30/2021, 3:26:31 PM] [DysonPureCoolPlatform] VT8-KR-KBA4197A - MQTT disconnected.
[1/30/2021, 3:26:32 PM] [DysonPureCoolPlatform] VT8-KR-KBA4197A - MQTT reconnecting.
As I'm very new to this homebridge stuff.. not sure how to fix this. Please help.

**Comment by felix-r9** [comment]
@infinitedr, @sensationunddesign please check if the IP address in your config file is correct. Also check if you can ping the Fans IP.

**Comment by infinitedr** [comment]
@felix-r9 [update] After turning on the dyson with its native dyson app. The 'disconnecting' issue went away. Not sure why but problem solved.

**Comment by sensationunddesign** [comment]
> @infinitedr, @sensationunddesign please check if the IP address in your config file is correct. Also check if you can ping the Fans IP.

thanks - that worked for me. I have no idea, why the ip has changed…

**Comment by Tesla-P100FX** [comment]
I am getting [DysonPureCoolPlatform] Error while signing in. Status Code: 401
 1:28:17 PM [DysonPureCoolPlatform] API could not be reached. Retry is disabled.
Pinged the IP address it is fine, Uninstalled and re installed plug in.
I can log into https://www.dyson.com/your-dyson fine with my user name and password 
0n 1.8.6

**Comment by alan-g-p** [comment]
I am getting the 401 error.
![image](https://user-images.githubusercontent.com/23020659/107595149-f1da9f00-6c67-11eb-97d7-36059bfdb4b1.png)

IP correct. Stopped working on upgrade to 1.8.6

**Comment by a19i23** [comment]
I'm new to this plugin and I'm also getting this api error
![image](https://user-images.githubusercontent.com/6509090/107607365-ddf25700-6bed-11eb-9de1-87af0a7850a1.png)

**Comment by townsmcp** [comment]
Same issue as reported in https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/159
I double checked the IP of the fan and HB IP address of the fan and they both match 😢 (my fan IP is static anyways but was worth double checking)

**Comment by Tesla-P100FX** [comment]
Here is what i did get rid of all other parameters, just use these three.   Uninstalled -  reinstalled and it started working  

{
        "ipAddress": "10.0.0.xxx",
        "serialNumber": "VS3-US-XXX####X",
        "isAirQualitySensorEnabled": true

**Comment by alan-g-p** [comment]
I logged out of the Dyson App and logged back in and now appears to be working on HomeBridge

**Comment by a19i23** [comment]
@alan-g-p I can't believe it but that worked for me.

**Comment by townsmcp** [comment]
@alan-g-p thanks that worked for me to

**Comment by lukasroegner** [comment]
As @alan-g-p mentioned, Dyson now requires to make an API call to check the "userstatus" before performing the actual sign-in. Logging in again in the app triggers this check. I published a fix that adds the check to the plugin, see #159. I would recommend to use the `credentials` option of the plugin, so that the Dyson API is not needed anymore.
