### ISSUE TITLE
[DysonPureCoolPlatform] No configuration provided for device with serial number

### ISSUE THREAD

**Issue by malcolmdeguelle** [lukasroegner/homebridge-dyson-pure-cool#154]
Here there Lukas,

I'm trying to get my head around this little problem I didn't know if you can shine some light exactly on what this error message means in the log file

I already have a config file set up with the correct serial numbers and IP addresses which matches the output from the API

1/30/2021, 7:11:39 PM [DysonPureCoolPlatform] Signed in.
1/30/2021, 7:11:40 PM [DysonPureCoolPlatform] No configuration provided for device with serial number GXB-US-NEA0XXXA.
1/30/2021, 7:11:40 PM [DysonPureCoolPlatform] No configuration provided for device with serial number CXB-US-NFA1XXXA.
1/30/2021, 7:11:40 PM [DysonPureCoolPlatform] Got devices from the Dyson API.

**Comment by lukasroegner** [comment]
Sorry for the late reply. If you still have issues, please post a sanitized version of the config here.

**Comment by MaikHoobs** [comment]
17.3.2021, 11:24:10 [DysonPureCoolPlatform] Checked user account.
17.3.2021, 11:24:10 [DysonPureCoolPlatform] Signing in.
17.3.2021, 11:24:11 [DysonPureCoolPlatform] Signed in.
17.3.2021, 11:24:11 [DysonPureCoolPlatform] No configuration provided for device with serial number NN2-EU-NEB3637A.
17.3.2021, 11:24:11 [DysonPureCoolPlatform] Got devices from the Dyson API.

[
    {
        "platforms": [
            {
                "platform": "DysonPureCoolPlatform",
                "username": "XXXX",
                "password": "XXXX",
                "countryCode": "DE",
                "devices": [
                    {
                        "ipAddress": "192.168.XXX.XXX",
                        "serialNumber": "NN2-EU-NEB3637A",
                        "enableAutoModeWhenActivating": false,
                        "enableOscillationWhenActivating": false,
                        "isNightModeEnabled": false,
                        "isJetFocusEnabled": false,
                        "isContinuousMonitoringEnabled": false,
                        "isTemperatureSensorEnabled": false,
                        "isHumiditySensorEnabled": false,
                        "isAirQualitySensorEnabled": false,
                        "isSingleAccessoryModeEnabled": false,
                        "isFullRangeHumidity": false,
                        "isHeatingDisabled": false
                    }
                ],
                "updateInterval": 60000,
                "retrySignInInterval": 0
            }
        ]
    }
]

**Comment by wickhama09** [comment]
Hey all, I was having this issue and I was able to resolve it. Although, I'm still not 100% sure what fixed it, here is what I remember trying lol.

Also, for what it's worth, I am a new user and just created my dyson account yesterday. I'm wondering if you all also have new accounts? I had read other issues about the API now requiring an email code, and people with existing setups needed to relog in the Dyson app, which gets that code established. Anyways, here is what all i did to get it working:

- Log out of Dyson app, attempt to log back in.
- Retrieve code from email, input into app, and log back in.
- Remove the device configuration in homebridge (not the whole platform, just the device through options in the config UI.)
- Restart Homebridge
-Add device back in to the plugin options, left all checkboxes unchecked. Entered IP address and double/triple checked that my serial number was correct (which it was)
- Restart Homebridge

There may have been a couple other restarts thrown into the mix, with me removing my username and password and changing serial numbers, etc. in between the restarts... but this last restart seems to have done the trick. I can now control this beast of a purifier from HomeKit!! Don't give up hope fellas! Good luck!
