### ISSUE TITLE
Oscillation switch hard to access in single accessory mode

### ISSUE THREAD

**Issue by jasongerbes** [lukasroegner/homebridge-dyson-pure-cool#156]
The switch to enable/disable oscillation is missing for my HP03 device. All other functions work as expected.

P.S. The readme needs to be updated to indicate that the HP03 is also supported.

**Comment by jasongerbes** [comment]
**Update:** After some further digging I have found the oscillate toggle.

![0F94081E-726D-42C2-8CEA-CC17A9C572EA](https://user-images.githubusercontent.com/13686180/107116570-0bcb5900-68d9-11eb-96d1-80c413e57892.png)

However, it is quite buried/hard to access when using “single accessory mode”. To access it, you must open the accessory, scroll to “Accessories”, open the “Fan” accessory, and then scroll down to the “Oscillate” toggle.

It would be great if a separate switch could be added, similar to the night mode switch.

**Comment by lukasroegner** [comment]
If you want the oscillation switch to be easier to access, you have to disable single accessory mode. 
I won't add another option to the config to add an exception to the single accessory mode, as the plugin's configuration already is way too complex.

**Comment by joshjohanning** [comment]
@lukasroegner 

> If you want the oscillation switch to be easier to access, you have to disable single accessory mode.

I do not have single accessory mode enabled and my oscillation configuration is just as buried as OP's.   HP-04 (with heat)

![image](https://user-images.githubusercontent.com/19912012/147139858-8732c5c7-3dd8-4932-ba13-220e726f3270.png)

config

```json
                {
                    "enableAutoModeWhenActivating": false,
                    "enableOscillationWhenActivating": true,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": false,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false
                }
```

**Comment by joshjohanning** [comment]
Edit: From OP's edit and other issues on here, I see it's working as expected (i was expecting a separate switch too)

**Comment by hommegithub** [comment]
Can it be looked at again?  I am having the same issue/request with my HP03
Also, temperate as a sensor don't seem to work as expected - I used HP03 as a condition to trigger a HomeKit plug to turn on my Air Con.
