### ISSUE TITLE
[Feature Request] Add auto night mode configuration option

### ISSUE THREAD

**Issue by jasongerbes** [lukasroegner/homebridge-dyson-pure-cool#157]
It would be great if you could add a configuration option to automatically enable night mode when the accessory is activated. 

This would be similar to the existing configuration options for oscillation and auto mode.

In my scenario, my fan is in a bedroom and used exclusively at night with night mode enabled.

**Comment by gabemunro** [comment]
Could a Homekit automation be an acceptable workaround? "When Accessory Dyson Purifier is turned on, turn on Night Mode"? Also doesn't it just stay activated for you when you turn the fan on/off? That second switch doesn't change state for me when I control the device via HomeKit.

**Comment by jasongerbes** [comment]
Oh of course! An automation is a perfect workaround.

Night mode is off every time the fan is turned on, similar to oscillation. But the automation is a suitable workaround :)

**Comment by Kentzo** [comment]
@jasongerbes https://github.com/lukasroegner/homebridge-dyson-pure-cool/pull/238

**Comment by lukasroegner** [comment]
Fixed in 2.3.0 with the help of @Kentzo
