### ISSUE TITLE
Does not work anymore error 401

### ISSUE THREAD

**Issue by henkied** [lukasroegner/homebridge-dyson-pure-cool#159]
Hello both my dysons are not working in homebridge anymore

I have 2 hombridge running both are not working. Any one know how to solved it

 [DysonPureCoolPlatform] Error while signing in. Status Code: 401
[DysonPureCoolPlatform] API could not be reached. Retry is disabled.

**Comment by GoTeslaGo** [comment]
seeing the same error. App is working so assume the API is still working but something may have changed

**Comment by knedd** [comment]
I am seeing the same error as well. App is working, but receiving the sign-on error in the log.

**Comment by Stewart06** [comment]
J'ai exactement le même problème actuellement. Il est possible que cela vienne d'une mise à jour du plugin pour correspondre à l'API. Ou alors cela vient des serveurs de chez Dyson.

I have the exact same problem now. It is possible that this came from a plugin update to match the API. Or it comes from Dyson servers.

**Comment by henkied** [comment]
Does the dyson work for you with Homekit?

**Comment by Stewart06** [comment]
Yes !

**Comment by krharrison1** [comment]
I have been seeing the 401 error in HB logs since yesterday. Restarting HB has no effect. I’m able to login to the Dyson website, my credentials are still good. Guessing that the API has changed again...

**Comment by jyjourdain** [comment]
Hi! Also here:
> [2/12/2021, 14:22:57] [DysonPureCoolPlatform] Error while signing in. Status Code: 401

How can I help?

**Comment by Stewart06** [comment]
Se qui est bizarre c’est que parfois le plugin arrive à se connecter !

**Comment by patowod** [comment]
Chiming in (Dyson login on their site via credentials (as in config) is working). Following Log entry:

[2/12/2021, 3:05:04 PM] [DysonPureCoolPlatform] Error while signing in. Status Code: 429
[2/12/2021, 3:05:04 PM] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.

**Comment by Stewart06** [comment]
![F7419D68-427F-4D59-9A1B-444AD576B98D](https://user-images.githubusercontent.com/63004191/107789984-8d483e80-6d52-11eb-9f24-0bba270882a9.jpeg)

J’ai remarqué que si je suis en wifi impossible de me connecter à mon compte Dyson. Alors que si je suis en 4G ça fonctionne.

**Comment by ndornquast** [comment]
I get same error.  This worked for last couple weeks great.. this week not so much.  I did installed the latest release which mention API fix.. but still fails.

Last success: (though worked for days later.. didn't re-auth)
[1/26/2021, 10:37:05 PM] [DysonPureCoolPlatform] Signing in.
[1/26/2021, 10:37:06 PM] [DysonPureCoolPlatform] Signed in.

Initial failure:
[2/11/2021, 1:09:44 PM] [DysonPureCoolPlatform] Signing in.
[2/11/2021, 1:09:45 PM] [DysonPureCoolPlatform] Error while signing in. Status Code: 403
[2/11/2021, 1:09:45 PM] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.


Failure after latest update:
[2/11/2021, 9:13:29 PM] [DysonPureCoolPlatform] Signing in.
[2/11/2021, 9:13:30 PM] [DysonPureCoolPlatform] Error while signing in. Status Code: 401
[2/11/2021, 9:13:30 PM] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.

Validated authentication username and pass at dyson.com.

**Comment by professoruss** [comment]
Having the same issue both with this plugin and a couple others.  I suspect Dyson change something on their end

**Comment by townsmcp** [comment]
Dyson seem to change this roughly every 6 months 😢

**Comment by KibosJ** [comment]
Over at https://github.com/etheralm/libpurecool/issues/37 they have found that making a GET request to the URL below, before authenticating it works :)

/v1/userregistration/userstatus?country=GB&email=YOUR_EMAIL_ADDRESS

**Comment by Soldiiier** [comment]
I’m getting 429 error, “too many attempts”

**Comment by Soldiiier** [comment]
> Over at [etheralm/libpurecool#37](https://github.com/etheralm/libpurecool/issues/37) they have found that making a GET request to the URL below, before authenticating it works :)
> 
> /v1/userregistration/userstatus?country=GB&email=YOUR_EMAIL_ADDRESS
> 
> I've tested it here and it works :)

What’s the base URL to send the get request to?

**Comment by KibosJ** [comment]
> I’m getting 429 error, “too many attempts”

> What’s the base URL to send the get request to?

It looks like they've added rate limiting to the API too, so too many requests will have you blocked for a while.

The full URL is https://appapi.cp.dyson.com/v1/userregistration/userstatus?country={{countrycode}}&email={{emailaddress}}

**Comment by Stewart06** [comment]
Ca ne fonctionne pas pour moi l'URL depuis safari en modifiant le country code et @mail.

**Comment by jyjourdain** [comment]
> Ca ne fonctionne pas pour moi l'URL depuis safari en modifiant le country code et @mail.

Idem pour moi…

**Comment by Stewart06** [comment]
Le plugin Dyson Pure Cool a réussi d’un coup à se connecter, sans rien que je fasse de particulier. Je vais éviter pendant un moment de le faire redémarrer...

**Comment by Stewart06** [comment]
![Uploading 9562BB3C-432C-43B9-9BE4-C16488864885.jpeg…]()

**Comment by Soldiiier** [comment]
> > I’m getting 429 error, “too many attempts”
> 
> It looks like they've added rate limiting to the API too, so too many requests will have you blocked for a while.
> 
> > What’s the base URL to send the get request to?
> 
> The full URL is [https://appapi.cp.dyson.com/v1/userregistration/userstatus?country={{countrycode}}&email={{emailaddress}}](https://appapi.cp.dyson.com/v1/userregistration/userstatus?country=%7B%7Bcountrycode%7D%7D&email=%7B%7Bemailaddress%7D%7D)

Thanks. This didn’t solve it for me though. Now I am getting 401 error.

**Comment by KibosJ** [comment]
> > > I’m getting 429 error, “too many attempts”
> > 
> > 
> > It looks like they've added rate limiting to the API too, so too many requests will have you blocked for a while.
> > > What’s the base URL to send the get request to?
> > 
> > 
> > The full URL is [https://appapi.cp.dyson.com/v1/userregistration/userstatus?country={{countrycode}}&email={{emailaddress}}](https://appapi.cp.dyson.com/v1/userregistration/userstatus?country=%7B%7Bcountrycode%7D%7D&email=%7B%7Bemailaddress%7D%7D)
> 
> Thanks. This didn’t solve it for me though. Now I am getting 401 error.

Strange, with that URL
```
GET /v1/userregistration/userstatus?country=GB&email=fakeuser@fakedomain.com HTTP/1.1
Host: appapi.cp.dyson.com
User-Agent: DysonLink/30794 CFNetwork/1220.1 Darwin/20.3.0
```

I get the following JSON response:

`{"accountStatus":"ACTIVE"}`

Then the original authentication request:

```
POST /v1/userregistration/authenticate?country=GB HTTP/1.1
Host: appapi.cp.dyson.com
User-Agent: DysonLink/30794 CFNetwork/1220.1 Darwin/20.3.0
Content-Type: application/json

{ "Email": "fakeuser@fakedomain.com", "Password": "FaKeP@ssw0rd" }
```

Returns this JSON

```
{
    "Account": "fakeaccount",
    "Password": "FaKeP@ssw0rd"
}
```

**Comment by lukasroegner** [comment]
I just published a fix (1.8.7) for the issue. Thanks to @KibosJ for providing the solution.

As pointed out in the README, the plugin provides a setting for storing the credentials locally, so that the Dyson API is not called. I would highly recommend to use this setting. This plugin uses an undocumented API, which can change at any time.

Also, please comment in English if you have issues.

**Comment by sensationunddesign** [comment]
@lukasroegner and where do I get the credentials? Have no idea 🤦‍♂️

**Comment by jyjourdain** [comment]
> @lukasroegner and where do I get the credentials? Have no idea 🤦‍♂️

Hi @lukasroegner, you export the log, you'll get a text file, and you look for "[DysonPureCoolPlatform] Credentials for device with serial number" for example, there will be a long string for each device…

**Comment by jyjourdain** [comment]
And thank-you very much @lukasroegner !

**Comment by sensationunddesign** [comment]
> > @lukasroegner and where do I get the credentials? Have no idea 🤦‍♂️
> 
> Hi @sensationunddesign, you export the log, you'll get a text file, and you look for "[DysonPureCoolPlatform] Credentials for device with serial number" for example, there will be a long string for each device…
 How does this go?

**Comment by jyjourdain** [comment]
> > > @lukasroegner and where do I get the credentials? Have no idea 🤦‍♂️
> > 
> > 
> > Hi @sensationunddesign, you export the log, you'll get a text file, and you look for "[DysonPureCoolPlatform] Credentials for device with serial number" for example, there will be a long string for each device…
> 
> How does this go?

@sensationunddesign, on HomeBridge, the button on the top right…
![Capture d’écran 2021-02-14 à 11 24 02](https://user-images.githubusercontent.com/13624170/107874074-44f66100-6eb7-11eb-9190-a0bc647e8d0f.png)
](url)

**Comment by asvictory3** [comment]
For anyone with this current issue, you can download the old logs in the "view logs" tab and hitting the download button. Scroll back in time a bit (while the device was functioning) and the credentials are in the txt document. Pasting this long string into the plugin settings window caused my fan to respond immediately after a HB server restart. Works even if you can't run the API currently.

**Comment by philipamour** [comment]
The plugin stopped working, getting this:
[2/18/2021, 12:31:02] [DysonPureCoolPlatform] Error while signing in. Status Code: 401
[2/18/2021, 12:31:02] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.

**Comment by philipamour** [comment]
> For anyone with this current issue, you can download the old logs in the "view logs" tab and hitting the download button. Scroll back in time a bit (while the device was functioning) and the credentials are in the txt document. Pasting this long string into the plugin settings window caused my fan to respond immediately after a HB server restart. Works even if you can't run the API currently.

Not working for me - the log is not long enough. 🙁

**Comment by manningtelfer** [comment]
If we are a new user of this plugin and we are encountering the below, do we just wait and try again later or is there a workaround to retrieve the credentials?

```
[2/18/2021, 12:31:02] [DysonPureCoolPlatform] Error while signing in. Status Code: 401
[2/18/2021, 12:31:02] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.
```

**Comment by arkku** [comment]
I also have this problem. I may currently be rate limited since I can't login with the Dyson Link app on a new installation (was trying to mitm the connection), but an existing installation of Dyson Link works just fine… Any ideas?

**Comment by marioschaper** [comment]
same problem here. updated to the newest Version and getting the 401 Error.

> The plugin stopped working, getting this:
> [2/18/2021, 12:31:02] [DysonPureCoolPlatform] Error while signing in. Status Code: 401
> [2/18/2021, 12:31:02] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.

**Comment by Soldiiier** [comment]
As with me now.

**Comment by marmitol** [comment]
Same error.

I have upgraded to the Hombrige versionv 1.3.2 and it shows this error.

[05/03/2021, 16:49:29] [DysonPureCoolPlatform] Checked user account.
[05/03/2021, 16:49:29] [DysonPureCoolPlatform] Signing in.
[05/03/2021, 16:49:31] [DysonPureCoolPlatform] Error while signing in. Status Code: 401
[05/03/2021, 16:49:31] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.

With the previous version it worked fine.

**Comment by markholland** [comment]
https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/166#issuecomment-790856416

**Comment by marmitol** [comment]
Thank You.
Now working fine.
Nice.

**Comment by bondskin** [comment]
See [https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/166]

**Comment by lukasroegner** [comment]
See https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/166#issuecomment-841255154
