### ISSUE TITLE
API Error 429

### ISSUE THREAD

**Issue by Panic135** [lukasroegner/homebridge-dyson-pure-cool#160]
Hi! 

When using homebridge to connect, the API continually gives the following error 

[13/02/2021, 18:13:30] [DysonPureCoolPlatform] Error while signing in. Status Code: 429
[13/02/2021, 18:13:30] [DysonPureCoolPlatform] API could not be reached. Retry is disabled.

I have double checked connection, username and password, country code etc - The credentials also worked fine a week ago, now it says they have been entered incorrectly. 

Thanks!

**Comment by lukasroegner** [comment]
429 = too many requests. Stop the plugin, wait for a few hours, update the plugin to the latest version (see #159) and try again.

**Comment by Panic135** [comment]
Bob on! The update works and I’ve saved the credentials in a separate text file in case I ever lose them again! -Thanks for the rapid response 👍🏻
