### ISSUE TITLE
Throw error in console if device is not responding (with connection details)

### ISSUE THREAD

**Issue by SInCE** [lukasroegner/homebridge-dyson-pure-cool#161]
Hi @lukasroegner,

first of all, thanks a lot for this plugin! Its awesome :)

 I had to replace my Humidify&Cool on warranty. So I installed the new one, added it to the network, updated the config (removed the stored "credentials" information so it queries the Dyson API for details). What I missed is updating the IP used in the configuration. I didn't notice that for a while as the terminal in homebridge didn't return any error message that it couldn't reach the device or something similar.

**Current behaviour:** No timeout or error warning if configured device IP is wrong.
**Expected behaviour:** In case of a timeout or no response after some time, it should write an error into the console stating that the device is not responding with connection details (e.g. IP used for the request + name/serialnumber of the device)

Its a minor thing for sure, but very helpful to have validated and shown 👍

**Comment by lukasroegner** [comment]
Hi @SInCE, the plugin actually produces logs when it cannot reach a device, however, as those messages might spam our logs, they are only visible in debug mode (`-D`).

**Comment by codyc1515** [comment]
The ideal thing to do in that instance would actually be to mark the device as unreachable (from a platform perspective). This would be a prompt for most people to then check the logs.
