### ISSUE TITLE
TP02 show nothing after setup

### ISSUE THREAD

**Issue by no-Legend** [lukasroegner/homebridge-dyson-pure-cool#162]
I just own a tp02 from end of 2017.
The login of the plugin word, but it looks like that Homebridge is not getting any updates of the fan.
Fan is set on with the Dyson app but Homebridge show the device is off.
Also all status information are not shown in Homebridge.
Please see attached screenshots.

![IMG_2725](https://user-images.githubusercontent.com/13560035/108332228-da536700-71cf-11eb-9b44-523b16801cdc.PNG)
![IMG_2726](https://user-images.githubusercontent.com/13560035/108332278-e50dfc00-71cf-11eb-8d1e-1fe40601dc72.PNG)

**Comment by chayerd** [comment]
Hello,
I have the same issue. Homebridge works, plugin works but does not communicate with fan and it doesn't report communication problem even if fan is unplugged.

does it work now for you? what is the solution ?
thanks

**Comment by thumax** [comment]
Turn on debug logging in homebridge and see if the errors are the same as in #185 .
