### ISSUE TITLE
Homekit automations do not work with Homebridge 1.3.2

### ISSUE THREAD

**Issue by jchhenderson** [lukasroegner/homebridge-dyson-pure-cool#167]
with Homebridge v1.3.2, HomeKit automations do not work (nothing happens).  Also Dyson status is no longer visible out side the home.  Manual changes work fine.

None of these problems exist withy Homebridge v1.3.0 (bit not sure about 1.3.1)

**Comment by codyc1515** [comment]
I'm not having this issue so it's likely something with your setup.

**Comment by jchhenderson** [comment]
yes, I think you are right.  I downgraded back to 1.3 and it worked.  I then re-upgraded back to 1.33 and it still worked.

No clue what happened.
