### ISSUE TITLE
[Feature Request] Multiple Fans on different accounts

### ISSUE THREAD

**Issue by jaer0d** [lukasroegner/homebridge-dyson-pure-cool#169]
If one has multiple Dyson fans in a household on different accounts, it would be a great feature to be able to add multiple fans that are under different usernames and passwords. Unsure if this is already a feature or able to be done somehow, but after a couple weeks of trying to google and look around I have found nothing on the subject - (every time I would attempt to add another fan via the homebridge GUI or command line, it would break my setup, I assume it is because the "DysonPureCoolPlatform" name is the same inside of of each fan instance in the config.json file and it cannot initialize multiples of the same item name. Changing the platform name to "DysonPureCoolPlatform2" did not help either, I assume since it cannot trace back to the plugin name. My workaround for this is running one homebridge instance on 2 different computers, but I'd much rather have them on one if possible. Thanks for the awesome work you all do with this project!

**Comment by lukasroegner** [comment]
You can now do that with the latest version 2.0.0: as getting the credentials for each device is now done via the credentials generator, you can add multiple devices from different accounts.
