### ISSUE TITLE
Cannot login from CN account

### ISSUE THREAD

**Issue by iambbbb** [lukasroegner/homebridge-dyson-pure-cool#171]
Fix it

**Comment by n3ih7** [comment]
I'd say fix it yourself and make a PR instead of yelling for help.

**Comment by iambbbb** [comment]
Yelling?? Are you talking about you?  right?

**Comment by iambbbb** [comment]
Already fix it.

**Comment by iambbbb** [comment]
> I cannot log in to the Dyson account from Email. The CN account they use a phone number to log in. I don’t know if I can’t download API for this reason.
> Is it possible to add a project similar to the following method to change the address of API to CN
> ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
> self._email = email
> self._password = password
> self._country = country
> self._logged = False
> self._auth = None
> self._headers = {'User-Agent': DYSON_API_USER_AGENT}
> if country == "CN":
> self._dyson_api_url = DYSON_API_URL_CN
> else:
> self._dyson_api_url = DYSON_API_URL
> ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
> I found the method elsewhere but I don’t know if it can be changed.
