### ISSUE TITLE
The Plug-in Doesn’t work anymore

### ISSUE THREAD

**Issue by ands0me** [lukasroegner/homebridge-dyson-pure-cool#174]
Since Homebridge-ui-x 1.3 the plug-in doesn’t respond. When the Dyson is switched ok trough HomeKit the state is to update but it doesn’t switch on.
There’s no log to this issue in Homebridge.

**Comment by dhut1832** [comment]
Same for me. I also downloaded older version and still wouldn't work right

**Comment by dhut1832** [comment]
Just read some other comments and found a solution. I logged out of app on my phone, then logged back in. I then restarted homebride and it started verging in HomeKit again.

**Comment by ands0me** [comment]
> Just read some other comments and found a solution. I logged out of app on my phone, then logged back in. I then restarted homebride and it started working in HomeKit again.

I tried it. Doesn’t work for me. :(

**Comment by mschmees** [comment]
after a long time of usage it still does not work anymore.

**Comment by siim911** [comment]
I think this issue has appeared after new security changes during log in which require a code sent to the email 

Am also suffering from the same issue !!

**Comment by ands0me** [comment]
Hey guys I have the solution: restart your Homebridge and copy the credentials of your Dyson Pure cool Device. And paste in your config of Dyson pure cool.
![4843FCF5-B6E6-4932-A6DF-4D79F7E65BEA](https://user-images.githubusercontent.com/74508966/113052791-d7bd3780-91a7-11eb-84e5-ee44f3586cd3.jpeg)

**Comment by idechev** [comment]
The plug-in stopped working even with the credentials entered in the config

**Comment by ands0me** [comment]
> The plug-in stopped working even with the credentials entered in the config

Are your credentials correct?
Copy them without any space.

**Comment by idechev** [comment]
All correct. I re-copied the credentials and checked - no spaces or new lines. I am using HomeBridge v 1.3.4. All was working fine some weeks ago.

**Comment by ands0me** [comment]
> All correct. I re-copied the credentials and checked - no spaces or new lines. I am using HomeBridge v 1.3.4. All was working fine some weeks ago.

Die you restart Homebridge Service after typing the credentials?

I am using also v1.3.4 and it’s working fine only with the credentials. Try also after typing credentials and restart, log out from the Dyson App and Login.

**Comment by idechev** [comment]
Thanks. Yes, I restarted. I even uninstalled and installed the plugin, configured again and still not working. Everything is showing up in the Home app, but nothing is working (switching on/off, sensors, etc.). I don't see any error messages in the log.
