### ISSUE TITLE
Accessory stops updating if the Dyson is unplugged physically

### ISSUE THREAD

**Issue by codyc1515** [lukasroegner/homebridge-dyson-pure-cool#176]
As far as I can tell the plug-in doesn’t try to reestablish a connection after it doesn’t respond anymore.

**Comment by lukasroegner** [comment]
If the connection to a device is lost (i.e. MQTT disconnect) the plugin should start trying to reconnect periodically. You can start homebridge in debug mode (parameter `-D`) to get the full MQTT logs.

**Comment by codyc1515** [comment]
Yeah it doesn’t though. There was no indication in the logs as to why this might be however.

**Comment by codyc1515** [comment]
Sorry to say but there isn’t actually anything there. The updates just stop.
