### ISSUE TITLE
API Error code 400 

### ISSUE THREAD

**Issue by rose-cottage** [lukasroegner/homebridge-dyson-pure-cool#183]
I have been trying to get this plug in working, and it falls over at the same point. It has given a 401 status code, but today it is only status code 400. I tried (twice) logging off the Dyson app and logging back on with the 2FA and the app works find... but the plug in still fails at the same point.

**Comment by bunique2k** [comment]
So is there still no fix?

**Comment by GeezusChrotch** [comment]
Same issue. Logging out and in, restarting server doesn’t help.

**Comment by henkied** [comment]
same here

**Comment by hwbai** [comment]
Same here. Logging out and in doesn't help

**Comment by lukasroegner** [comment]
A new version is published with a completely new approach for 2FA, that should solve your issue. If that's not the case, feel free to reopen the issue.

**Comment by hwbai** [comment]
Perfectly solved my issue. Thanks!

**Comment by rose-cottage** [comment]
Fixed and working! Great. Thanks very much.

**Comment by bunique2k** [comment]
I was unable to receive my credentials.
