### ISSUE TITLE
Please add support for TP09

### ISSUE THREAD

**Issue by fkikood** [lukasroegner/homebridge-dyson-pure-cool#184]
Please add support for Dyson Purifier Cool Formaldehyde (TP09).

**Comment by lukasroegner** [comment]
Please check the logs for this message and post the product type here:
```
Device with serial number XXXXXX not added, as it is not supported by this plugin. Product type: XXX
```

**Comment by fkikood** [comment]
Product type: 438E

thank you

**Comment by lukasroegner** [comment]
@fkikood This is the same product type as the TP07. Support has been added today, check out the latest version of the plugin. If you still have problems, feel free to reopen the issue.
