### ISSUE TITLE
HP04 No longer working

### ISSUE THREAD

**Issue by jdgorelick** [lukasroegner/homebridge-dyson-pure-cool#185]
I believe this is due to a new firmware update, but my HP04 now is stuck on "All Off" in HomeKit and will not turn on or change any status using HomeKit. Shows temperature as 32 degrees as well.

**Comment by McRip** [comment]
My TP02 is currently not working either. Unplugging it did not solve the problem. The Dyson App is working properly.

**Comment by jdgorelick** [comment]
Yep same issue when I check ed my logs. Lots of lines saying "MQTT Disconnected"

**Comment by thumax** [comment]
I have the same problem with my PH01 and I believe #134 is the same. Any idea how to troubleshoot this?

**Comment by thumax** [comment]
> I have the same problem with my PH01 and I believe #134 is the same. Any idea how to troubleshoot this?

It turns out that in my case it actually was a DHCP issue: My Dyson got assigned a different IP address than the one that was set in the homebridge config block.

**So, lesson learned: If you see frequent "MQTT reconnecting" errors, check the value of the IP address**:

```
"platform": "DysonPureCoolPlatform",
            "devices": [
                {
                    "ipAddress": "XXX.XXX.XXX.XXX",
                    […]
```
