### ISSUE TITLE
Cannot hide switch for continuous monitoring

### ISSUE THREAD

**Issue by phteven9** [lukasroegner/homebridge-dyson-pure-cool#187]
I activated the option "Enable Continuous Monitoring" in the settings for testing purposes. After disabling that option and several restarts (and updates in the meantime) the switch won't disappear in HomeKit.
I'm using Dyson TP04.

**Comment by lukasroegner** [comment]
There are some ways you could remove it from HomeKit:
- Temporarily remove the device from the array, restart Homebridge, add the device to the array again, restart Homebridge
- Temporarily disable `isNightModeEnabled`, `isContinuousMonitoringEnabled` and `isJetFocusEnabled`, restart Homebridge, enable `isNightModeEnabled` and/or `isJetFocusEnabled` again,  restart Homebridge
