### ISSUE TITLE
error adding dyson fan with new update

### ISSUE THREAD

**Issue by just808b** [lukasroegner/homebridge-dyson-pure-cool#188]
Hi,

I have followed the new instructions to get credentials which works ok.  I then copied and pasted the code with the new credentials and I get an error message in the logs.  

[DysonPureCoolPlatform] Check the devices property, it has to be a valid array.

In devices the code is:

{
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "devices": [
                {
                    "ipAddress": "xxxxxxxx",
                    "serialNumber": "xxx-UK-xxxxxxx",
                    "credentials": "verylong=",
                    "enableAutoModeWhenActivating": false,
                    "enableOscillationWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false
                }
            ],
            "updateInterval": 60000,
            "credentialsGeneratorPort": 48000
        }
    ]
}

**Comment by just808b** [comment]
I thought to leave it for a while and try again.  So I uninstalled and installed again and then restarted and completed the entire process again and now have different error in the logs.

5/22/2021, 1:03:23 PM [DysonPureCoolPlatform] Some devices are missing credentials. Please visit the credentials generator (see README) to retrieve them and add them to the configuration.

**Comment by schmudi** [comment]
Same here. I wondered if I have done a configuration error, but as you have the exact same error perhaps something else is wrong.

My configuration:

```
{
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "devices": [
                {
                    "ipAddress": "XXX.XXX.XXX.XXX",
                    "serialNumber": "C4H-EU-XXXXXXXX",
                    "credentials": "644CHARACTERS",
                    "enableAutoModeWhenActivating": false,
                    "enableOscillationWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false
                }
            ],
            "updateInterval": 60000,
            "credentialsGeneratorPort": 48000
        }
    ]
}
```
Error message in Hoobs protocol:
[DysonPureCoolPlatform] Check the devices property, it has to be a valid array.

**Comment by schmudi** [comment]
@just808b: But you have just the one device and credentials are available?

**Comment by just808b** [comment]
> @just808b: But you have just the one device and credentials are available?

yes just one device Dyson TP04 (Pure cool tower air purifier) and copied and pasted credentials into the relevant space.  Although the first and last digits were the same as previously (didnt check all of them)

**Comment by lukasroegner** [comment]
The error message `Check the devices property, it has to be a valid array.` only occurs if the devices property is not a well-formed JSON array. You could copy your configuration into a JSON validator (e.g. https://jsonlint.com) and see whether there is an issue with the config (e.g. missing quotes or missing colon after the long credentials string).

**Comment by schmudi** [comment]
Thank you for your great work and coming back to us so quickly. In my case it's literally the code above (just ipAddress, serial number and credentials within the pharentesis changed) that is my configuration.
When checking my real configuration as well as the code above in https://jsonlint.com the result is "Valid JSON".

**Comment by lukasroegner** [comment]
That's really weird. I would suggest to perform the following steps, restart Homebridge and check for errors in the logs after each step

**1. remove all entries from the devices array**
The plugin should start without issues. It won't expose any devices to HomeKit.

**2. add just one entry with the properties for IP address and serial number**
```
{
  "ipAddress": "XXX.XXX.XXX.XXX",
  "serialNumber": "XXX-XX-XXXXXXXX"
}
```
The plugin should now complain about the missing credentials.

**3. add the credentials**
```
{
  "ipAddress": "XXX.XXX.XXX.XXX",
  "serialNumber": "XXX-XX-XXXXXXXX",
  "credentials": ""
}
```
The plugin should now expose the device.

If all of the steps above succeed, start adding the additional properties one by one.

**Comment by lukasroegner** [comment]
> As update interval and port number is already in the configuration, those fields are empty in the HOOBS configuration. Could this be the problem?

Can you explain that further?

**Comment by schmudi** [comment]
The updateInterval and the credentialsGeneratorPort are as well in the configuration as well as as separate fields in the Hoobs GUI. But they don't seem to be linked.
![Capto_Capture 2021-05-26_06-38-40_PM](https://user-images.githubusercontent.com/38379660/119698795-e5aed200-be51-11eb-90bf-46837d99ea85.png)
However even if after updating 60000 for the update interval and 48000 for port number credentials configuration the result is them same.

**Comment by lukasroegner** [comment]
Honestly, this has been a bit of a waste of time...please be sure to get to know the basics of Homebridge before filing such an issue: you just added the whole JSON from the README into the text field that is meant to be used for the devices array. I assume (I neither use Hoobs nor any other graphical interface for Homebridge configuration) that you just have to enter the `devices` array into the text field, i.e.

```
[
  {
    "ipAddress": "XXX.XXX.XXX.XXX",
    "serialNumber": "XXX-XX-XXXXXXXX",
    "credentials: "xxxxxxxxxxxxxxxx...xxxxxx"
  }
]
```

**Comment by schmudi** [comment]
I am very sorry I took up so much of your valuable time with my ignorance.
Nevertheless, thank you very much for your patience and your inputs, with these adjustments it worked.

**Comment by just808b** [comment]
> I am very sorry I took up so much of your valuable time with my ignorance.
> Nevertheless, thank you very much for your patience and your inputs, with these adjustments it worked.

im confused, what adjustments did you make, to make it work?

**Comment by just808b** [comment]
after some messing around I have got it.  In case anyone else with Hoobs is confused.

copy and paste code after devices

[
    {
        "ipAddress": "",
        "serialNumber": "-UK-",
        "credentials": "",
        "enableAutoModeWhenActivating": false,
        "enableOscillationWhenActivating": false,
        "isNightModeEnabled": false,
        "isJetFocusEnabled": false,
        "isContinuousMonitoringEnabled": false,
        "isTemperatureSensorEnabled": false,
        "isHumiditySensorEnabled": false,
        "isAirQualitySensorEnabled": false,
        "isSingleAccessoryModeEnabled": false,
        "isFullRangeHumidity": false,
        "isHeatingDisabled": false
    }
]
