### ISSUE TITLE
Spinning symbol on Dyson purifier

### ISSUE THREAD

**Issue by gferreroferri** [lukasroegner/homebridge-dyson-pure-cool#191]
Since last update I get a spinning symbol in Home app for my Dyson purifier when it is deactivated. It does not go away, no matter what I do

**Comment by hwbai** [comment]
I got into the same situation

**Comment by gferreroferri** [comment]
I noticed that actually it was not working. I have seen a new update to the plugin yesterday, so I need to check now once I get it configured (I am having problems now to get it working)

**Comment by hwbai** [comment]
I am having the same issue and can confirm on my end that mine is not working

**Comment by gferreroferri** [comment]
Finally I have got it working again after yesterday's update
