### ISSUE TITLE
Readme on getting credentials not working?

### ISSUE THREAD

**Issue by skazzyskills** [lukasroegner/homebridge-dyson-pure-cool#192]
Any help appreciated. Here is what it says:
Step 3: Open a browser and navigate to http://<IP-ADDRESS-OF-HOMEBRIDGE-HOST>:48000/ (where <IP-ADDRESS-OF-HOMEBRIDGE-HOST> is the IP address of the host your homebridge instance is running on).

Step 4: Follow the steps on the website to retrieve the credentials for all of the devices that are registered in your Dyson account.

I entered in:
http://<192.168.7.xxx>:48000/ 

invalid 'site' and it does not bring me to see the Dyson API. What am I missing?

**Comment by biocross** [comment]
+1 Does not work for me as well.

**Comment by biocross** [comment]
Nevermind, got it to work. Need to follow Step 1 in the README and add this to `config.json` first to get the link to work:

```
"platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "devices": [],
            "updateInterval": 60000,
            "credentialsGeneratorPort": 48000
        }
    ]
```

**Comment by skazzyskills** [comment]
@biocross Can you help me here? Do I delete everything in my config file and just use this:
{
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "devices": [],
            "updateInterval": 60000,
            "credentialsGeneratorPort": 48000
        }
    ]
}

Or do I keep some part of my config and add this part at the end. This is what I have now:

{
    "bridge": {
        "name": "Homebridge 2829",
        "username": "xxxx",
        "manufacturer": "Dyson",
        "model": "Bridge",
        "port": 51008,
        "pin": "xxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8583,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        }
    ]
}

**Comment by biocross** [comment]
@skazzyskills You can keep your existing config file, just add the new object in the `platforms` section and restart homebridge.

**Comment by skazzyskills** [comment]
Thanks, but where exactly do I put it in here:

{
    "bridge": {
        "name": "Homebridge 2829",
        "username": "0E:A4:3B:11:28:29",
        "manufacturer": "Dyson",
        "model": "Bridge",
        "port": 51008,
        "pin": "423-26-306"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8583,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
            
        }
    ]
}


And do I cut and paste all of this?
{
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "devices": [],
            "updateInterval": 60000,
            "credentialsGeneratorPort": 48000
        }
    ]
}


Any help appreciated!!

**Comment by biocross** [comment]
@skazzyskills Your final config should be this:

```
{
  "bridge": {
    "name": "Homebridge 2829",
    "username": "xxxx",
    "manufacturer": "Dyson",
    "model": "Bridge",
    "port": 51008,
    "pin": "xxxx"
  },
  "accessories": [],
  "platforms": [
    {
      "name": "Config",
      "port": 8583,
      "auth": "form",
      "theme": "auto",
      "tempUnits": "c",
      "lang": "auto",
      "platform": "config"
    },
    {
      "platform": "DysonPureCoolPlatform",
      "devices": [],
      "updateInterval": 60000,
      "credentialsGeneratorPort": 48000
    }
  ]
}
```

**Comment by skazzyskills** [comment]
Thank you very much for that! It accepted the config.

After restart, I then go to this site? And input my ip address of the Pi?

http://<IP-ADDRESS-OF-HOMEBRIDGE-HOST>:48000/

So something like..

http://<192.168.7.226>:48000/


Is that it, or am I missing something? If so, it’s not working. However, I do notice that the Pi is actually on ip6 so the address format for it is much different than ip4. Could this be the issue?

Thanks for your help!

Shawn Skalinski
***@***.***

**Comment by skazzyskills** [comment]
Oh never mind..found the ip4..works! Thanks so much for your help!!


Shawn Skalinski
***@***.***

**Comment by mpatgojira** [comment]
I am having the same issue, when entering "http://<172.xx.xx.xxx>:48000/" I am not getting any results. 

My JSON is set at

{
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "devices": [],
            "updateInterval": 60000,
            "credentialsGeneratorPort": 48000
        }
    ]
}
