### ISSUE TITLE
Getting credentials - last step blank page

### ISSUE THREAD

**Issue by alberthchau** [lukasroegner/homebridge-dyson-pure-cool#193]
When I go through the credentials process, after I enter my password (correctly) and 2FA code, I get to the page that looks like this:

![image](https://user-images.githubusercontent.com/19624944/120881585-0f20d980-c587-11eb-9a9b-4601680d12e2.png)

Where should the code be located?

**Comment by lukasroegner** [comment]
The list of devices and their corresponding credentials should show up below the heading "Credentials". 
Can you double check that you used the correct Dyson account and that you have a supported device registered in this account?

**Comment by alberthchau** [comment]
Thanks, it still didn't work but I tried with a different dyson account registered with the same advice and it worked.
