### ISSUE TITLE
Array issue with Hoobs

### ISSUE THREAD

**Issue by damiang1** [lukasroegner/homebridge-dyson-pure-cool#194]
HI Lucas. Thanks for your hard work with this plugin. But I have tried every permutation I can think of to get it to work but I still keep getting [DysonPureCoolPlatform] Check the devices property, it has to be a valid array. This is using HOOBS. What can I be missing with my config? Credentials verified, SN and ip address static, but no go...

Thank you

 { "platforms": [{ "platform": "DysonPureCoolPlatform", "devices": [{ "ipAddress": "192.168.1.95", "serialNumber": "VS2-US-XXXXXXX", "credentials": "eyJTZXJpYWwetc...", "enableAutoModeWhenActivating": false, "enableOscillationWhenActivating": false, "isNightModeEnabled": false, "isJetFocusEnabled": false, "isContinuousMonitoringEnabled": false, "isTemperatureSensorEnabled": false, "isHumiditySensorEnabled": false, "isAirQualitySensorEnabled": false, "isSingleAccessoryModeEnabled": false, "isFullRangeHumidity": false, "isHeatingDisabled": false }], "updateInterval": 60000, "credentialsGeneratorPort": 48000 }] }

**Comment by lukasroegner** [comment]
Please check out issue #188 where someone also had issues with Hoobs and the device array.

**Comment by damiang1** [comment]
Thanks Lucas,  Got it working per the thread.

And again thanks for the great plugin

Regards

Damian

**Comment by eddie1590** [comment]
> Thanks Lucas, Got it working per the thread. And again thanks for the great plugin Regards Damian
> […](#)

Hey Damian, I went to thread issue #188 but I didn’t see a clear answer on how to get the Dyson devices to appear on Homekit. I am also using Hoobs. You mentioned that you got it working? How were you able to do it if may ask? Thanks your time.

**Comment by damiang1** [comment]
Hi Eddie,

It was oversimplified how I got it finally working.  Once you get your credentials from Dyson, DONT follow the config directions (included herein) but rather just use this simple device setup config instead (here’s mine for reference).  All you need is the IP address of your Dyson device on your network, its serial number and the credentials and you should see the device in HomeKit.   For months I was trying all kinds of various configs to no avail until Dyson set up verification of credentials.

Regards

Damian
