### ISSUE TITLE
Just says “Turning on” and no action

### ISSUE THREAD

**Issue by dhut1832** [lukasroegner/homebridge-dyson-pure-cool#195]
I’m having an issue controlling heat/cool fan in HomeKit.  When I try to turn on fan in home kit it says “turning on” but nothing happens. Eventually it stops and goes back to show an off state in HomeKit. The dyson app works fine. I’m seeing an issue even after reserving the IP address . No errors in logs. 

Using version 2.0.3

**Comment by Dex-ctrl** [comment]
Same here
[
    {
        "ipAddress": "192.xxx.xx.x",
        "serialNumber": "CH",
        "credentials": "lonG"
        "enableAutoModeWhenActivating": true,
        "enableOscillationWhenActivating": true,
        "isNightModeEnabled": true,
        "isJetFocusEnabled": false,
        "isContinuousMonitoringEnabled": false,
        "isTemperatureSensorEnabled": true,
        "isHumiditySensorEnabled": true,
        "isAirQualitySensorEnabled": true,
        "isSingleAccessoryModeEnabled": false,
        "isFullRangeHumidity": false,
        "isHeatingDisabled": false
    }
]

showing this in terminal:

[DysonPureCoolPlatform] xxxxxxxxxx - set Active to 1: {"fpwr":"ON","fmod":"AUTO","oson":"ON"}

**Comment by hdasmith** [comment]
Having the same problem. Using a Dyson TP02. The Dyson app is working fine.

**Comment by Marvive** [comment]
Same Issue here

**Comment by hdasmith** [comment]
Unfortunately not, checked my IP addresses, and all as should be on reserved addresses.

**Comment by WolfgangWagnerDevelopments** [comment]
Reading the solution (wrong ip address) i already gave up because it seems to be right
Then i changed it not having leading zeros (following the mask written in the guide (xxx.xxx.xxx.xxx) and its working now
Great tip guys to check the ip - now its working ! Horray!

**Comment by pattyqubed** [comment]
So im having this same issue but the IP address is all correct and matching. I cannot figure out for the life of me what is wrong.

**Comment by thumax** [comment]
Turn on debug logging in homebridge and see if the errors are the same as in #185 .

**Comment by dhut1832** [comment]
@thumax how do you enable/disable debugging?

**Comment by thumax** [comment]
> @thumax how do you enable/disable debugging?

![debughb](https://user-images.githubusercontent.com/38001267/127905753-3f886a55-9d79-44ab-9d80-fe02f5035f7c.png)

In the Homebridge UI, click the three dots in the upper righthand corner, select Homebridge Settings and switch debugging to on. Then restart Homebridge. You will now see much more detailed logs.

**Comment by dhut1832** [comment]
@thumax,

I don’t have that option in my homebridge. What version are you using?

**Comment by thumax** [comment]
> @thumax, I don’t have that option in my homebridge. What version are you using?
Homebridge 1.3.4. and that screenshot is from homebridge-config-ui-x v4.41.2. Maybe you're using the app instead of the web UI? I never tried the app, so I'm not sure.
