### ISSUE TITLE
Dyson devices not appearing on Homekit using HOOBS Homebridge.

### ISSUE THREAD

**Issue by eddie1590** [lukasroegner/homebridge-dyson-pure-cool#197]
First I would like to thank all the people that make these plug-ins possible. 
I had my Dyson devices previously working with the plug-in “Dyson Link” published on 1/29/21 by author Joeng. 
I understand now Dyson has a new 2 form authentication that has left that plug-in not to work and a new one has been created by author lukas.roegner called “Dyson Pure Cool” and published on 5/24/21.
I’m not a super professional but I am a bit knowledgeable to some degree when it comes to this process. However, I am obviously missing something and if anyone has resolved this problem and can help I would greatly appreciate it. 
So I follow the instructions:
“Step 1: Configure the plugin (don't add devices to the devices array if you don't already have the credentials for them). If you're setting up the plugin for the first time, you can simply use the following configuration:”
{
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "devices": [],
            "updateInterval": 60000,
            "credentialsGeneratorPort": 48000
        }
    ]
}
“Step 2: Start homebridge”

“Step 3: Open a browser and navigate to http://<IP-ADDRESS-OF-HOMEBRIDGE-HOST>:48000/ (where <IP-ADDRESS-OF-HOMEBRIDGE-HOST> is the IP address of the host your homebridge instance is running on)”.

Okay, I’ll explain something here that I learned by trial and error. For those having trouble. This next example is how retrieved the credentials. It wants you to add the IP address of the Homebridge, in my case I am using Hoobs on a Raspberry Pi and this example is how I was able to generate the credentials.   http://123.456.7.89:48000/    .Please note that the IP address I used on this example is not real and used just to show how the layout should be with YOUR IP ADDRESS before copying and pasting to the search bar. 

“Step 4: Follow the steps on the website to retrieve the credentials for all of the devices that are registered in your Dyson account”.

So I get to the website where it asks for the country you live in, Dyson account email, Dyson account password and the security code that Dyson sends to you via Email. I successfully go through the process and I get to the page where it lists all my Dyson devices and provides “credentials” for each of the devices. Disclaimer: I have checked to make sure my devices are compatible with this plug-in and they all are. 

“Step 5: Now you can add the devices to the configuration (see below) and restart homebridge”.

The following is the example of how I’ve configured the JSON inside the plug-in after retrieving the credentials. Just a disclosure, the only thing I changed from the example configuration provided to follow was the: IP address for my Dyson Device. The Serial number for my Dyson device and the credentials I redeemed. Everything else was left the same. The configuration looks as follows:

{
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "devices": [
                {
                    "ipAddress": "My Dyson IP Address",
                    "serialNumber": "My Dyson Serial Number",
                    "credentials": "The Credentials I redeemed using step 3",
                    "enableAutoModeWhenActivating": false,
                    "enableOscillationWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false
                }
            ],
            "updateInterval": 60000,
            "credentialsGeneratorPort": 48000
        }
    ]
}

- I have checked and made sure the JSON is valid and it is. No errors. 
I have saved the configuration and restarted/rebooted my Homebridge and the Dyson devices are still not appearing on my homekit. All the IP addresses are static so I know that’s not the problem. I don’t know where the problem is. If anyone knows if I need to remove something off the configuration or modify or add something. If anyone has had the same issue and was able to resolve the problem to get the devices to appear and fully work on your homekit, I would greatly appreciate to see how you were able to achieve it. Sorry for the long thread but I try to be as detailed as possible. Thanks in advance!

**Comment by freemanuk** [comment]
Encountered the same issue. Ran a check on the JSON data to ensure there was no error, but nothing is showing up on my homekit.

**Comment by lukasroegner** [comment]
You can take a look at the logs and check whether the plugin printed out any warnings or errors.

**Comment by freemanuk** [comment]
Indeed the plug-in isn’t showing in the log. I wonder what has gone wrong.

**Comment by WolfgangWagnerDevelopments** [comment]
I had the same issue and added some log infos lines to the code
I had to recognize the credentials i pasted are not valid (any more)
After recreation and a new paste they showed up in homekit (but are not working there including the sensors show nothing)
Seems i need more „juhu debug messages“ ;)

**Comment by lukasroegner** [comment]
I added a clarification on the IP address format in version 2.3.3, thanks!
