### ISSUE TITLE
TP04 showing 3 degrees wrong...

### ISSUE THREAD

**Issue by SpeedingGuy** [lukasroegner/homebridge-dyson-pure-cool#199]
Hi, now that it's summer my TP04 displays 22 degrees in HomeKit and 25 degrees in the dyson app? Started with the last dyson app update (a month ago or so)

**Comment by lukasroegner** [comment]
I haven't experienced something like that. Maybe the plugin could not communicate with your device, so that a cached value has been displayed. Feel free to reopen the issue if it still occurs.
