### ISSUE TITLE
Does TP02 still use MQTT?

### ISSUE THREAD

**Issue by ryanleesmith** [lukasroegner/homebridge-dyson-pure-cool#20]
Sorry for resorting to creating an issue, but I was wondering if you know whether Dyson is still using MQTT for the TP02? I initially tried integrating your plugin with my Homebridge config without success. I have since stripped down the code to bare minimum: I am just simply trying to establish an MQTT connection, and it is reporting "offline".

To be honest, I'm not even really seeing MQTT activity over Wireshark, which makes me wonder if it's just simply a Dyson server-side connection. It's also disconcerting that nmap is reporting port 1883 is closed on my device IP. If you have any thoughts or troubleshooting steps you encountered while building this plugin, it would be greatly appreciated.

**Comment by lukasroegner** [comment]
Hi @ryanleesmith,

I had some issues with the Dyson devices that occurred when I was heavily testing the plugin. It seems that the devices do not like establishing a large amount of MQTT connections in a short period of time. Maybe you should restart them and try again.

I think there are several people that use the plugin with TP02 devices, so I think that the devices in fact use MQTT.
