### ISSUE TITLE
Unable to login to Dyson account

### ISSUE THREAD

**Issue by dennis8989** [lukasroegner/homebridge-dyson-pure-cool#200]
I try to log in dyson account like below code.
dyson_account = DysonAccount("XXX@hotmail.com","123456","US")
logged = dyson_account.login()
if not logged:
    print('Unable to login to Dyson account')
    exit(1)
but it shows unable to login to Dyson account.
Is the account and password the same as APP Dyson link?
or anything wrong?
Thanks

**Comment by lukasroegner** [comment]
The code you present here does not belong to this plugin.
