### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by mpatgojira** [lukasroegner/homebridge-dyson-pure-cool#203]
Any ideas on this one? Email is correct, logged in and out of Dyson app with 2FA, tried with Dyson account logged out... No luck.

![Screen Shot 2021-07-18 at 7 49 37 PM](https://user-images.githubusercontent.com/87622894/126088068-6c922fa8-457e-4c4a-a389-05ecdd51e5d1.png)

![Screen Shot 2021-07-18 at 7 50 01 PM](https://user-images.githubusercontent.com/87622894/126088067-cac341f9-ec81-4800-9a1b-7c7ffaf23c2c.png)

**Comment by igino111** [comment]
Have the same Problem.
I tried already everything 😏

**Comment by tobiasburkart** [comment]
Same issue.

**Comment by raiubreaksthings** [comment]
Also same issue

**Comment by tobiasburkart** [comment]
Log in the Dyson app out and again in.
After this it worked for me.

**Comment by raiubreaksthings** [comment]
Same error.

**Comment by bbashy** [comment]
It's definitely working. If it doesn't, log out/in on the Dyson app then wait a bit and try the credentials generator again.

Tested in Postman... 

![dTGRqUNZQQ0s1VpjgbPOzE1wYMP8oJYWWLsP5dQaHz](https://user-images.githubusercontent.com/1149200/129726521-f1fe871b-b8ef-4f93-ba12-7b5635e0bb81.jpg)
