### ISSUE TITLE
Step 5: Now you can add the devices to the configuration (see below) and restart homebridge.

### ISSUE THREAD

**Issue by cjwalkeruk** [lukasroegner/homebridge-dyson-pure-cool#204]
Dear all,

This Is my first post on the group. I am a complete amateur.

I already have been using Hoobs for some time, and I just recently upgraded to Hoobs 4.

I have a Dyson fan which I am trying to add to Apple Home Kit through Hoobs.

I have managed to follow all the steps exactly, and got all my necessary IP addresses, Serial Numbers, and Credentials, but I am completely lost regarding Step 5.

Where exactly do I need to paste this information into ? (I just took the below example Json from the website. I know my own details have not been entered below, but I have them to hand ready to replace) 

Thank you in advance for any assistance provided.

**Step 5: Now you can add the devices to the configuration (see below) and restart homebridge.

Configuration

{
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "devices": [
                {
                    "ipAddress": "XXX.XXX.XXX.XXX",
                    "serialNumber": "XXX-EU-XXXXXXXX",
                    "credentials": "xxx...xxx",
                    "enableAutoModeWhenActivating": false,
                    "enableOscillationWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false
                }
            ],
            "updateInterval": 60000,
            "credentialsGeneratorPort": 48000
        }
    ]
}**

**Comment by lukasroegner** [comment]
I hope you have already solved it getting used to Homebridge. You don't have to configure it manually in the `config.json` file, you can also use the configuration UI in HOOBS.
