### ISSUE TITLE
Error while receiving 2FA challenge ID. Status Code: 401

### ISSUE THREAD

**Issue by raiubreaksthings** [lukasroegner/homebridge-dyson-pure-cool#205]
Received new fan HP04 and not able to pull the IDs:

I get the error:
Error while receiving 2FA challenge ID. Status Code: 401

**Comment by BeauGiles** [comment]
Same here.

**Comment by freeformz** [comment]
Same

**Comment by custa1200** [comment]
I can confirm this also. Without this the integration is dead :(

**Comment by Fastdesigner** [comment]
Same here, but earlier in the process. Maybe Dyson pulled the trigger?

**Comment by lukasroegner** [comment]
See #166, #196 and #203. Most users got it working with a combination of stopping homebridge, waiting for a while, and sometimes signing out of the mobile apps. The README has already been enhanced to reflect on those hints.

Sadly, there is no "works 100%" way, as there is no official documentation or support from Dyson.
