### ISSUE TITLE
Step 1: 401

### ISSUE THREAD

**Issue by patowod** [lukasroegner/homebridge-dyson-pure-cool#210]
Hi all, 

as the title says I'm getting a 401 at step 1 of credentials generator. A few weeks ago everything worked fine. I also tried the solution logging in the app and signing back out - unfortunately it didn't work. Are there any other tricks to try? 

Thanks in advance 🙏

**Comment by timojs** [comment]
Good morning!
Make sure to disable all VPNs that might be enabled on the devices. For me only logging out and back in into the app did not work. After that I disabled all the VPN connections and could finally retrieve my credentials. Probably some safety measure from dyson.
Hope that helps.

**Comment by patowod** [comment]
Bingo! @timojs Thank you very much for this idea, it worked great once I turned off my mobile VPN. Once I logged in and out again via mobile I could then complete all steps on my desktop machine. What I’m getting at is that it matters if you log in via VPN, even if you don't have it enabled on your machine where you are trying to receive the credentials. Thanks again and have a great day.

**Comment by timojs** [comment]
Glad it worked out for you as well! 😊
