### ISSUE TITLE
Credentials page is blank

### ISSUE THREAD

**Issue by EddiOS42** [lukasroegner/homebridge-dyson-pure-cool#211]
I'm able to enter my password and the 2fa code from email. But after entering, the next page is blank and just says "Credentials."

**Comment by lgomez** [comment]
I followed these steps and still get the 401. Is there a way for me to at least see the logs or, even better, get these credentials manually?

**Comment by lukasroegner** [comment]
If you see an empty credentials page after going through the process, it means that there are no supported devices registered with the Dyson account you have used in the process. The plugin relies on Dyson devices that support `LocalCredentials`, which are the fans and air purifiers they produce.

If you have further issues with getting a blank credentials page, feel free to reopen this issue. Please make sure that you are using the correct account, which actually contains the devices you want the credentials for.
