### ISSUE TITLE
Air Quality recording and Index calculation clarification.

### ISSUE THREAD

**Issue by RaffoNin** [lukasroegner/homebridge-dyson-pure-cool#214]
I've been noticing that the air quality in the dyson app and the home app are different. PM 2.5 ￼and PM 10 have a +-1 difference. And VOC appears to only pop up in the home app if it's above 10 on the dyson app. Lastly, the Index is different from the dyson app. Earlier it was poor according to the Dyson app but only inferior according to the home app. 

I'm just clarifying if this is because the Dyson API doesn't give out actual index data but the app itself interprets it so the plug-in has to make its own formula for determining the index. Also, would like to know if there's a reason for the discrepancy in the measurements. 

![image](https://user-images.githubusercontent.com/85386859/133878879-bec21bb7-2c7f-4a86-b9ae-45daa0fc1cbb.png)
![image](https://user-images.githubusercontent.com/85386859/133878884-60811a99-bde4-48ca-8de9-76d1d1308112.jpeg)

**Comment by RaffoNin** [comment]
Correction the figure reported by the home app for VOC is x10 (6 be 61)

**Comment by lukasroegner** [comment]
Has you have already pointed out, the API of the Dyson devices does not expose the values that are shown in the Dyson app. That is the reason why values may differ between HomeKit and the Dyson app.

If you want to, you can go through the logic that maps the raw values coming from the device to the HomeKit characteristics:

https://github.com/lukasroegner/homebridge-dyson-pure-cool/blob/a435b88c5587568d117973fbc659107b8628f09a/src/dyson-pure-cool-device.js#L463-L475

If you have an idea on how to improve this logic, I would gladly accept a PR with the changes!

**Comment by RaffoNin** [comment]
I'll look into it. I currently already implemented logic with my Node red setup that seems to get similar results with the Dyson app.
