### ISSUE TITLE
[Feature Request] Support for HP07

### ISSUE THREAD

**Issue by BeginnerOfLife** [lukasroegner/homebridge-dyson-pure-cool#215]
Hi, are you looking for someone who can support you with a HP07? Best regards, Christian

**Comment by igino111** [comment]
Hallo Christian 
Yes I am 
Thanks Igor

**Comment by BeginnerOfLife** [comment]
Hallo Igor, what are the steps to support you?

**Comment by kennychenhk** [comment]
I have been using your plugin with my two HP07 and they have been working flawlessly.
The product type is 527E, it is basically an updated version of HP07 (heat+cool).

**Comment by lukasroegner** [comment]
Thanks, I added the HP07 to the list of supported devices in 2.4.0
