### ISSUE TITLE
MQTT Control

### ISSUE THREAD

**Issue by RaffoNin** [lukasroegner/homebridge-dyson-pure-cool#216]
Hi is there a way to control the fan from another MQTT Client? I can see from the logs that it seems to be communicating to my fan via MQTT. 

Reason: Node Red.

**Comment by lukasroegner** [comment]
Yes, this plugin also communicates via MQTT. I'm not going to write complete instructions (you can get all of the required information by taking a look at the source code of this plugin), but here are some things that might be helpful:

- Create a new server configuration in the MQTT node
  - Server: IP address of the device
  - Port: 1833
  - Enable traditional MQTT 3.1 support
  - Use the serial number as user name
  - Use the credentials generator of this plugin to get the credentials string. Afterwards, do a Base64 decode on the credentials string. You will see that the credentials are in fact just a JSON object. The `password` property in the JSON object is the value that you have to use as password when communicating via MQTT
- Use the topic `<PRODUCTTYPE>/<SERIALNUMBER>/status/current` to get the current status of the device, where `<PRODUCTTYPE>` is the numeric type of the product (you can find it in the source code of this plugin), `<SERIALNUMBER>` is the SN of your device
- Use the topic `<PRODUCTTYPE>/<SERIALNUMBER>/command` to change the state of the device
