### ISSUE TITLE
[Feature Request] Support for PH03

### ISSUE THREAD

**Issue by charliebird** [lukasroegner/homebridge-dyson-pure-cool#219]
Dyson have launched a minor update to the Purifier+Humidifier, model number PH03.
I added mine (replacement for PH01) to the plug-in but it doesn't recognise it as a Humidifier, only shows up Purifier settings.
Would you be able to add support for PH03?
Many thanks,

**Comment by acrmedics** [comment]
I would like PH03 supported as well. What do you think your timeline will be? Thank you

**Comment by lukasroegner** [comment]
Please install the latest version (2.3.5) of the plugin. On startup, you will be able to new log entry:

```
Device with serial number XXXXXXX: product type XXX
```

Report the product type, so that I can add it to the list of supported devices. Please also tell me which features are available (heating, humidifier, jet focus).

**Comment by acrmedics** [comment]
Thank you Lukas

Device with serial number K1D-US-PGA1481A: product type 358E

This is the new version of the Humidifier, replacing HP01

Thank you for all your hard work.

Jordan

**Comment by lukasroegner** [comment]
Thanks, I've added "official" support in version 2.4.1.

**Comment by acrmedics** [comment]
Thanks Lukas

Really appreciate everything you’ve done
