### ISSUE TITLE
Tapping the icon in Home App kicks in Manual Mode

### ISSUE THREAD

**Issue by D-a-n-e** [lukasroegner/homebridge-dyson-pure-cool#22]
Hello again! 😄

### My wish:
Opposite to Issue 1 - A simple tap on the icon of the air purifier in the home app should enable the automatic mode.
Is it possible to make this default behavior selectable during the integration? `["defaultAutoEnabled": true]`
Alternatively: Is it possible to save the last value and return to it on reactivation?

### Device:

- Dyson TP02

### Working scenario:
I usually use the TP02 in automatic mode. At night, the night mode is activated via an automation.
In the morning, the night mode is deactivated again via another automation and the TP02 continues to be operated in automatic mode. That works fine.

### Problematic scenario:
Under certain conditions I would like to turn off the TP02 completely overnight. The next morning he should then switch back to automatic mode.
Turning off works. But I can not put the device back in automatic mode again. Even if automatic mode (with oscillation) is preselected in automation, manual mode is actually activated.
And, as mentioned above, I personally would like to start the device off with a simple tap in automatic mode. ☺️

Best regards and thank you for your plugin!
Dane

**Comment by lukasroegner** [comment]
Hi Dane,

Indeed, it is possible to add a setting for the tap action in the Home app to either
* Start auto mode (which the Home app does by default)
* Don't change mode (which is the current behavior of the plugin)

Regarding your problematic scenario:
In you automation to return to automatic mode, do you also activate the device or does the automation just change from manual to automatic?

**Comment by D-a-n-e** [comment]
Hi Lukas,

yes, I activate the device as well. I have attached a screenshot to this.
The setting is as follows: Activate and select the automatic mode.

![activate-purifier](https://user-images.githubusercontent.com/55045838/66599805-64cf9380-eba4-11e9-94e4-b714d4fd383f.jpeg)

![automation-settings](https://user-images.githubusercontent.com/55045838/66518934-95e98e80-eae6-11e9-9618-c014d80db02b.jpeg)

**Comment by lukasroegner** [comment]
Hi @D-a-n-e,

I added the configuration `enableAutoModeWhenActivating`. You can find the latest version on the `development` branch, please try it out.

**Comment by D-a-n-e** [comment]
Hi Lukas,

I just tested the new module.
Of course I also adapted the config.json.

Apparently it does not work yet.
If I turn off the fan by tapping the tile in the Home app and then turn it back on, it will change to manual mode. Even if the automatic mode was active before switching off.

Maybe I solved the problem in the automation.
As I said before: If I only activate and deactivate the night mode via the external tile, there are no problems.
If I turn off the air purifier on the primary tile in addition completely and afterwards to put back in the automatic mode that does not work. It will then be activated in manual mode. (see screenshots above)
But if I switch off only the primary tile and then switch back to the automatic mode, it works. The tile for the night mode is ignored. Something is getting tangled up there. 😄 
The circuits are always performed via automations.

**Comment by lukasroegner** [comment]
Can you please post the detailed log (parameter -D) that is written when you click on the tile in the Home app in order to activate the device?

**Comment by D-a-n-e** [comment]
Hi Lukas,
I am not sure if you mean this log. I queried it by "journalctl -f -u homebridge", as described in the file "/etc/default/homebridge". If not, please give me a short note where I can use the parameter and where I can get the log. ☺️

### Switch to off from auto mode:
```
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.106] HTTP request: /characteristics
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT HAPServer [B8:27:EB:6F:D2:3F] HAP Request: PUT /characteristics
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT Accessory [HomeBridge] Processing characteristic set: [{"aid":19,"iid":10,"value":0}]
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT Accessory [HomeBridge] Setting Characteristic "Active" to value 0
Okt 16 21:18:24 Server-Intern homebridge[2576]: [2019-10-16 21:18:24] [DysonPureCoolPlatform] NN2-EU-MGA1414A - set Active to 0: {"fpwr":"OFF","fmod":"OFF"}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.106] Muting event '19.10' notification for this connection since it originated here.
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.71] Sending HTTP event '19.10' with data: {"characteristics":[{"aid":19,"iid":10,"value":0}]}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.103] Sending HTTP event '19.10' with data: {"characteristics":[{"aid":19,"iid":10,"value":0}]}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.106] HTTP Response is finished
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.106] Sending HTTP event '19.11' with data: {"characteristics":[{"aid":19,"iid":11,"value":0}]}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.71] Sending HTTP event '19.11' with data: {"characteristics":[{"aid":19,"iid":11,"value":0}]}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.103] Sending HTTP event '19.11' with data: {"characteristics":[{"aid":19,"iid":11,"value":0}]}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.106] Sending HTTP event '19.12' with data: {"characteristics":[{"aid":19,"iid":12,"value":0}]}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.71] Sending HTTP event '19.12' with data: {"characteristics":[{"aid":19,"iid":12,"value":0}]}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.103] Sending HTTP event '19.12' with data: {"characteristics":[{"aid":19,"iid":12,"value":0}]}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.106] Sending HTTP event '19.13' with data: {"characteristics":[{"aid":19,"iid":13,"value":0}]}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.71] Sending HTTP event '19.13' with data: {"characteristics":[{"aid":19,"iid":13,"value":0}]}
Okt 16 21:18:24 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:24 GMT EventedHTTPServer [::ffff:10.0.0.103] Sending HTTP event '19.13' with data: {"characteristics":[{"aid":19,"iid":13,"value":0}]}
```


### Switch to on from off by tapping the tile:
```
Okt 16 21:18:43 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:43 GMT EventedHTTPServer [::ffff:10.0.0.106] HTTP request: /characteristics
Okt 16 21:18:43 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:43 GMT HAPServer [B8:27:EB:6F:D2:3F] HAP Request: PUT /characteristics
Okt 16 21:18:43 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:43 GMT Accessory [HomeBridge] Processing characteristic set: [{"aid":19,"iid":10,"value":1}]
Okt 16 21:18:43 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:43 GMT Accessory [HomeBridge] Setting Characteristic "Active" to value 1
Okt 16 21:18:43 Server-Intern homebridge[2576]: [2019-10-16 21:18:43] [DysonPureCoolPlatform] NN2-EU-MGA1414A - set Active to 1: {"fpwr":"ON","fmod":"FAN"}
Okt 16 21:18:43 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:43 GMT EventedHTTPServer [::ffff:10.0.0.106] Muting event '19.10' notification for this connection since it originated here.
Okt 16 21:18:43 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:43 GMT EventedHTTPServer [::ffff:10.0.0.71] Sending HTTP event '19.10' with data: {"characteristics":[{"aid":19,"iid":10,"value":1}]}
Okt 16 21:18:43 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:43 GMT EventedHTTPServer [::ffff:10.0.0.103] Sending HTTP event '19.10' with data: {"characteristics":[{"aid":19,"iid":10,"value":1}]}
Okt 16 21:18:43 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:43 GMT EventedHTTPServer [::ffff:10.0.0.106] HTTP Response is finished
Okt 16 21:18:44 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:44 GMT EventedHTTPServer [::ffff:10.0.0.106] Sending HTTP event '19.11' with data: {"characteristics":[{"aid":19,"iid":11,"value":2}]}
Okt 16 21:18:44 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:44 GMT EventedHTTPServer [::ffff:10.0.0.71] Sending HTTP event '19.11' with data: {"characteristics":[{"aid":19,"iid":11,"value":2}]}
Okt 16 21:18:44 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:18:44 GMT EventedHTTPServer [::ffff:10.0.0.103] Sending HTTP event '19.11' with data: {"characteristics":[{"aid":19,"iid":11,"value":2}]}
```


### Change to auto mode in device settings:
```
Okt 16 21:19:06 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:06 GMT EventedHTTPServer [::ffff:10.0.0.106] HTTP request: /characteristics
Okt 16 21:19:06 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:06 GMT HAPServer [B8:27:EB:6F:D2:3F] HAP Request: PUT /characteristics
Okt 16 21:19:06 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:06 GMT Accessory [HomeBridge] Processing characteristic set: [{"aid":19,"iid":12,"value":1}]
Okt 16 21:19:06 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:06 GMT Accessory [HomeBridge] Setting Characteristic "Target Air Purifier State" to value 1
Okt 16 21:19:06 Server-Intern homebridge[2576]: [2019-10-16 21:19:06] [DysonPureCoolPlatform] NN2-EU-MGA1414A - set TargetAirPurifierState to 1: {"auto":"ON","fmod":"AUTO"}
Okt 16 21:19:06 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:06 GMT EventedHTTPServer [::ffff:10.0.0.106] Muting event '19.12' notification for this connection since it originated here.
Okt 16 21:19:06 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:06 GMT EventedHTTPServer [::ffff:10.0.0.71] Sending HTTP event '19.12' with data: {"characteristics":[{"aid":19,"iid":12,"value":1}]}
Okt 16 21:19:06 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:06 GMT EventedHTTPServer [::ffff:10.0.0.103] Sending HTTP event '19.12' with data: {"characteristics":[{"aid":19,"iid":12,"value":1}]}
Okt 16 21:19:06 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:06 GMT EventedHTTPServer [::ffff:10.0.0.106] HTTP Response is finished
```


### Activate oscillation in device settings:
```
Okt 16 21:19:20 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:20 GMT EventedHTTPServer [::ffff:10.0.0.106] HTTP request: /characteristics
Okt 16 21:19:20 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:20 GMT HAPServer [B8:27:EB:6F:D2:3F] HAP Request: PUT /characteristics
Okt 16 21:19:20 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:20 GMT Accessory [HomeBridge] Processing characteristic set: [{"aid":19,"iid":13,"value":1}]
Okt 16 21:19:20 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:20 GMT Accessory [HomeBridge] Setting Characteristic "Swing Mode" to value 1
Okt 16 21:19:20 Server-Intern homebridge[2576]: [2019-10-16 21:19:20] [DysonPureCoolPlatform] NN2-EU-MGA1414A - set SwingMode to 1: {"oson":"ON"}
Okt 16 21:19:20 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:20 GMT EventedHTTPServer [::ffff:10.0.0.106] Muting event '19.13' notification for this connection since it originated here.
Okt 16 21:19:20 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:20 GMT EventedHTTPServer [::ffff:10.0.0.71] Sending HTTP event '19.13' with data: {"characteristics":[{"aid":19,"iid":13,"value":1}]}
Okt 16 21:19:20 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:20 GMT EventedHTTPServer [::ffff:10.0.0.103] Sending HTTP event '19.13' with data: {"characteristics":[{"aid":19,"iid":13,"value":1}]}
Okt 16 21:19:20 Server-Intern homebridge[2576]: Wed, 16 Oct 2019 19:19:20 GMT EventedHTTPServer [::ffff:10.0.0.106] HTTP Response is finished
```

**Comment by lukasroegner** [comment]
@D-a-n-e do you have a TP02 or a newer device? I think the issue is that the TP02 devices don't have a separate auto mode setting, they have fan settings for OFF/MANUAL/AUTO. I have to change the code so that is also works for those older devices.

**Comment by D-a-n-e** [comment]
Yes, it is a TP02.
Thank you for your help.

**Comment by lukasroegner** [comment]
@D-a-n-e OK, if I change the code, that would mean that if you activate the device via HomeKit (i.e. the `Active` characteristic is set to `On`) either on the tile or in the detailed settings, it will always switch to Auto mode. Is that OK?

**Comment by D-a-n-e** [comment]
That would be great.
Auto mode and oscillation would be perfect. ☺️

**Comment by lukasroegner** [comment]
@D-a-n-e Please try the `development` branch.

**Comment by D-a-n-e** [comment]
Now a simple tap in the home app enable the auto mode. Great!
The oscillation is disabled. Can you activate them as well?

**Comment by lukasroegner** [comment]
Oscillation should persist between all actions, does this not work for you?

**Comment by D-a-n-e** [comment]
No, it does not work.
I have just tried it with the original remote control. Even if I turn off the TP02 and turn it back on the Oszilation remains disabled.

**Comment by lukasroegner** [comment]
Ok, so that is not support by the TP02...I don't like to implement user requests that are not part of the functionality of the original device.

I'll think about it. In the meantime, you can install the plugin from NPM again, I published a new version with the recent changes.

**Comment by D-a-n-e** [comment]
No problem, I can understand that.
Thanks again.

**Comment by lebinho** [comment]
Hi, I'm new to homebridge and just set up my DYSON - i can see it on my APPLE HOME app but nothing works.
When i go to settings it looks like it picksu up the correct data about HEPA % and current humidity but i can't control it at all. 

This is my config in homebridge-so far have nothing else than Dyson:
<pre><code>
{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "033-44-254"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "restart": "sudo -n systemctl restart homebridge",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "platform": "DysonPureCoolPlatform",
            "username": "MYcorrect@MAIL",
            "password": "MYcorrectPASSWORD",
            "countryCode": "PL",
            "devices": [
                {
                    "ipAddress": "192.168.1.23",
                    "serialNumber": "D8N-PL-MDA0501A",
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false
                }
            ]
        }
    ]
}
</code></pre>


I can't diagnose what might be wrong?

I run this if it helps with anything:
<pre><code>
Oct 25 00:24:51 raspberrypi homebridge[291]: [10/25/2019, 12:24:51 AM] [DysonPureCoolPlatform] Signing in.
Oct 25 00:24:51 raspberrypi homebridge[291]: [10/25/2019, 12:24:51 AM] Homebridge is running on port 51826.
Oct 25 00:24:51 raspberrypi homebridge[291]: [10/25/2019, 12:24:51 AM] [DysonPureCoolPlatform] Error while signing in. Error: Error: getaddrinfo EAI_AGAIN api.cp.dyson.com api.cp.dyson.com:443
Oct 25 00:24:58 raspberrypi homebridge[291]: [10/25/2019, 12:24:58 AM] [Config] Homebridge Config UI X v4.6.2 is listening on :: port 8080
Oct 25 18:02:29 raspberrypi homebridge[291]: [10/25/2019, 6:02:29 PM] [Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered.
Oct 25 18:02:29 raspberrypi homebridge[291]: [10/25/2019, 6:02:29 PM] [Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered.
Oct 25 20:53:53 raspberrypi homebridge[291]: [10/25/2019, 8:53:53 PM] [Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered.
Oct 25 20:53:53 raspberrypi homebridge[291]: [10/25/2019, 8:53:53 PM] [Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered.
Oct 26 11:05:03 raspberrypi homebridge[291]: [10/26/2019, 11:05:03 AM] [Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered.
Oct 26 11:05:03 raspberrypi homebridge[291]: [10/26/2019, 11:05:03 AM] [Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered.</code></pre>

**Comment by lukasroegner** [comment]
@lebinho I created a new issue, please don't use existing issues that are not related to your problem.
