### ISSUE TITLE
[Feature Request] Completely disable humidity/air quality sensor

### ISSUE THREAD

**Issue by Stivenskyrah** [lukasroegner/homebridge-dyson-pure-cool#220]
I don’t have the fans set to continuous monitoring and when I ask Siri what my homes humidity it’s reading the old / last pulled data from the Dyson fans. 

Could you look into breaking out the humidity sensor as an option and allowing a prop for “disable humidity sensor” ?

the data I’m getting from it is useless as it is as it’s only correct when the fans are running or in continuous monitoring mode.

**Comment by codyc1515** [comment]
I have a similar request - to be able to disable the NO2 sensor. When I open the door the sensor spikes which affects the air quality measure, even though it is fine.

**Comment by lukasroegner** [comment]
Version 2.6.0 has new options to prevent the plugin from exposing temperature, humidity or air quality.
