### ISSUE TITLE
[Feature request] enable auto mode

### ISSUE THREAD

**Issue by Stivenskyrah** [lukasroegner/homebridge-dyson-pure-cool#221]
When using the Siri command “enable auto mode on {fan name}” is used Siri says “done” but the setting doesn’t change on the Dyson fan.

If possible could it be made so that:
“Turn on auto mode…
“Turn on automatic mode…
“Switch to auto mode…
“Enable auto mode…

For {fan}”

all enable the automatic mode on the devices. Currently it seems to do nothing.

**Comment by lukasroegner** [comment]
Fixed in version 2.5.1
