### ISSUE TITLE
No Credential page 

### ISSUE THREAD

**Issue by pillouz01** [lukasroegner/homebridge-dyson-pure-cool#224]
Hello,
I'm using Hoobs Version: 4.0.71 and trying to configure this plugin 
However, when I try to open the credential page and a black page is displayed

Have tried to change the port, do some restart no luck

Any help to generate the credentials?
Thanks

**Comment by Fofer** [comment]
Having "been there, done that," here's the best advice I can provide: https://github.com/homebridge/homebridge-raspbian-image/wiki/How-to-migrate-from-HOOBS-to-Homebridge

**Comment by hdasmith** [comment]
I'm on Homebridge, and not getting a credentials page either. I have used this in the past successfully, and not had an issue, but just moved house, updated everything, and it's now broken.

**Comment by hdasmith** [comment]
I managed to sort this out, I had to actively select the network interface homebridge uses to advertise on it. Once selecting that, all was fine. Through the web ui, go to the menu, homebridge settings, and it’s the top option.
