### ISSUE TITLE
[Feature Request] Support for TP09

### ISSUE THREAD

**Issue by MillanFung** [lukasroegner/homebridge-dyson-pure-cool#225]
Bought a Dyson TP09 and tested with it (even it's not in the list), found out it work on this plugin as well

Please add TP09 to the Supported Devices, Thank you~

**Comment by marmitol** [comment]
Me too

**Comment by lukasroegner** [comment]
Please install the latest version (2.3.5) of the plugin. On startup, you will be able to see a new log entry:

```
Device with serial number XXXXXXX: product type XXX
```

Report this product type to me, so that I can add it to the list of supported devices. Please also tell me which features are available (heating, humidifier, jet focus).

**Comment by marmitol** [comment]
Hello.
Thank you very much, I have now been able to add my Dyson TP09. Keep in mind that you have to proceed to obtain the Credentials according to the procedure described in https://github.com/lukasroegner/homebridge-dyson-pure-cool.
I found that without this procedure I could not add my second Dyson device.
![image](https://user-images.githubusercontent.com/61157812/154255472-cf5d460f-a20e-46f5-87d8-b655b30102af.png)

**Comment by lukasroegner** [comment]
Thanks for the feedback, I've added TP09 to the list of supported devices.
