### ISSUE TITLE
Credential page fails to open

### ISSUE THREAD

**Issue by sweeting89** [lukasroegner/homebridge-dyson-pure-cool#226]
Ive had issues getting the credentials page to open. I'm on Homebridge raspberry pi, I had issues originally, but managed to get it to work once. then had to reset something and lost credentials. subsequently ive been unable to navigate to the IP address and :48000

the format is as follows:
http://192.168.1.43:48000/
i've also tried https and no / at the end. and tried turning everything off and on again.

im running this on a Mac and have tried chrome, Firefox and safari. any info is appreciated. 

raspberry pi is on ethernet and laptop is on wifi 5ghz network. will directly connecting via ethernet help?

Alex

**Comment by LukasM937** [comment]
how did you fix it ? I have the same issue

**Comment by LukasM937** [comment]
I had the same issue, I resolved it with allowing the credential port in the firewall
