### ISSUE TITLE
Temperature and humidity do not change

### ISSUE THREAD

**Issue by rich-sykes** [lukasroegner/homebridge-dyson-pure-cool#232]
The temperature and humidity in home bridge do not align to the Dyson link app. Once the initial temperature passed to home bridge it never changes even though Dyson link has 10degC/15% shifts.

This is fixed at 20.9degC and 62% humidity.

Dyson fan is Dyson Pure Cool Tower TP07

{
            "devices": [
                {
                    "ipAddress": "192.168.x.xx",
                    "serialNumber": "NN-UK-HFxxxxxx",
                    "credentials": "e",
                    "enableAutoModeWhenActivating": true,
                    "enableOscillationWhenActivating": true,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": true,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false
                }
            ],
            "updateInterval": 60000,
            "credentialsGeneratorPort": 48000,
            "platform": "DysonPureCoolPlatform"
        }

**Comment by lukasroegner** [comment]
Please take a look at the logs in debug mode (start Homebridge with parameter `-D`) to make sure that the temperature/humidity are actually being update. If you only see log entries like `MQTT disconnected/reconnecting` it means that the Homebridge host and the device has communication issues. That would mean that cached values are presented to you. Another thing you can check is whether you enabled "continuous monitoring" for the devices in the Dyson app. Without this setting, the device may not send updated values to the plugin.

**Comment by rich-sykes** [comment]
Fixed by enabling a interface in "Home Bridge" > "Settings" > "Network Interface". I believe this is because my Raspberry Pi is connected via ethernet.

Thanks for the MQTT advice.
