### ISSUE TITLE
Ip Of Homebridge Host

### ISSUE THREAD

**Issue by ningunoi** [lukasroegner/homebridge-dyson-pure-cool#237]
I’m using a NAS docker. Meaning I can’t have double ports here. Example my host is 192.168.1.17, with the port number 32000. To access my home bridge, I’ll need 192.168.1.17:32000. How can I navigate to 48000 in this case then?

Thanks

**Comment by lukasroegner** [comment]
> Meaning I can’t have double ports here

Can you explain that further? With docker, you can just expose multiple ports.

If you don't want to mess with docker, you can also install the plugin on a local machine and run the credentials generator there. After receiving the credentials, you can just copy them into the configuration on your NAS.
