### ISSUE TITLE
Getting credentials - last step blank page

### ISSUE THREAD

**Issue by dersupergrobi** [lukasroegner/homebridge-dyson-pure-cool#242]
same as #193 

hi…
i have the same issue:
last page shows only the hesdline „credentials“ without credentials

i own a DP04
tried 2 different dyson accounts
restartet

any other idea?

danke,
frank

**Comment by lukasroegner** [comment]
If the page for the credentials is empty, it means that no devices are linked to the account.

In order to track down the issue, you can start Homebridge in debug mode (parameter `-D`) and go through the credentials generator again. It will print out the raw response from the Dyson API in the logs. It should look like this:

```json
[
  {
    "LocalCredentials": "...",
    "Serial": "..."
  }
]
```

If you encounter a body that only contains an empty array (`[]`), then the device is not registered with the account you've signed in with.

**Comment by dersupergrobi** [comment]
got it - but the devices are linked.
i also extracted the device DP04 to another account (because in my main account there are more products that are not "smart"
When i open the site source og the Blank page is as follows:

> <html>                     <head>                         <title>Dyson Pure Cool Plugin - Credentials Generator</title>                     </head>                     <body>                     <h1>Error while retrieving token. Status Code: 400</h1>                     </body>                 </html>

**Comment by lukasroegner** [comment]
If you get an HTTP 400 or HTTP 401, stick to the README:

> If you get a 401 or 400 error: Try the following:
> Log out of any mobile apps
> Restart your homebridge server
> Try again

**Comment by dersupergrobi** [comment]
i would not write an issue if i would have a problem that was already solved ;)
the error 400 is only in the HTML source, not as an error message.

i tried Homebridge with your plugin on 2 devices now:
Raspberry Pi3 and Hyper V

both with the same results and the empty page
devices are linked to the account: see above img
i opened this accout as a new account because i read that it worked for some ppl

i reinstalled and restarted severals time, w/ and w/o connected app
(because sometimes (really just sometimes) i have a 401 error when not connected to the app.

i assume there is an issue with dyson?
because netatmo and Tapo are running 

but another hint:
i received the message "too many APi requests" - in this case the solution is to reconnect with another IP (if possible)

**Comment by lukasroegner** [comment]
> both with the same results and the empty page

Have you taken a look at the logs? Do they show an empty array (`[]`) or some data (`[{"LocalCredentials": "...",...}]`) after you completed the steps (and an empty credentials page is shown in the credentials generator)?

**Comment by dersupergrobi** [comment]
chasing the right logs - because i dont find the entries.

tried another plugin - in the hombridge console this says: no products in account - but there are products....maybe there is a dyson error currently?

**Comment by lukasroegner** [comment]
Must be an issue with your account. I also own a DP04, it just works fine.

Here's a screenshot of how the logs look like in debug mode when you use the credentials generator:

<img width="1143" alt="Bildschirmfoto 2022-02-18 um 14 26 51" src="https://user-images.githubusercontent.com/16758848/154692159-650eab06-b2f5-4e36-9365-211e20a616ab.png">

**Comment by lukasroegner** [comment]
As it turned out to be an issue with the account, I'm closing the issue for now. If checking the logs reveal an issue with the plugin, feel free to reopen the issue!

**Comment by dersupergrobi** [comment]
just to resume my information: no entry for the request in Debug Mode....

![Homebridge_B8EB](https://user-images.githubusercontent.com/16088406/154912862-8e524b7f-3f4a-4a3f-93ee-6f05a48b27d2.jpg)

**Comment by lukasroegner** [comment]
Have you started Homebridge in debug mode?

**Comment by dersupergrobi** [comment]
yes - as requested...tried it several times - with reboots
