### ISSUE TITLE
[Feature request] Support Backward airflow mode in HP07/04/06/09

### ISSUE THREAD

**Issue by kennychenhk** [lukasroegner/homebridge-dyson-pure-cool#248]
HP07, similar to HP04/06/09, has a backward airflow mode in which the air is blowing toward the back rather than the front. Is it possible to have it supported as well.
Thank you very much

**Comment by lukasroegner** [comment]
Have you enabled the setting `isJetFocusEnabled`?

**Comment by kennychenhk** [comment]
sorry my bad, i didn't know Jetfocus is for controlling the air flow direction
It is now resolved. Thank you
