### ISSUE TITLE
I'm able to generate the credential using the tool; however im not able to save the configuration 

### ISSUE THREAD

**Issue by rtp8725** [lukasroegner/homebridge-dyson-pure-cool#251]
Has anyone else encountered this error? Thankfully I didn't have issues with error 400 or 401?[](url
![Screenshot 2022-03-10 100704](https://user-images.githubusercontent.com/99909570/157690961-c7b20a2e-6c28-4882-a9f1-0d204a77437f.png)
)

**Comment by lukasroegner** [comment]
It seems to be an issue with the Homebridge config UI rather than the plugin.
There is an issue you can take a look at: https://github.com/oznu/homebridge-config-ui-x/issues/841

**Comment by rtp8725** [comment]
Thanks for your response. That did the trick, I had to do sudo install from the beginning for homebridge. Many thanks
