### ISSUE TITLE
Credentials server does not close when successfully connected to the Dyson

### ISSUE THREAD

**Issue by codyc1515** [lukasroegner/homebridge-dyson-pure-cool#265]
This widens the attack surface for the Homebridge environment and is unnecessary. Once connected to the Dyson successfully or once credentials are input into the config, then the credentials server should shut down.

**Comment by codyc1515** [comment]
Any interest to resolve this?

**Comment by lukasroegner** [comment]
Feel free to submit a PR, I'm always open to contributions!
