### ISSUE TITLE
Add oscillate button to accessory

### ISSUE THREAD

**Issue by ifeign** [lukasroegner/homebridge-dyson-pure-cool#27]
Hi, love this new plugin, having moved over from https://github.com/joe-ng/homebridge-dyson-link plugin I find it's missing one minor detail. In Joe-ng's plugin a little oscillation button appears below the other switches, rather than having to scroll into the settings. Is there a way to implement this?

**Comment by lukasroegner** [comment]
Hi @ifeign, Can you provide a screenshot of how the oscillation button shows up in the other plugin?

**Comment by ifeign** [comment]
<img width="204" alt="Screen Shot 2019-11-20 at 1 35 04 AM" src="https://user-images.githubusercontent.com/32289760/69227024-0350fc00-0b36-11ea-94df-d3011fe1bd4a.png">
The icon on the bottom has since changed (this is an old screenshot from the early betas), it's now a circle with <>. I can reinstall the old plugin if you need to see exactly, but this is essentially how it looks.

**Comment by lukasroegner** [comment]
Ok, so the icon is in the top part of the accessory. I'm sorry, this cannot be changed by the developer. The Home app decides how accessories are displayed. I assume that the oscillation button does not show up in my plugin as they are exposed as air purifiers, where it is more important to toggle the On/Off button.

However, I also recognised that the layout has changed in one of the iOS 13 updates. The On/Off button is now a switch...may be a bug in the Home app as it does not match the available with of the top area.

**Comment by ifeign** [comment]
Would it be possible to have provide an option to expose this as a fan? That is probably the only accessory that supports the oscillate button.

**Comment by lukasroegner** [comment]
It would mess up the source code of the plugin if I had to dynamically switch the accessory type based on the configuration, that's why I decided to not provide such an option in the first place.

Why don't you use the plugin of Joe-ng? It exposes all devices as fans.

**Comment by ifeign** [comment]
Your plugin seems more stable. Thanks for the quick response.

**Comment by lukasroegner** [comment]
You could easily fork this plugin and change the accessory type. 

Maybe developers are allowed to set the layout manually in an update of iOS..I hope so!

**Comment by ifeign** [comment]
I hope they make things more customizable for developers. If they’re trying
to squeeze all these options into one accessory tile then it should be more
flexible.
