### ISSUE TITLE
Unable to turn on when air quality is bellow a level

### ISSUE THREAD

**Issue by nac6** [lukasroegner/homebridge-dyson-pure-cool#276]
I have managed to install and configure the plugin. Looks ok and can manually control the Dyson.
But when trying to create an automation based on air quality for example, the accessories to automate does not list the Dyson as on option to turn on.

**Comment by johnypony3** [comment]
hi there, please see the link attached. i use my garage as a woodshop and use the dyson to kick off bigger filters. the system is flawless, the automation could be refactored for efficiency.

https://gist.github.com/johnypony3/b9c8cf663e4e206132ca9d631ad00782

**Comment by johnypony3** [comment]
@lukasroegner would you mind closing this issue if you don't need assistance
