### ISSUE TITLE
error code 503 while signing in

### ISSUE THREAD

**Issue by CooperCGN** [lukasroegner/homebridge-dyson-pure-cool#29]
Just updated to the latest version and now get the following error
[DysonPureCoolPlatform] Error while signing in. Status Code: 503

Any idea? Which version number had the version before, want to try a rollback and see if it still happens.

**Comment by CooperCGN** [comment]
It seems it is the Dyson servers, logged out of the app and tried logging in again and get an error that the Dyson network is not available.

**Comment by lukasroegner** [comment]
@CooperCGN Seems that the Dyson server is currently not available or under heavy load (503 status code). Let's try it again tomorrow and see if the issue persists.

**Comment by CooperCGN** [comment]
it is working again.

**Comment by CooperCGN** [comment]
Question though: is It necessary that the plugin contacts the server after a bridge restart? or could it actually check for a changed config and then decide whether it needs new information from the server?

**Comment by lukasroegner** [comment]
@CooperCGN It is possible, however, requires massive changes to the plugin. Maybe in the future!
