### ISSUE TITLE
Enhancement: Add Sleep Timer functionality

### ISSUE THREAD

**Issue by CooperCGN** [lukasroegner/homebridge-dyson-pure-cool#3]
In the MQTT message block there is a sltm statement describing the sleep timer. Any chance to get a slider like control in the eve or home 3 app to set this. I think it ranges from off to 540 minutes (9 hours), 15 minute intervals would be perfect.

**Comment by lukasroegner** [comment]
Sadly, there is no such thing as a generic slider service in HomeKit. It could be implemented with a dimmable light service, but that would just look ugly.

You could use Home automations to disable the Dyson after a specific time (e.g. I have a Dyson in the bedroom with an automation that stops it at 3am).
