### ISSUE TITLE
Dyson Pure Cool+Hot Link not supported

### ISSUE THREAD

**Issue by mmax-nl** [lukasroegner/homebridge-dyson-pure-cool#30]
[11/29/2019, 11:18:16 PM] [DysonPlatform] Device with serial number PT4-EU-KAA1163A not added, as it is not supported by this plugin. Product type: 455
[11/29/2019, 11:18:17 PM] [DysonPlatform] Got devices from the Dyson API.

**Comment by lukasroegner** [comment]
HI @mmax-nl, this is correct, the Hot+Cool is not (and won't be) supported by this plugin. Take a look at https://github.com/joe-ng/homebridge-dyson-link, which supports the Hot+Cool devices.

**Comment by KaidenR** [comment]
I got everything installed and running just to find that my hot+cool fan isn't supported. Why not? Your plugin seems to be more full-featured than the `dyson-link` one you linked to. Kudos on building this out btw.

**Comment by lukasroegner** [comment]
@KaidenR The main reason why the hot+cool devices are not supported is that this plugin exposes the Dyson devices as air purifiers. A hot+cool device should be of type Heating-Cooling. This means, the source code has to be massively restructured. It is also quite challenging to integrate a completely different device without having physical access to it. Somebody with a hot+cool has to provide me with log files after each stage of development.

Maybe, if I find time to work on it, I can implement it. Could I contact you to work on the log files with me?

**Comment by mmax-nl** [comment]
I would gladly help as well with the logs. Just tell me what To do and how to do it 

Inviato da iPhone
