### ISSUE TITLE
Dyson Purifier Big + Quiet Formaldehyde BP04 Support

### ISSUE THREAD

**Issue by DisneyFanatic4** [lukasroegner/homebridge-dyson-pure-cool#321]
Would it be possible to add support for the Dyson Purifier Big + Quiet Formaldehyde BP04?

**Comment by kjohn** [comment]
I would like this support also. The BP02, BP03, BP04, and BP06 is Product Type 664. Thanks for all your hard work!

**Comment by lukasroegner** [comment]
Support added in version 2.7.7. Feel free to create a PR if you want specific features to be integrated.
