### ISSUE TITLE
Request: Expose Temperature and Humidity as sensors

### ISSUE THREAD

**Issue by ZitherGH** [lukasroegner/homebridge-dyson-pure-cool#37]
Hi

I have the TP04 and just installed your plug-in.  Thanks for making this great plug-in.  Is it possible to expose the humidity and temperature as sensors in Homekit so we can create automations based off it?

Chun

**Comment by lukasroegner** [comment]
Hi @ZitherGH,

Both "sensors" are exposed in HomeKit. Either as separate accessories or as characteristics of the air purifier (depends on your configuration). Either way you will see temperature and humidity as sensor in the automations.

**Comment by ZitherGH** [comment]
Thanks for the quick response.  But I don't see it.  I have everything set to true:

            "devices": [
                {
...
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": true,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true
                }

I only see (attached).
![MyHomeSensors](https://user-images.githubusercontent.com/857629/72898561-5118f900-3d5f-11ea-859d-980b2544cfb2.png)
![Myhome1](https://user-images.githubusercontent.com/857629/72898562-5118f900-3d5f-11ea-9b57-216ed3eda089.png)

**Comment by lukasroegner** [comment]
I think that humidity and temperature cannot be used with the sensor automation, can you try to use the "if a value changed" automation type?

**Comment by ZitherGH** [comment]
Unfortunately, it only seems to give me option to check if on/off or the air quality.

![IMG_0065](https://user-images.githubusercontent.com/857629/72899583-45c6cd00-3d61-11ea-801e-0795cc42efad.png)

**Comment by lukasroegner** [comment]
Create an automation in the Home app (e.g. use the sensor automation) and save it. Open the automation with a third-party HomeKit app (Controller for HomeKit is free and excellent for automations). There you can add a new start condition for temperature/humidity values. Remove the old start condition and you are done.

**Comment by ZitherGH** [comment]
Interestingly, the Eve app exposes the sensors and I was able to create an automation off it similar to the Home app you recommended.

Thanks!

**Comment by lukasroegner** [comment]
I don't know why Apple implemented the sensor selection this way. I would always recommend to use third-party HomeKit apps to create automations as you have even more options.
