### ISSUE TITLE
Not about to Sign In.

### ISSUE THREAD

**Issue by donavanbecker** [lukasroegner/homebridge-dyson-pure-cool#44]
# Log

```[2/3/2020, 12:27:30 PM] [DysonPureCoolPlatform] Signing in.
[2/3/2020, 12:27:30 PM] Homebridge is running on port 51910.
[2/3/2020, 12:27:31 PM] [DysonPureCoolPlatform] Error while signing in. Status Code: 404
```

# Config is

```
{
            "username": "**********",
            "password": "*********",
            "countryCode": "US",
            "devices": [
                {
                    "ipAddress": "**********",
                    "serialNumber": "**********",
                    "enableAutoModeWhenActivating": true,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": true,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true
                }
            ],
            "platform": "DysonPureCoolPlatform"
        }
```

**Comment by donavanbecker** [comment]
I can log into the Dyson app just fine

**Comment by Krocko** [comment]
Could be a Dyson problem. I also can‘t login on Home Assistant.

**Comment by antiabed** [comment]
I've been having this same problem since a few hours (before and after updating the homebridge-dyson-pure-cool plug-in to the latest version).

**Comment by lukasroegner** [comment]
Seems to be an issue with the Dyson server...or maybe, they killed the v1 version of the API. Let‘s check tomorrow if it works again.

**Comment by ryanleesmith** [comment]
I reached out to Dyson directly - but it may be up to 72 hours before a response, as they had to forward it to "IT Department". Hopefully they didn't just kill it - to be honest, I've never seen documentation on the API, so I'm not sure how folks figured it out in the first place.

**Comment by Krocko** [comment]
@lukasroegner  Dyson changed something. 
Here is a working solution:
https://github.com/etheralm/libpurecool/pull/9

**Comment by lukasroegner** [comment]
Thanks @Krocko, can you test the latest version 1.5.2?

**Comment by Krocko** [comment]
Sorry, I can not. No homebridge installed anymore.
I changed to Home Assistant.

**Comment by antiabed** [comment]
This update fixed the problem for me! Awesome, thanks for the quick fix

**Comment by donavanbecker** [comment]
Same here

**Comment by lukasroegner** [comment]
Thank you all for the quick reply!
