### ISSUE TITLE
HP04 : air quality

### ISSUE THREAD

**Issue by philippe317** [lukasroegner/homebridge-dyson-pure-cool#45]
The "Air quality" indicator is incorrect.
It would appear that he is referring to the air quality in the city (and not in the room).
![IMG_5272](https://user-images.githubusercontent.com/18035521/74084888-f0ceca80-4a73-11ea-8d6b-8f40cee2c0da.PNG)
![IMG_5271](https://user-images.githubusercontent.com/18035521/74084890-f3312480-4a73-11ea-98a1-57a12b5070e2.PNG)
![01 homebridge](https://user-images.githubusercontent.com/18035521/74084869-c11fc280-4a73-11ea-94e7-1b21c584c5c4.jpg)

**Comment by lukasroegner** [comment]
Hi @philippe317,

Thanks for reporting. Originally, I thought that the NO2-density is not included in the overall air quality calculation by the Dyson app, see https://github.com/lukasroegner/homebridge-dyson-pure-cool/blob/94ef6b6425a56e7b0cac7adf81f8eba8404b9a8c/src/dyson-pure-cool-device.js#L367

Can you please make some measurements for the next few days with:
NO2 (from HomeKit) => Air quality (in Dyson app)

Example for the values you provided:
80 => Medium

If we gather some data, we can approximate the function that Dyson uses to map NO2 to air quality. Thank you!

**Comment by philippe317** [comment]
![35E5AD5D-FB37-42C0-8B62-CB87CAE859E8](https://user-images.githubusercontent.com/18035521/74102426-b46a9f80-4b43-11ea-8293-edcf555a2c9c.png)
![11543128-869F-4178-85D4-A24D0C45625A](https://user-images.githubusercontent.com/18035521/74102429-b7fe2680-4b43-11ea-9f39-784eb035aa6c.png)
![91307D4F-338B-489D-9604-491742AC3C6D](https://user-images.githubusercontent.com/18035521/74102432-b9c7ea00-4b43-11ea-8e08-ae3fc3f15404.png)
![97047FA9-32A0-4872-B327-5C92A8DB22EE](https://user-images.githubusercontent.com/18035521/74102433-ba608080-4b43-11ea-8379-3c603ecc3269.png)
![96E7CE8C-F8D9-45A7-909E-C25525CA9DAA](https://user-images.githubusercontent.com/18035521/74102434-bb91ad80-4b43-11ea-82a3-7a054f1a61a8.png)
![33676201-A111-4CAD-8C80-71E1A2960954](https://user-images.githubusercontent.com/18035521/74102435-bc2a4400-4b43-11ea-9b49-5e7139a2ff4d.png)
![F2C52CEC-D9B3-419E-A47D-B1B50E021C01](https://user-images.githubusercontent.com/18035521/74102436-bd5b7100-4b43-11ea-8dfb-61300aba27db.png)
![E1164D94-F553-4B2C-B70D-771C469F2CFB](https://user-images.githubusercontent.com/18035521/74102437-bdf40780-4b43-11ea-8682-435349388f30.png)

**Comment by philippe317** [comment]
With an another plugins
https://github.com/joe-ng/homebridge-dyson-link#readme
the "Air quality" indicator is correct in homekit.

**Comment by lukasroegner** [comment]
Added the NO2 density to the calculation of the air quality. New version on master branch and NPM.
