### ISSUE TITLE
No IP address provided for device with serial

### ISSUE THREAD

**Issue by marmitol** [lukasroegner/homebridge-dyson-pure-cool#48]
Please i need Help.

I've installed and I can't see the devices in homebrige.
The following messages appear in the log

[2/17/2020, 4:40:20 PM] [DysonPureCoolPlatform] Signed in.
[2/17/2020, 4:40:23 PM] [DysonPureCoolPlatform] No IP address provided for device with serial number VS8-EU-KGA1234A.
[2/17/2020, 4:40:24 PM] [DysonPureCoolPlatform] Got devices from the Dyson API.

******************************************************************************************************
        {
            "platform": "DysonPureCoolPlatform",
            "username": "username",
            "password": "password@",
            "countryCode": "ES",
            "devices": [
                {
                    "ipAddress": "192.168.0.10",
                    "serialNumber": "V58-EU-KGA1234A",
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false
                },
***************************************************************************************************

Thank.

**Comment by lukasroegner** [comment]
Your serial number in the config.json is invalid, it should be `VS8`, not `V58`.
