### ISSUE TITLE
Retry initial sign-in.

### ISSUE THREAD

**Issue by Suges** [lukasroegner/homebridge-dyson-pure-cool#50]
Hi there,

Thanks for making this plugin!

Could you add a feature to retry signing-in every, say, 15 seconds if not successful initially? Up to some sort of sensible maximum, of course.

I get:

`[DysonPureCoolPlatform] Error while signing in. Error: Error: getaddrinfo EAI_AGAIN appapi.cp.dyson.com`

...every time I sign in (same with some other plugins, but the other ones _do_ sign-in after a couple of tries).

**Comment by lukasroegner** [comment]
Hi @Suges,

I can implement some kind of retry mechanism, however, it does not have the highest priority on my list.

**Comment by Suges** [comment]
I understand! Thanks very much for considering it.

**Comment by lukasroegner** [comment]
Retry is added in the latest version. The plugin continuously retries to communicate with the API until it succeeds.

**Comment by Suges** [comment]
Thank you so much!

**Comment by lukasroegner** [comment]
@Suges Please note that some user had issues with the retry mechanism. In the new version 1.5.8, the retry is disabled by default and can be configured in the config.json.

**Comment by Suges** [comment]
Noted! Thank you.
