### ISSUE TITLE
Support for new Dyson Pure Humidify+Cool possible?

### ISSUE THREAD

**Issue by CooperCGN** [lukasroegner/homebridge-dyson-pure-cool#51]
Hello Lukas,

I just saw this new product on the Dyson Homepage and was wondering if support by your plugin would be possible.

https://shop.dyson.de/dyson-pure-humidify-cool-white-silver-275413-01

I am not yet sure if I am going to get one but ask in general if the humidifier component can somehow be added.

**Comment by lukasroegner** [comment]
Hi! Could be possibly added if the device has the same MQTT API as the other devices. However, someone with such a device would have to help with development and debugging.

**Comment by CooperCGN** [comment]
I assume it’s the same API as it uses the Dyson link app additionally to the IR remote.

If I get one I could maybe help, don’t know what the prerequisites are though.

**Comment by lukasroegner** [comment]
Feel free to reopen if you purchase one and want to help!
