### ISSUE TITLE
Is the air quality data available on HP02?

### ISSUE THREAD

**Issue by jounih** [lukasroegner/homebridge-dyson-pure-cool#52]
In the docs it says - "Air quality (incl. PM2.5, PM10, VOC and NO2 data for 2018 devices)" - does that mean PM2.5, PM10, VOC and NO2 data are only available on HP04, and not the HP02?

**Comment by lukasroegner** [comment]
Correct. The DP04, TP04 and HP04 expose additional data (PM2.5, PM10, VOC, NO2) via the API, the HP02 only exposes a generic "air quality" indicator ("good", "moderate",...)
