### ISSUE TITLE
Info does not update unless Dyson Link app is opened

### ISSUE THREAD

**Issue by antiabed** [lukasroegner/homebridge-dyson-pure-cool#53]
The temperature, humidity, and air quality numbers don’t update unless I open the Dyson link app. I tried with the app open in the background and background refresh on but it doesn’t make a difference. This has been going ons for about one or two weeks. It might be a change on Dyson’s side? But I hope it can be fixed.

**Comment by lukasroegner** [comment]
Do you have the option for continuous sensor data enabled? It is required for the plugin to get data even if the device is off.

**Comment by antiabed** [comment]
I have ‘Continuous Monitoring’ on in the Dyson app, if that’s what you mean?

**Comment by lukasroegner** [comment]
Yea, OK, so that's not the issue. I would suggest to start homebridge in debug mode and check whether the MQTT connection is stable. You can do that by adding the parameter `-D`.

**Comment by antiabed** [comment]
I tried that it seems to work fine:

`[3/15/2020, 2:15:54 PM] [Dyson] xxx-xx-xxxxxxxx - MQTT connection requested for 192.168.xxx.xx.
[3/15/2020, 2:15:54 PM] [Dyson] Got devices from the Dyson API.
[3/15/2020, 2:15:54 PM] [Dyson] xxx-xx-xxxxxxxx - MQTT connection established.
[3/15/2020, 2:15:54 PM] [Dyson] xxx-xx-xxxxxxxx - MQTT message received: {"msg":"CURRENT-STATE","time":"2020-03-15T13:15:53.000Z","mode-reason":"NONE","state-reason":"MODE","rssi":"-57","channel":"100","fqhp":"95672","fghp":"0","product-state":{"fpwr":"ON","auto":"ON","oscs":"IDLE","oson":"ON","nmod":"OFF","rhtm":"ON","fnst":"OFF","ercd":"11E1","wacd":"NONE","nmdv":"0004","fnsp":"AUTO","bril":"0002","corf":"ON","cflr":"0089","hflr":"0089","cflt":"CARF","hflt":"GHEP","sltm":"OFF","osal":"0005","osau":"0355","ancp":"CUST","fdir":"OFF"},"scheduler":{"srsc":"000000005e695cdd","dstv":"0001","tzid":"0001"}}
[3/15/2020, 2:15:54 PM] [Dyson] xxx-xx-xxxxxxxx - MQTT message received: {"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","time":"2020-03-15T13:15:53.000Z","data":{"tact":"2948","hact":"0055","pm25":"0006","pm10":"0006","va10":"0004","noxl":"0005","p25r":"0007","p10r":"0010","sltm":"OFF"}}`

**Comment by lukasroegner** [comment]
That looks good! You can leave the terminal open, the logs with `ENVIRONMENTAL-CURRENT-SENSOR-DATA` should arrive from time to time. You can e.g. check the `hact` value (humidity), it should update in the Home App as soon as you can see a change in the logs.

**Comment by antiabed** [comment]
I left it open for a while but it doesn’t update unless I open the Dyson app. Nu communications from the Dyson plug-in at all. Other homebridge plug-ins do update.

I tried turning off the fan and leaving it a while before turning it back on, and also turning off the ‘Continuous Monitoring’ switch and turning it back on after restarting the app. Both make no difference. The Dyson app does show a history for all the sensors unless I Turn the feature off, so continuous monitoring does works in the Dyson app itself.

**Comment by lukasroegner** [comment]
Ok, so the logs don‘t show any new MQTT messages until you open the Dyson App?

**Comment by antiabed** [comment]
Yeah that’s right. I can’t figure it out either. I do have pi-hole running on the same raspberry as homebridge, blocking DNS requests for ads and trackers. But it doesn’t seem to block anything related and turning it off doesn’t seem to make a difference.

**Comment by lukasroegner** [comment]
I did some tests and it seems that Dyson changed the way the MQTT subscription works. Changes are only reported if they are actively requested. I'll add a timer that requests changes at a certain interval.

**Comment by lukasroegner** [comment]
Update is on master and new version on NPM.

**Comment by antiabed** [comment]
Awesome! Thank you!

**Comment by antiabed** [comment]
It works for me, updating every minute. Maybe it’s an idea to also have it update when the home app is opened? Some other homebridge plugins do this.

**Comment by lukasroegner** [comment]
I won't implement updating when HomeKit is opened as the whole plugin is designed to immediately return "cached" values. I would have to rewrite parts of the plugin to get this to work. Another option might be to reduce the update interval...do you think that 1 minute is too much?

**Comment by antiabed** [comment]
I would like the data I see in the home app reflect the current status, but I understand you don’t want to rewrite a huge part of the code. I also have some automations set up, and I can imagine other people have done that too, so maybe updating every 30 seconds would help with those.

**Comment by lukasroegner** [comment]
Update interval is now configurable via config.json.
