### ISSUE TITLE
API could not be reached

### ISSUE THREAD

**Issue by twynne** [lukasroegner/homebridge-dyson-pure-cool#56]
Hi there

Thought I'd try this plugin rather than homebridge-dyson-link as this one is verified and I hoped less verbose than the other in logs.  I've configured using same details as the other plugin (via config-ui), but when I start homebridge I'm getting 'API could not be reached.  Trying again soon' repeated in logs.  I've tried using country code of GB and UK (for United Kingdom) - made no difference.

What am I doing wrong?  Or is there an outage at present with the API?  The machine is an HP02 if that matters.

Config:

`        {
            "platform": "DysonPureCoolPlatform",
            "username": "my email address",
            "password": "my password",
            "countryCode": "UK",
            "devices": [
                {
                    "ipAddress": "192.168.1.9",
                    "serialNumber": "my serial",
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": true,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true
                }
            ]
        }`

**Comment by twynne** [comment]
status code 429 by the way

**Comment by lukasroegner** [comment]
The API might have had a downtime. I've checked it, now it should work. Country code is `GB`.

**Comment by twynne** [comment]
Thank you... Still showing the same error connecting. Anything I should check?

**Comment by twynne** [comment]
Error while signing in. Status code: 429
