### ISSUE TITLE
Still getting status code 429

### ISSUE THREAD

**Issue by twynne** [lukasroegner/homebridge-dyson-pure-cool#57]
As per my earlier issue... I'm afraid nothing has changed.  Is the service available?

**Comment by lukasroegner** [comment]
```
[12.4.2020, 10:07:13] [DysonPureCoolPlatform] Signing in.
[12.4.2020, 10:07:15] [DysonPureCoolPlatform] Signed in.
[12.4.2020, 10:07:16] [DysonPureCoolPlatform] Got devices from the Dyson API.
```

This is what I get when starting the plugin. Make sure that
- Your country code is GB
- Your email address and the password are the same ones that you use with your Dyson account in the Dyson app

**Comment by twynne** [comment]
Checked and double checked. Even logged out of the app and back in using same details, and into the Dyson website using the same.

**Comment by lukasroegner** [comment]
Have you stopped the plugin in the meantime? Making numerous requests (successful or not) to the API can result in a temporary blocking of requests.

If you are sure that your credentials are correct, stop the plugin, wait for some hours, and spin it up again.

**Comment by twynne** [comment]
I've removed it for now, as that's the only way I know to 'stop' it trying.  Will re-add later and report back.

**Comment by twynne** [comment]
Now seeing this... the IP address (local) is specified in the config and is correct.

[4/12/2020, 11:41:57 AM] [DysonPureCoolPlatform] Signed in.
[4/12/2020, 11:41:57 AM] [DysonPureCoolPlatform] No IP address provided for device with serial number PE9-UK-JAA0461A.
[4/12/2020, 11:41:57 AM] [DysonPureCoolPlatform] Got devices from the Dyson API.

Not seeing any new devices appearing in Home, so I assume still not working?

**Comment by lukasroegner** [comment]
Check your config if the `serialNumber` value in the config exactly matches the one that is printed out in the logs, i.e. no spaces, all caps, etc. Ideally, copy the serial number from the logs and paste it into your config.

**Comment by twynne** [comment]
Sorry, but not sure where you're suggested the serial would be appearing in the logs (assuming you mean the homebridge logs), as your plugin isn't finding the device.

As it happens, I still have the original Dyson platform plugin.  I've been taking the serial number from its config, but noting that it includes the prefix "DYSON-" which does not appear in the Dyson website for my device, nor in the iOS application.  Nonetheless, the Dyson platform plugin is working.

If I put the DYSON prefix on the serial in your plugin's config, I get the sign in error.  If I remove it, I get the output shown above from today (which appears to sign in, but then no device is found/added).

**Comment by lukasroegner** [comment]
> Sorry, but not sure where you're suggested the serial would be appearing in the logs (assuming you mean the homebridge logs), as your plugin isn't finding the device.

You posted it already, the serial for the config should be `PE9-UK-JXXXXXA`

**Comment by twynne** [comment]
Think I might see the problem... for whatever reason the Dyson platform plugin appears to use a different format for the serial number (oddly the serial it reflects is not one I've ever entered, thus no idea how/why it's working).  I think the issue is an additional *suffix* of -455.  I've now removed that, but it appears the API is blocking me so I'll have to wait a few hours to try again.

**Comment by twynne** [comment]
I should add that part of the challenge here has been the error message which alway seems to imply a sign in error, despite knowing that the sign in details were correct.  If it was the serial it didn't like, a message like 'serial number not found' or 'serial number invalid' might have pointed in the right direction.

Also if the server begins blocking after x invalid logins, the plugin should really prevent repeated sign ins within that period of time.  Instead it appears to retry logging in every few seconds, likely contributing to further blocking.

**Comment by twynne** [comment]
Update - that appears to have been the issue.  No idea why the other Dyson plugin was showing an odd (altered) serial number, but copying/pasting (trusting) that was the issue.  Will disable to the other and work with this for a while.

Thanks for the help.

**Comment by twynne** [comment]
Spoke too soon... disabled the old plugin, restarted, I'm again locked out.  Are you hosting the server here, and is there any way to work around this without (again) disabling your plugin and waiting several hours?

**Comment by lukasroegner** [comment]
This is not my server, it is the Dyson server that it also used by the App. I assume that you are again locked out as you tried it too often today. My homebridge instance with this plugin is restarted once every day, I didn't had any issues. Also, when working on the plugin, I restart the plugin several times a day with no issues. I really think that your "counter" is currently too high, wait something like a day before restarting several times.

P.S. retry has been implemented as requested in #50

**Comment by twynne** [comment]
Ah ok... must have misread one of your earlier posts. Strange that the other plugin (Dyson platform) doesn’t cause any such issue with restarts... maybe it’s connecting in some other way?

**Comment by esummers** [comment]
I had the same issue.  It was due to a refurbished unit in my case.  The serial number and hostname of the device ends in a "B".  However the API expects it to end in an "A".  Just swapping the last letter of the serial from B to A worked for me.

**Comment by ijm51000** [comment]
- I had/have the same problem the plugin just kept retrying to log in every 5 seconds. 

- Installed version 1.5.7 of the plugin and it just refused to work, just looped attempting to login every 5 seconds. 
 
- Downgraded to version 1.5.6 of the plugin and everything worked.
 
- Upgrade the plugin via the Homebridge Config UI X but had the same issue with the log in retrying every 5 seconds.  

- Downgraded again to version 1.5.6 of the plugin and it is now all working.  

- I don't see this being a problem with the Dyson API as I could log in with the Dyson supplied app and I could also log in to the website with the same credentials at the same time as the plugin was cycling the log in message every 5 seconds.


Downgrade:
`sudo npm install -g homebridge-dyson-pure-cool@1.5.6`

Start the homebridge app in insecure mode
`pm2 start homebridge -- -I`

Then configure via the plugin settings via the Homebridge Config UI X plugin

JSON config for the plugin, this is the same for both 1.5.6 & 1.5.7

```
        {
            "username": "name@name.com",
            "password": "**************",
            "countryCode": "GB",
            "devices": [
                {
                    "ipAddress": "xxx.xxx.xxx.xxx",
                    "serialNumber": "Z**-UK-*******A",
                    "enableAutoModeWhenActivating": true,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": true,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true
                }
            ],
            "platform": "DysonPureCoolPlatform"
        }
```

Not sure if that helps?

**Comment by lukasroegner** [comment]
I see that there is an issue with the retry feature if you are setting up the plugin and want to play around with the correct settings. That's why I published a new version of the plugin, the sign-in retry is now disabled by default. You can enable it in the config now. I hope that this helps you guys with finding the correct settings to get everything up and running.

**Comment by ijm51000** [comment]
Good stuff I have now upgraded to 1.5.8 and can confirm it all seems to be working well, thank you for such a quick response.

**Comment by twynne** [comment]
Maybe add an option for the retry, whether it’s enabled and how frequently to retry. I had to restart server earlier today - the only time today- and it immediately locked me out, but then on the 10th or so try it worked. 

Will upgrade anyway to see if latest version improves.

**Comment by lukasroegner** [comment]
> Maybe add an option for the retry, whether it’s enabled and how frequently to retry.

That's exactly what I did.

**Comment by twynne** [comment]
Brilliant 😁 sorry hadn’t gotten To release notes yet.

**Comment by twynne** [comment]
After upgrade it no longer works here... First restart, with retry disabled, failed to log in at first attempt and then didn't retry (as expected).  Enabled retry with a low interval of 1 minute, now won't let me back in.

I can't figure what about using this plugin is different for me, why it works for others but locks me out.  Thoughts?

**Comment by lukasroegner** [comment]
> Enabled retry with a low interval of 1 minute, now won't let me back in.
Did you use the correct value in milliseconds, `60000`?

I don't know why you have such issues, I can only assume that the blocking mechanism of the Dyson API stores the number of requests for multiple days, thus a single request is enough to get blocked again.

I would suggest to try it again tomorrow (once) and then let homebridge run for some days before restarting.

**Comment by twynne** [comment]
Yes I used 60000, and then monitored in the logs to ensure it was correct. I've disabled again for now and will try later to get it working again. I don't suppose you know what the interval is at which it again allows a login attempt?

**Comment by twynne** [comment]
Also out of interest does the iOS app use the same API? Just wondering if somehow also having the app logged in could be part of the issue (even though not currently open)?

**Comment by lukasroegner** [comment]
No, I don't know the interval, as the API is not officially documented.

**Comment by esummers** [comment]
> Also out of interest does the iOS app use the same API? Just wondering if somehow also having the app logged in could be part of the issue (even though not currently open)?
  
As far as I can tell not an issue to use the app while setting up or after.  If there were problems with the configuration I think it blacklists temporarily, but seems to be just Homebridge.  App still works.  When configured correctly it ignored commands without showing errors.  I came back in a couple hours and it was working perfectly.

**Comment by lukasroegner** [comment]
Another update: I've added an option to run the plugin without the Dyson API.

The following steps are needed:
- Start the plugin. It will communicate with the Dyson API to retrieve the credentials for your devices. Those credentials are printed out in the logs for each device.
- Copy the credentials for each device from the logs to the config.json (see README)
- Restart homebridge. Now, the Dyson API is not used anymore.

**Comment by ijm51000** [comment]
I guess once you have successfully authenticated you are given a session cookie that persists for a limited time, hence the ios app will not be blacklisted as its session is already authenticated.   

Perhaps if you have a problem with the plugin, disable the plugin, wait a bit, change your password via the website and then retry?

But then Lukas seems to be super responsive and has offered another way to resolve the issue

**Comment by twynne** [comment]
It’s now working here, but I still noticed it locked out after the previous restart (first in over 24 hours and necessary to update the plugin!). It then worked again after about 10 minutes, which was enough to get the credentials. There’s something very random about the lockout.

**Comment by lukasroegner** [comment]
@twynne I assume that you now use the stored credentials method, thus the Dyson API is no longer needed (only if you add new devices). I'll close this issue, feel free to reopen if you have further issues.
