### ISSUE TITLE
Homebridge startet nicht

### ISSUE THREAD

**Issue by nico1411** [lukasroegner/homebridge-dyson-pure-cool#59]
Ich habe die Konfiguration gemacht und nun startet Hoobs nicht mehr. Es kommt immer der Fehler: 

TypeError: platform.config.devices.some is not a function
    at DysonPureCoolPlatform.getDevicesFromConfig (/home/hoobs/.hoobs/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-platform.js:246:33)
    at API.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-platform.js:72:22)
    at API.emit (events.js:228:7)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:91:15)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)

Der Ventilator taucht auch nicht in Homekit auf... Habe ich etwas falsch gemacht? Ich habe noch keine Erfahrung mit Hoobs/ programmiersprache...

vielen dank im voraus!

**Comment by lukasroegner** [comment]
Please post your config here. It seems that you misconfigured the `devices` property.

**Comment by nico1411** [comment]
{
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "username": "<n.eggenweiler88@gmail.com>",
            "password": "<Pxxxxxxxxxxx03>",
            "countryCode": "<EU>",
            "devices": [
                {
                    "ipAddress": "192.168.178.74",
                    "serialNumber": "NN2-EU-KMA252xx",
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": false
                }
            ],
            "updateInterval": 15000,
            "retrySignInInterval": 0
        }
    ]
}

So ist es in dem Konfig-Fenster von dem Plug-in. Ich habe das Passwort und die Seriennummer mit einem x versehen, aber in der richtigen Konfig ist es mit den richtigen Werten.

Vielen Dank für ihre Hilfe!

**Comment by nico1411** [comment]
![IMG_0194](https://user-images.githubusercontent.com/63658033/79327810-5bd5cb00-7f15-11ea-9bf5-0b7b3f6d16cc.JPEG)

**Comment by nico1411** [comment]
Ich habe übrigens den 2018 Pure Cool link (ohne display)

**Comment by lukasroegner** [comment]
Your screenshot show some angle brackets in the fields `username`, `password` and `countryCode`, you should delete them.

Wrong: `"<n.eggenweiler88@gmail.com>"`
Correct: `"n.eggenweiler88@gmail.com"`

However, that should not be the actual issue.

**Comment by lukasroegner** [comment]
For the other issue, it might be useful to check the Node and NPM versions. Please run
```
node --version
```
and
```
npm --version
```
on the command line and post the version numbers here.

**Comment by nico1411** [comment]
node --version: v12.14.1
npm --version: 6.13.4

**Comment by lukasroegner** [comment]
I did a test on my local machine with the exact config that you posted (added a random password). The plugin got over the point where your exception occurs.

My suggestions are:
- Restart the machine
- Check if there is an update for Hoobs
- Restart Hoobs

**Comment by nico1411** [comment]
Ich habe die 3 punkte gemacht und bekomme immernoch den fehler. 

![IMG_0195](https://user-images.githubusercontent.com/63658033/79331605-ba05ac80-7f1b-11ea-8eed-0a530c7d0eb3.JPEG)

**Comment by nico1411** [comment]
komischerweise sagt es auch. "loading 0 accessories"

**Comment by lukasroegner** [comment]
I've published a new version (1.6.1) with an additional check for a valid configuration. That should help to debug your issue. Please update to 1.6.1 and try again.

**Comment by nico1411** [comment]
Ich habe jetzt diesen Teil "{"platforms":" gelöscht und nun startet der Service. Dennoch kommt diese Fehler: 

Device credentials not stored, asking Dyson API. If you want to prevent communication with the Dyson API, copy the credentials for each device from the coming log entries to the config.json.

Error while signing in. Status Code: 400

API could not be reached. Retry is disabled.

**Comment by nico1411** [comment]
Gleicher Fehler auch bei Version 1.6.1

**Comment by lukasroegner** [comment]
> Ich habe jetzt diesen Teil "{"platforms":" gelöscht und nun startet der Service

Ich nutze Hoobs nicht, empfehle es nicht und kann daher auch keinen Support dafür geben. Anscheinend muss man dort die config pro Plugin getrennt machen. Das war also mal der erste Fehler. Gelöst.

> Error while signing in. Status Code: 400

Hast du den korrekten Country-Code angegeben? Wenn du aus Deutschland kommst muss der Wert `DE` sein. 

Deine config sollte jetzt so aussehen:
```json
{
	"platform": "DysonPureCoolPlatform",
	"username": "n.eggenweiler88@gmail.com",
	"password": "DEINPASSWORT",
	"countryCode": "DE",
	"devices": [
		{
			"ipAddress": "192.168.178.74",
			"serialNumber": "NN2-EU-KMA252xx",
			"enableAutoModeWhenActivating": false,
			"isNightModeEnabled": false,
			"isJetFocusEnabled": false,
			"isTemperatureSensorEnabled": false,
			"isHumiditySensorEnabled": false,
			"isAirQualitySensorEnabled": false
		}
	],
	"updateInterval": 15000,
	"retrySignInInterval": 0
}
```

**Comment by nico1411** [comment]
mit der richtigen Konfig kommt dieser fehler:
Check the devices property, it has to be a valid array.

**Comment by nico1411** [comment]
nachdem ich den service neu gestartet habe kommt der Fehler:
No IP address provided for device with serial number NN2-EU-KMA2521B.

**Comment by lukasroegner** [comment]
Das ist gut, wieder ein Schritt weiter. Diese Seriennummer aus dem Log sollte als Seriennummer in deiner Config stehen.

**Comment by nico1411** [comment]
ich habe gerade in der Homemanager-app nochmal die Daten eingegeben, jetzt gehts. Jetzt habe ich nur noch eine Sache: Wenn oszillieren an ist und ich den Lüfter in Homekit ausschalte und danach wieder an, wird oszillieren deaktiviert. Kann man das umstellen, sodass die letzte Einstellung für oszillieren bleibt? 
Zudem würde ich mich gerne bedanken, dazu bräuchte ich einmal ihre Papyal email adresse :)

Die Konfig sieht nun etwas anders aus, aber es geht. (Bild davon im Anhang)

Vielen Dank!
![IMG_0196](https://user-images.githubusercontent.com/63658033/79337368-ac552480-7f25-11ea-9556-a7e3eee2906c.JPEG)

**Comment by lukasroegner** [comment]
Die Homemanager-App scheint die Konfiguration etwas durcheinanderzubringen...aber wenn es läuft dann läuft es. 

> Wenn oszillieren an ist und ich den Lüfter in Homekit ausschalte und danach wieder an, wird oszillieren deaktiviert. Kann man das umstellen, sodass die letzte Einstellung für oszillieren bleibt?

Ich kann mich daran erinnern, dass die Speicherung der Oszillation bei TP02 und DP02 nicht funktioniert. Bei den neueren Modellen wird diese gespeichert, ich habe bei mir einen TP04 und DP04 stehen.

> Zudem würde ich mich gerne bedanken, dazu bräuchte ich einmal ihre Papyal email adresse :)

Vielen Dank für das Angebot, aber es handelt sich hier um ein Hobby-Projekt, mit dem ich der Community etwas zurückgeben möchte!
