### ISSUE TITLE
iOS13 layout issues

### ISSUE THREAD

**Issue by lukasroegner** [lukasroegner/homebridge-dyson-pure-cool#6]
If night mode or jet focus switches are enabled, the iOS 13 Home app displays all "devices" in a single view, which results in an ugly-looking interface. To prevent this, the night mode and jet focus switches should be exposed as separate accessories.

This issue should be tackled after Apple releases the final iOS 13 version, as things might change. In the meantime, you could disable the night mode and jet focus switches.

**Comment by Krocko** [comment]
Can you do anything about the missing labels in the Apple’s Home app?
I use the homebridge-neato plugin and there are the labels in the home app. Any chance that you von fix this?

 <img src="https://user-images.githubusercontent.com/29394115/63214700-dbf42880-c11b-11e9-8cdf-d1e5ed566d06.png" width="300"> <img src="https://user-images.githubusercontent.com/29394115/63214699-dbf42880-c11b-11e9-9740-5ca506ef374d.png" width="300">

**Comment by lukasroegner** [comment]
@Krocko Why is there a switch with a fan icon in the air purifier accessory? What does it do?

By default, it seems that the labels for on/off button and rotation speed of air purifiers are hidden in iOS 13. When you enable night mode, the night mode switch actually has a label (see images of @CooperCGN in #1). I can understand this decision (as air purifier only has an on/off switch and a rotation speed bar) and it looks fine if just those two controls are visible.

**Comment by CooperCGN** [comment]
@lukasroegner I did not have any labels on iOS 13 either, you mentioned them with your beta installed. Maybe we should wait and see what happens in the final release. It seems that Apple still is changing a lot of stuff.

**Comment by Krocko** [comment]
> Why is there a switch with a fan icon in the air purifier accessory? What does it do?

This is the Nightmode button. I changed the icon from switch to fan in the home app.

**Comment by ukypayne** [comment]
So the way that iOS 13 shows switches, instead of having all the parameters listed in a room, it combines them into one accessory. This then exposes the individual switches inside the accessory.

**Comment by lukasroegner** [comment]
It seems to be that labels are only shown if multiple services of the same type are grouped (e.g. a switch service for Jet Focus and a switch service for Night Mode).

No switches:
![IMG_2622](https://user-images.githubusercontent.com/16758848/63222955-bd8b3d00-c1ae-11e9-865a-842c39fa12aa.png)

Night Mode only:
![IMG_2623](https://user-images.githubusercontent.com/16758848/63222964-cd0a8600-c1ae-11e9-840e-16ffeeec8c13.png)

Night Mode + Jet Focus:
![IMG_2624](https://user-images.githubusercontent.com/16758848/63222969-d85db180-c1ae-11e9-820a-af6da5e9fbbe.png)
![IMG_2625](https://user-images.githubusercontent.com/16758848/63222970-d85db180-c1ae-11e9-97a2-2f853693d9f9.png)

**Comment by lukasroegner** [comment]
I updated to 13.1 Beta yesterday, still no changes regarding visualisation of multiple services in a single accessory. I'm going to implement a separate accessory for the night mode and the jet focus switches (you can name it something like "Settings"). Played around with the HAS and it looks fine to me (two switches side by side with labels underneath each switch.

Due to the architecture of the current plugin, it is not as simple as it seems to have multiple accessories for a physical device. As soon as #7 is closed and merged to the master branch, I'm going to start development.

**Comment by lukasroegner** [comment]
Finished refactoring the plugin, so that multiple plugins can be easily exposed, latest version is on the `development` branch. I'll test the implementation for some days, feel free to try it out and report bugs. Here are the results for a 2018 Dyson with separate sensors disabled and night mode/jet focus both enabled:

Two separate accessories show up, the air purifier and a second "settings" accessory:
![IMG_2631](https://user-images.githubusercontent.com/16758848/63874326-9fe58100-c9c1-11e9-8491-66e380a9c148.PNG)

Air purifier accessory (clean UI, all properties directly accessible):
![IMG_2632](https://user-images.githubusercontent.com/16758848/63874401-c0add680-c9c1-11e9-95ee-57fbf015da02.PNG)
![IMG_2633](https://user-images.githubusercontent.com/16758848/63874409-c5728a80-c9c1-11e9-855b-c0c245c8e31b.PNG)
![IMG_2634](https://user-images.githubusercontent.com/16758848/63874425-cd322f00-c9c1-11e9-834d-f140ca1bef83.PNG)

"Settings" accessory with switches:
![IMG_2635](https://user-images.githubusercontent.com/16758848/63874479-de7b3b80-c9c1-11e9-8088-e54cbba6ef39.PNG)

**Comment by lukasroegner** [comment]
Did find a bug when restarting homebridge...please wait until I fixed it before testing the development branch.

**Comment by lukasroegner** [comment]
Bug fixed, restarting homebridge now also works.

**Comment by CooperCGN** [comment]
Nice work! When are you merging that into the master branch?

**Comment by lukasroegner** [comment]
I‘m going to try it out for some days before merging into master, maybe Sunday

**Comment by lukasroegner** [comment]
Enhancements merged into master with #9. New version published on NPM.

**Comment by Krocko** [comment]
Hi Lukas.
Now i have the Jet Focus switch but my Fan don't have this option. 
In the config.json it is also `false`. 
In the Home app the jet focus switch is on. If i toggle this switch i get the following error:
```
TypeError: Cannot read property '1' of undefined
    at MqttClient.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/index.js:787:84)
    at MqttClient.emit (events.js:198:13)
    at MqttClient._handlePublish (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:940:12)
    at MqttClient._handlePacket (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:305:12)
    at work (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:709:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by lukasroegner** [comment]
@Krocko found the bug and fixed it. Please

* Install latest version (1.0.1)
* Disable night mode and jet focus in config.json
* Start homebridge
* Stop homebridge
* Enable night mode in config.json
* Start homebridge

The plugin has to be loaded with both switches disabled so that the jet focus switch is actually removed. Afterwards, you can enable night mode again in the config.json

**Comment by Krocko** [comment]
Worked now. Thank you.

**Comment by CooperCGN** [comment]
So Apple heard all the complaints, I leave the pic without any further comment ;)
![9C5A12F5-736B-48FE-ABE7-C607D467296E](https://user-images.githubusercontent.com/29116509/66116877-c8215a80-e5d3-11e9-93f6-85403db3ddaf.jpeg)

**Comment by Krocko** [comment]
This is cool.
Maybe @lukasroegner can now combine the sensors to mimic an EVE Room?
