### ISSUE TITLE
Fan speed control missing

### ISSUE THREAD

**Issue by arbyter** [lukasroegner/homebridge-dyson-pure-cool#61]
Hey, can't find fan speed control in my homekit app. Config is plain and simple:
What do I miss?

```json
{
"username": "email@lala.com",
"devices": [{
   "ipAddress": "1.2.3.4",
   "serialNumber": "abc",
   "credentials": "xyz",
   "isJetFocusEnabled": false
  }],
 "platform": "DysonPureCoolPlatform"
}
```

**Comment by lukasroegner** [comment]
Can you clarify that? Does an air purifier accessory show up (with on/off) but no fan speed control?

**Comment by arbyter** [comment]
It was my fault based on wrong assumption: The eve home app - my goto homekit app - does not support this feature. Apples home app instead supports it and shows all panels.

**Comment by lukasroegner** [comment]
I can see all settings in Eve. Have you pressed on the device to get into the details view (don‘t press the on/off toggle, click on the name of the device in the overview list)?

**Comment by arbyter** [comment]
okay, that wasn't obvious: I only tried the toggle direct! I had no idea to tap on the lable to access the complete features. Instead I expected it below the Air Quality Status panel and taped on it - without success.
