### ISSUE TITLE
HP06 Filter Life issue

### ISSUE THREAD

**Issue by Ti-Bo** [lukasroegner/homebridge-dyson-pure-cool#63]
Hi, thanks for this plugin !
I know that HP06 is new and it works fine with the plugin except for filter life indication. It's seems inverted. The filter is new and Home is displaying "change filter" and filter life at 0%.
Thanks for your help :)

![IMG_F6EDED8A6C54-1](https://user-images.githubusercontent.com/16858560/79685501-9a32f900-8239-11ea-9cce-fccb9571730e.jpeg)

**Comment by lukasroegner** [comment]
Hi @Ti-Bo,

Can you tell me what device model is shown in the Home app? The HP06 is currently not supported, however, as it is shown in your Home app, it must have the same model number as another Dyson device.

**Comment by Ti-Bo** [comment]
The device model shown is :  "Dyson Pure Hot+Cool" in Home app.

**Comment by lukasroegner** [comment]
OK, it seems that the HP04 and HP06 share the same model number. Can you please start homebridge in debug mode (parameter `-D`) and share the log messages for `CURRENT-STATE` changes? This will help me finding the correct filter life value for this model.

**Comment by Ti-Bo** [comment]
MQTT message received: {"msg":"CURRENT-STATE","time":"2020-04-22T13:56:27.000Z","mode-reason":"PUI","state-reason":"MODE","rssi":"-42","channel":"11","fqhp":"105280","fghp":"71696","product-state":{"fpwr":"OFF","auto":"ON","oscs":"OFF","oson":"OFF","nmod":"OFF","rhtm":"ON","fnst":"OFF","ercd":"40F6","wacd":"NONE","nmdv":"0004","fnsp":"AUTO","bril":"0002","corf":"ON","cflr":"INV","hflr":"0100","cflt":"SCOF","hflt":"GCOM","sltm":"OFF","osal":"0180","osau":"0180","ancp":"CUST","hmod":"OFF","hmax":"2885","tilt":"OK","hsta":"OFF","psta":"OFF","fdir":"ON"},"scheduler":{"srsc":"0000000000000000","dstv":"0000","tzid":"0001"}}

**Comment by lukasroegner** [comment]
@Ti-Bo please check out the latest version 1.6.2 of the plugin. HomeKit should now show you the correct value for filter life.

**Comment by Ti-Bo** [comment]
@lukasroegner It works ! Thank you !  👍 
![IMG_FE66FDE259EE-1](https://user-images.githubusercontent.com/16858560/80074666-d02df100-8549-11ea-84bf-c2e00c8f46e7.jpeg)
