### ISSUE TITLE
Control & Status of Fan unresponsive

### ISSUE THREAD

**Issue by town3r** [lukasroegner/homebridge-dyson-pure-cool#64]
since yesterday i have been unable to get an updated status from the fan or control it via homekit.

Dyson mobile app still controls it just fine.

**Comment by lukasroegner** [comment]
Have you checked the logs? Are other plugins running on the same homebridge instance?

**Comment by town3r** [comment]
A total of 3 plugins at the moment.

Installed:
- Homebridge Config UI X v4.15.1
- Homebridge Dyson Pure Cool v1.6.1
- Homebridge Ring v7.2.2

Uninstalled:
- Homebridge Dyson Link (also wasn't working, found this verified plugin, was hoping it would work.)

Ring plugin is still working as expected.

**Comment by town3r** [comment]
🤦 IP Address of fan changed.....
False alarm. 
Apologies
