### ISSUE TITLE
Error: Accessories must be created with a non-empty displayName.

### ISSUE THREAD

**Issue by keremerkan** [lukasroegner/homebridge-dyson-pure-cool#67]
I have been using Homebridge for quite some time. With the new easier Homebridge installation, I removed my old configuration and started a new installation.

To use my Dyson Pure Cool with Homebridge, I installed homebridge-dyson-pure-cool instead of another similar plugin as yours has support for configuration from the UI. But unfortunately, after entering the necessary information, it gives the infamous ```Error: Accessories must be created with a non-empty displayName.``` error after trying to add an accessory and disables homebridge altogether.

Following is the generated config by the UI.

```json
{
            "username": "MY_USERNAME",
            "password": "MY_PASSWORD",
            "countryCode": "TR",
            "devices": [
                {
                    "ipAddress": "DEVICE_IP",
                    "serialNumber": "XXX-TR-XXXXXXXX",
                    "credentials": "DEVICE_CREDENTIALS_OBTAINED_FROM_API",
                    "enableAutoModeWhenActivating": true,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": true,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true
                }
            ],
            "platform": "DysonPureCoolPlatform"
        },
```

And here is the log generated:

```
[DysonPureCoolPlatform] Adding new accessory with serial number XXX-TR-XXXXXXXX and kind AirPurifierAccessory.
Error: Accessories must be created with a non-empty displayName.
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:15:27)
    at new DysonPureCoolDevice (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-device.js:75:32)
    at DysonPureCoolPlatform.getDevicesFromConfig (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-platform.js:271:31)
    at API.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/src/dyson-pure-cool-platform.js:78:22)
    at API.emit (events.js:310:20)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:103:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Homebridge is running on port 51345.
Got SIGTERM, shutting down Homebridge...
```

As the accessory is not generated and added to the config, I am unable to add a ```displayName``` to it myself. Any suggestions on how to continue?

Thanks in advance.

**Comment by lukasroegner** [comment]
The issue is that you haven't set up the device room in the Dyson app.

1. Remove the `credentials` property from the configuration
2. Provide a room (name) for the device in the Dyson app
3. Restart homebridge
4. Copy the credentials from the logs and use those for storing them in the config

**Comment by keremerkan** [comment]
Thank you very much for your fast response. Indeed, I was using the default name in the Dyson Link app. Giving a custom name fixed the problem.

Perhaps adding this as a warning to the README can be useful for future users like me.

Another suggestion would be to use a default name (perhaps using the serial and/or model number) when a name cannot be retrieved from the API, so that the error condition is not encountered.

Again, thank you for your help and this great plugin.

**Comment by lukasroegner** [comment]
I already added a default name in case the API does not provide on (1.6.4).

**Comment by keremerkan** [comment]
I encountered this problem on 1.6.4 though.

**Comment by lukasroegner** [comment]
But you created the credentials with an earlier version (the also "cache" the device name from the API).

**Comment by keremerkan** [comment]
My bad, it looks like you added 1.6.4 only 28 minutes ago. Great work! :)
