### ISSUE TITLE
HomeKit and Dyson temperature settings 

### ISSUE THREAD

**Issue by Soldiiier** [lukasroegner/homebridge-dyson-pure-cool#68]
Home app has a decimal granularity of 0.5, however the Dyson can only take full integers. 
Example: When choosing 22.5° In the home app, Dyson interprets this as 22°, but asking Siri rounds it up to 23° when checking what the setting is at. 
Is there a way to have the HomeKit thermostat service only take integers?
Or, if this is a fixed behaviour, can the input to the Dyson be rounded up to match what Siri reports this as?
![CEC6BD85-1D6E-4E9E-AA56-FCCEC869F12E](https://user-images.githubusercontent.com/16224280/80251436-ef975c00-86b8-11ea-8519-3241c43e7c0a.png)
![BB3E4AA0-8838-4E16-B4A9-4A3AB193587F](https://user-images.githubusercontent.com/16224280/80251450-f625d380-86b8-11ea-910c-63351dcdcd9f.png)
![B7EC7384-CF90-4E58-8589-CA7716E9DD83](https://user-images.githubusercontent.com/16224280/80251459-f7ef9700-86b8-11ea-8e34-f89299642915.png)

**Comment by lukasroegner** [comment]
Changed temperature steps to integers in new version 1.6.5.
