### ISSUE TITLE
no

### ISSUE THREAD

**Issue by bondskin** [lukasroegner/homebridge-dyson-pure-cool#69]
I see the following error

[4/25/2020, 19:55:18] [DysonPureCoolPlatform] Signed in.
[4/25/2020, 19:55:18] [DysonPureCoolPlatform] No IP address provided for device with serial number NN2-EU-KMA2960B.
[4/25/2020, 19:55:18] [DysonPureCoolPlatform] Got devices from the Dyson API.

Although IP address is in the config file and device is pingable.
"ipAddress": "192.168.2.216"

No device shows up in Homebridge

**Comment by lukasroegner** [comment]
Please check that the device entry in the configuration (where the property `"ipAddress": "192.168.2.216"` resides) also has the correct property `"serialNumber": "NN2-EU-KMA2960B"`.

**Comment by bondskin** [comment]
yes... entered using the wizard after installing the plugin

{
            "username": "xxx",
            "password": "xxx",
            "devices": [
                {
                    "ipAddress": "192.168.2.216",
                    "serialNumber": "NN2-EU-KMA2906B",
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true
                }
            ],
            "platform": "DysonPureCoolPlatform"
        }

**Comment by lukasroegner** [comment]
Typo in the serial number

**Comment by bondskin** [comment]
oh man..... how stupid. thank you!
