### ISSUE TITLE
Activate Night mode only when Dyson actually is on.

### ISSUE THREAD

**Issue by CooperCGN** [lukasroegner/homebridge-dyson-pure-cool#7]
When activating night mode but Dyson isn’t working it is overwriting current speed settiings. Usually no problem but makes automations unnecessary complicated as I can’t simply add night mode to my good night scene but instead need to add multiple automations with conditions. Any chance that this somehow could be integrated into the plugin logic?

**Comment by lukasroegner** [comment]
@CooperCGN could you provide a snippet from the log where you activate night mode?

**Comment by CooperCGN** [comment]
First entry I set the rot speed to 7, then turned it off and turned on night mode. When turning on again rot speed is on 4 (where it should be seven)

```
Aug 22 13:54:22 raspberrypi homebridge[14389]: [8/22/2019, 1:54:22 PM] [DysonPureCoolPlatform] VW2-EU-KDA1200A - set RotationSpeed to 70: {"fnsp":"0007"}
Aug 22 13:54:22 raspberrypi homebridge[14389]: [8/22/2019, 1:54:22 PM] [DysonPureCoolPlatform] VW2-EU-KDA1200A - set Active to 1: {"fpwr":"ON","fmod":"FAN"}
Aug 22 13:54:22 raspberrypi homebridge[14389]: [8/22/2019, 1:54:22 PM] [DysonPureCoolPlatform] VW2-EU-KDA1200A - MQTT message received: {"msg":"STATE-CHANGE","time":"2019-08-22T11:54:21.000Z","mode-reason":"NONE","state-reason":"MODE","product-state":{"fpwr":["ON","ON"],"auto":["OFF","OFF"],"oscs":["ON","ON"],"oson":["ON","ON"],"nmod":["OFF","OFF"],"rhtm":["ON","ON"],"fnst":["FAN","FAN"],"ercd":["11E1","11E1"],"wacd":["NONE","NONE"],"nmdv":["0004","0004"],"fnsp":["0006","0007"],"bril":["0002","0002"],"corf":["ON","ON"],"cflr":["0045","0045"],"hflr":["0045","0045"],"cflt":["CARF","CARF"],"hflt":["GHEP","GHEP"],"sltm":["OFF","OFF"],"osal":["0240","0240"],"osau":["0285","0285"],"ancp":["0045","0045"],"fdir":["ON","ON"]},"scheduler":{"srsc":"0000000000000000","dstv":"0000","tzid":"0001"}}
Aug 22 13:55:33 raspberrypi homebridge[14389]: [8/22/2019, 1:55:33 PM] [DysonPureCoolPlatform] VW2-EU-KDA1200A - set Active to 0: {"fpwr":"OFF","fmod":"OFF"}
Aug 22 13:55:33 raspberrypi homebridge[14389]: [8/22/2019, 1:55:33 PM] [DysonPureCoolPlatform] VW2-EU-KDA1200A - MQTT message received: {"msg":"STATE-CHANGE","time":"2019-08-22T11:55:32.000Z","mode-reason":"NONE","state-reason":"MODE","product-state":{"fpwr":["ON","OFF"],"auto":["OFF","OFF"],"oscs":["ON","ON"],"oson":["ON","ON"],"nmod":["OFF","OFF"],"rhtm":["ON","ON"],"fnst":["FAN","OFF"],"ercd":["11E1","11E1"],"wacd":["NONE","NONE"],"nmdv":["0004","0004"],"fnsp":["0007","0007"],"bril":["0002","0002"],"corf":["ON","ON"],"cflr":["0045","0045"],"hflr":["0045","0045"],"cflt":["CARF","CARF"],"hflt":["GHEP","GHEP"],"sltm":["OFF","OFF"],"osal":["0240","0240"],"osau":["0285","0285"],"ancp":["0045","0045"],"fdir":["ON","ON"]},"scheduler":{"srsc":"0000000000000000","dstv":"0000","tzid":"0001"}}
Aug 22 13:55:36 raspberrypi homebridge[14389]: [8/22/2019, 1:55:36 PM] [DysonPureCoolPlatform] VW2-EU-KDA1200A - set NightMode to true: {"nmod":"ON"}
Aug 22 13:55:36 raspberrypi homebridge[14389]: [8/22/2019, 1:55:36 PM] [DysonPureCoolPlatform] VW2-EU-KDA1200A - MQTT message received: {"msg":"STATE-CHANGE","time":"2019-08-22T11:55:35.000Z","mode-reason":"NONE","state-reason":"MODE","product-state":{"fpwr":["OFF","OFF"],"auto":["OFF","OFF"],"oscs":["ON","ON"],"oson":["ON","ON"],"nmod":["OFF","ON"],"rhtm":["ON","ON"],"fnst":["OFF","OFF"],"ercd":["11E1","11E1"],"wacd":["NONE","NONE"],"nmdv":["0004","0004"],"fnsp":["0007","0004"],"bril":["0002","0002"],"corf":["ON","ON"],"cflr":["0045","0045"],"hflr":["0045","0045"],"cflt":["CARF","CARF"],"hflt":["GHEP","GHEP"],"sltm":["OFF","OFF"],"osal":["0240","0240"],"osau":["0285","0285"],"ancp":["0045","0045"],"fdir":["ON","ON"]},"scheduler":{"srsc":"0000000000000000","dstv":"0000","tzid":"0001"}}
Aug 22 13:55:38 raspberrypi homebridge[14389]: [8/22/2019, 1:55:38 PM] [DysonPureCoolPlatform] VW2-EU-KDA1200A - MQTT message received: {"msg":"STATE-CHANGE","time":"2019-08-22T11:55:37.000Z","mode-reason":"NONE","state-reason":"MODE","product-state":{"fpwr":["OFF","OFF"],"auto":["OFF","OFF"],"oscs":["ON","OFF"],"oson":["ON","ON"],"nmod":["ON","ON"],"rhtm":["ON","ON"],"fnst":["OFF","OFF"],"ercd":["11E1","11E1"],"wacd":["NONE","NONE"],"nmdv":["0004","0004"],"fnsp":["0004","0004"],"bril":["0002","0002"],"corf":["ON","ON"],"cflr":["0045","0045"],"hflr":["0045","0045"],"cflt":["CARF","CARF"],"hflt":["GHEP","GHEP"],"sltm":["OFF","OFF"],"osal":["0240","0240"],"osau":["0285","0285"],"ancp":["0045","0045"],"fdir":["ON","ON"]},"scheduler":{"srsc":"0000000000000000","dstv":"0000","tzid":"0001"}}
```

**Comment by lukasroegner** [comment]
Ok, a rotation speed of 4 is the default that is used in night mode (set by the Dyson device itself). You can see from the logs that the fan speed is not set by the plugin, it is a state change done by the air purifier.

You can see the same behavior in the Dyson app if you enable night mode when the fan is on. My devices always switch to 4 when enabling night mode in the Dyson app.

**Comment by CooperCGN** [comment]
I know, that's why I asked if it possible to pass the night mode command to the fan only when it is already on. If you set night mode when the Dyson is off and turn him on afterwards night mode gets deactivated anyway. If you do it the other way round (setting night mode when dyson is on) the fan returns to it previous speed setting after night mode is again deactivated.

**Comment by lukasroegner** [comment]
I haven't used night mode that often. Can you confirm that enabling night mode via remote or Dyson app always results in a fan speed of 4?

**Comment by CooperCGN** [comment]
What I described above would replicate the behavior of using the remote. Night mode button on the remote works only when Dyson is already turned on and then always defaults to 4. Pressing it again returns it to previous speed. As I am using NM extensively this would save some automations in HomeKit.

**Comment by lukasroegner** [comment]
Possible solution:
* If you enable night mode AND the device is off, the current fan speed is stored in a variable.
* If you change any setting manually (On/Off, Rotation Speed, Auto mode), the variable is cleared.
* If you disable night mode AND the variable still contains a value, the rotation speed stored in the variable is set and the variable is cleared.
Thoughts?

**Comment by CooperCGN** [comment]
Isn't that a bit too complicated? The current speed is stored by the fan itself. Just include some logic that when night mode in HomeKit is turned on but the fan itself is still off that nothing happens. Or am I missing now any other scenario that might then not work?

**Comment by lukasroegner** [comment]
Do you mean just do nothing when changing the night mode switch (and the device is off)?

**Comment by CooperCGN** [comment]
That would be the exact behavior as if using the IR remote. When using the Dyson app the app turns on the fan as normal and then switches to NM. So there is two choices when using NM in HomeKit, either do nothing or turn on the fan first and then turn on NM. Too bad that even Dyson isn't consistent how their devices get controlled.

**Comment by lukasroegner** [comment]
I'm not a fan of controls that don't behave as expected (i.e. do nothing). I would prefer to implement the behavior of the Dyson app, where the device is activated when enabling night mode. Would that help you with your automations?

**Comment by CooperCGN** [comment]
Definitely, at least I don't need that automations anymore in the morning that check if the fan was running in night mode over night and then proceed from there with further logic. I simply would include all NM buttons as "off" in the good morning scene, those actually running return to normal, those that were off stay off.

**Comment by lukasroegner** [comment]
@andrewtzn This is not possible in the Home app. The app decides on how the accessories are displayed.

**Comment by lukasroegner** [comment]
@CooperCGN Updated the development branch, could you try it out? I did some quick tests and it now works as expected:

* If the device is on and you enable night mode and disable it again, the previous rotation speed is restored
* If the device is off and you enable night mode, the device is enabled. If you then disable night mode, the previous rotation speed is restored

**Comment by CooperCGN** [comment]
How do I install the development branch?

sudo npm install -g homebridge-dyson-pure-cool ???

**Comment by lukasroegner** [comment]
You can install NPM packages from any Git repository and any branch, in this case I would recommend:

`npm uninstall -g homebridge-dyson-pure-cool`
`npm install -g https://github.com/lukasroegner/homebridge-dyson-pure-cool.git#development`

**Comment by lukasroegner** [comment]
BTW, it is save to switch sources of an NPM package, you won't loose any settings in homebridge. As I haven't bumped the package version on the development branch yet, uninstalling the current version is recommended as NPM might use a cached version.

**Comment by CooperCGN** [comment]
I tried to install plugins like that before and always get this as error:
```
sudo npm install -g https://github.com/lukasroegner/homebridge-dyson-pure-cool.git#development
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b development https://github.com/lukasroegner/homebridge-dyson-pure-cool.git /root/.npm/_cacache/tmp/git-clone-ff1dea8e
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-ff1dea8e': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-28T08_12_05_810Z-debug.log
```

**Comment by lukasroegner** [comment]
Do you always install/uninstall npm packages with `sudo`?

**Comment by CooperCGN** [comment]
Yes, otherwise I get tons of permission errors. Always has been like this.

**Comment by lukasroegner** [comment]
Hmm, could be an outdated Git version...check out https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/54 they solved it with `sudo -s`. 

If that doesn't work, you can either try to update npm, Git, etc. or wait until I finish additional tests and integrate it into the master branch/make a new package version on npm.

**Comment by CooperCGN** [comment]
Git is latest 2.11 version, I have no idea what it is because that tmp directory mentioned in the error log exists and owner is the user pi. ls -lh shows this: `drwxr-xr-x   2 pi pi 4.0K Aug 28 10:30 tmp`

I will wait until it is merged.

**Comment by lukasroegner** [comment]
New package 0.3.0 on NPM.

**Comment by CooperCGN** [comment]
Sorry, if I need to come back to this once more but there’s still some error in the handling of the night mode switch.
Assuming the Dyson is running in night mode and you turn it off either by timer, remote or from HomeKit the night mode switch in HK stays in the on mode. Internally switching the Dyson off disables night mode already. I have the night mode buttons included in my good morning scene but now when they’re set to off the Dysons turn on when not running due to one off the above mentioned.
That means turning the Dyson off should result in setting the night switch in HK to off without further action, switching off night mode should not turn on the Dyson. Any idea?

**Comment by lukasroegner** [comment]
@CooperCGN new version 1.0.3 on NPM. There has been a bug in the night mode logic, which switched of the device if you switch off night mode. This should work now. Can you test the latest version and check if that resolves your issue?

**Comment by CooperCGN** [comment]
No, turning on night mode now crashes Homebridge

**Comment by CooperCGN** [comment]
```
Sep 05 08:24:31 raspberrypi homebridge[26793]: [9/5/2019, 8:24:31 AM] TypeError: Assignment to constant variable.
Sep 05 08:24:31 raspberrypi homebridge[26793]:     at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-pure-cool/index.js:877:23)
Sep 05 08:24:31 raspberrypi homebridge[26793]:     at Characteristic.emit (events.js:198:13)
Sep 05 08:24:31 raspberrypi homebridge[26793]:     at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Sep 05 08:24:31 raspberrypi homebridge[26793]:     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
Sep 05 08:24:31 raspberrypi homebridge[26793]:     at Array.forEach (<anonymous>)
Sep 05 08:24:31 raspberrypi homebridge[26793]:     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
Sep 05 08:24:31 raspberrypi homebridge[26793]:     at HAPServer.emit (events.js:198:13)
Sep 05 08:24:31 raspberrypi homebridge[26793]:     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
Sep 05 08:24:31 raspberrypi homebridge[26793]:     at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Sep 05 08:24:31 raspberrypi homebridge[26793]:     at IncomingMessage.emit (events.js:198:13)
Sep 05 08:24:31 raspberrypi homebridge[26793]: [9/5/2019, 8:24:31 AM] Got SIGTERM, shutting down Homebridge...
Sep 05 08:24:31 raspber
```

**Comment by lukasroegner** [comment]
Sorry, new version already online (1.0.4).

**Comment by CooperCGN** [comment]
The only thing that might be a problem now is the following and maybe you try for yourself.

Turn on Dyson and turn in night mode, now turn the Dyson off via IR remote. Night mode switch in HomeKit stays active although it internally is already disabled. Now my next „good night“ automation which checks for running Dyson and turn on night mode accordingly will fail.

Basically whenever the Dyson it set to off it needs to turn off the night mode switch too.

**Comment by CooperCGN** [comment]
Well I need to do some testing, as the NM switch is turned off when the Dyson is turned on the next time. It is just a bit confusing.

**Comment by lukasroegner** [comment]
The issue is that the device itself handles the night mode independently from on/off state, i.e. night mode can be on if the device is off.

**Comment by CooperCGN** [comment]
Weird, when I turn it off while being in night mode and turn it on again (all by IR remote) it jumps back to normal operation, display is turned on, no moon icon. That’s why I thought that NM would be off.

**Comment by lukasroegner** [comment]
What we can do is reverse engineer what the remote command actually do to the internal configuration of the device. That means, observe the logs of the homebridge plugin and annotate them ("STATE-CHANGE" log entries) with the button pressed on the remote.

**Comment by CooperCGN** [comment]
Good idea but I won’t be able to do that before tomorrow or Saturday, too much work on the desk :-)

**Comment by andrewtzn** [comment]
I might be able to help. 
Here is the log when I cycle night mode ON and OFF with the remote:

```
[9/5/2019, 7:05:46 PM] [DysonPureCoolPlatform] XXX-US-XXXXXX - MQTT message received: {"msg":"STATE-CHANGE","time":"2019-09-05T23:05:45.000Z","mode-reason":"PRC","state-reason":"MODE","product-state":{"fmod":["AUTO","AUTO"],"fnst":["FAN","FAN"],"fnsp":["AUTO","AUTO"],"qtar":["0004","0004"],"oson":["OFF","OFF"],"rhtm":["ON","ON"],"filf":["4036","4036"],"ercd":["02C0","02C0"],"nmod":["OFF","ON"],"wacd":["NONE","NONE"]},"scheduler":{"srsc":"25c9","dstv":"0001","tzid":"0001"}}
[9/5/2019, 7:06:08 PM] [DysonPureCoolPlatform] XXX-US-XXXXXX - MQTT message received: {"msg":"STATE-CHANGE","time":"2019-09-05T23:06:07.000Z","mode-reason":"PRC","state-reason":"MODE","product-state":{"fmod":["AUTO","AUTO"],"fnst":["FAN","FAN"],"fnsp":["AUTO","AUTO"],"qtar":["0004","0004"],"oson":["OFF","OFF"],"rhtm":["ON","ON"],"filf":["4036","4036"],"ercd":["02C0","02C0"],"nmod":["ON","OFF"],"wacd":["NONE","NONE"]},"scheduler":{"srsc":"25c9","dstv":"0001","tzid":"0001"}}
[9/5/2019, 7:06:17 PM] [DysonPureCoolPlatform] XXX-US-XXXXXX - MQTT message received: {"msg":"STATE-CHANGE","time":"2019-09-05T23:06:16.000Z","mode-reason":"PRC","state-reason":"MODE","product-state":{"fmod":["AUTO","AUTO"],"fnst":["FAN","FAN"],"fnsp":["AUTO","AUTO"],"qtar":["0004","0004"],"oson":["OFF","OFF"],"rhtm":["ON","ON"],"filf":["4036","4036"],"ercd":["02C0","02C0"],"nmod":["OFF","ON"],"wacd":["NONE","NONE"]},"scheduler":{"srsc":"25c9","dstv":"0001","tzid":"0001"}}
```

**Comment by CooperCGN** [comment]
Ok, I did some further testing and I think we can leave it as it is. Even if the night mode switch is still turned on in HomeKit the logic included in the plugin turns on the Dyson when it is off but NM is still activated. Seems that HomeKit is sending that regardless of the actual state.

**Comment by CooperCGN** [comment]
By the way this is where the Dyson app and the IR remote differ. The app turns on the device when NM is activated and it is off, the IR remote doesn't. You have to turn it on and then activate NM in a second button press. A bit inconsistent and confusing.
