### ISSUE TITLE
Improvements on controls for Hot+Cool Purifiers

### ISSUE THREAD

**Issue by fifty8** [lukasroegner/homebridge-dyson-pure-cool#70]
Hi there, wondering if the following two suggestions would be considered (both related to hot+cool purifiers/fans, but separate):

1. Currently the purifier controls are stacked vertically (the ON/OFF switch on top, fan speed on bottom) -- is it possible to make them stack side-by-side? I can tinker around if you could provide some pointers.

2. Is it possible to add temperature control to the ON/OFF UI? Currently the "thermostat" is a different and unrelated accessory from the purifier, and two issues come with that:
    a. Turning off the purifier will leave the thermostat permenently in "Heating to xx.x C"; the thermostat should ideally be OFF when the purifier is turned OFF.
    b. Vice-versa, turning on the thermostat has no effect until the purifier is turned on manually.

Thanks!

**Comment by fifty8** [comment]
![Photo 2020-04-27, 4 02 48 PM](https://user-images.githubusercontent.com/11584503/80429307-a6a1fc00-88a0-11ea-87f3-9f3a0f703f7f.png)

Attached some screenshot.

**Comment by lukasroegner** [comment]
Hi @fifty8,

Homebridge plugins cannot control how the UI is displayed in the Home app. You can just specify the service type ("Air Purifier") and the characteristics, the Home app "styles" the UI for the service. In an earlier version of iOS, the large switch has been just a round button, which worked fine. I assume the large slider button in the air purifier UI is a bug and will be resolved in future versions of iOS. 

The Hot+Cool device exposes two accessories as one accessory with an air purifier AND a thermostat service would not work in the Home app.

I hope that we can have more control over the UI in the future. As soon as something changes, I'll try to enhance the plugin.
