### ISSUE TITLE
Some inconsistency using the oscillate feature

### ISSUE THREAD

**Issue by Soldiiier** [lukasroegner/homebridge-dyson-pure-cool#71]
Hello! 
I’ve done some tests and found the behaviour to be inconsistent with the oscillate feature. 

1. If the oscillation feature is turned off in the Dyson app, homekit reports the correct setting, however changing the toggle to on does not feedback the setting to the Dyson (Dyson app oscillation = off, even though homebridge oscillation = 1 command appears in the log)

2. If the oscillation is turned on in the Dyson app, then using HomeKit/bridge to toggle the oscillation setting works as expected, and the setting appears to feedback into the Dyson app too. 

In summary, it looks like if the oscillation setting is handled purely in the HomeKit app then it is fine. However I go into the Dyson app on occasion to change the oscillation settings in particular so I can angle the direction, and choose the oscillation range 45°, 90°, 180°, 350° - turning off the oscillation setting in the app makes the feature unusable in HomeKit unless turned on once more in the Dyson app. 
Additional query, What are the option for HomeKit handling oscillation ranges?

Are the screenshot logs adequate?

Thanks always for a cool plugin!

![IMG_1912](https://user-images.githubusercontent.com/16224280/80781771-fe997500-8bb6-11ea-9386-83fcb421393d.jpeg)

**Comment by Soldiiier** [comment]
Additional test, found that turn ing oscillation off in the Dyson app doesn’t show a log entry for “oson = 0”, but the switch is set to off in HomeKit.

**Comment by lukasroegner** [comment]
If you turn off oscillation in the Dyson app, it also sends commands to the device to clear the angle settings (i.e. angle is set to 0°). If you then try to enable oscillation in HomeKit, it will just enable oscillation, not change the angle settings. Currently, there is no reasonably usable HomeKit property for the angle settings of Dyson devices (especially as different models have different features), thus they haven't been implemented in the plugin.

**Comment by Soldiiier** [comment]
Makes total sense. Thanks.
Is it worth having another comfort property that sets a user defined default angle that gets sent to the Dyson if there’s no angle value.
Also is the tilting mechanism characteristic something that can be applied to air purifiers?
![B365D473-7E03-4CC6-912E-F111A25F61CE](https://user-images.githubusercontent.com/16224280/80803347-53f47700-8bf5-11ea-8948-b85509e2111b.png)

**Comment by lukasroegner** [comment]
I'll try if the tilting can also be applied for air purifiers, the docs only mention fans.

**Comment by lukasroegner** [comment]
Sadly, the mentioned characteristics do not work for air purifiers, nothing shows up in the Home app.

**Comment by Soldiiier** [comment]
Thanks for confirming!
