### ISSUE TITLE
Siri Command for Rotation

### ISSUE THREAD

**Issue by THX723** [lukasroegner/homebridge-dyson-pure-cool#72]
What is the correct Siri Command used to control rotation/oscillation?

I've not had any luck with "oscillation", "oscillate", and only limited success with "rotation" as follows:

"Hey Siri, <DeviceName> rotation Off" correctly turns off rotation/oscillation.

However,

"Hey Siri, <DeviceName> rotation On" resulted in the whole device getting shut off. Very odd.

**Comment by lukasroegner** [comment]
Hi @THX723, I tried some commands in German, also no luck. As a workaround, you can create a Siri Shortcut that changes the oscillation mode.

**Comment by THX723** [comment]
@lukasroegner Oddly, after more tries, this worked to turn on rotation, but not off.

"Hey Siri, swing On"

In either cases, it does take the purifier out of the auto mode to manual, which is also not desirable.

**Comment by THX723** [comment]
Good news. There's a work around using Eve (HomeKit App).

The 'Swing' control is exposed in Eve app, when creating a scene.

![ADC7B7C2-4F4D-4484-ABF7-79056DEC29B7_1_105_c](https://user-images.githubusercontent.com/25112621/80923744-4a285c00-8d3a-11ea-859e-7a3c55025e53.jpeg)

So I created two scenes, which can be called out accordingly.

"Hey Siri, Theater Fan Rotation On"
"Hey Siri, Theater Fan Rotation Off"

Works brilliantly!

![C99EF4A7-0448-444A-8571-BD789002D424_1_105_c](https://user-images.githubusercontent.com/25112621/80923786-8c519d80-8d3a-11ea-8085-975bccae83ea.jpeg)
