### ISSUE TITLE
Does Not Operate when on other subnet

### ISSUE THREAD

**Issue by TheUglyKorean** [lukasroegner/homebridge-dyson-pure-cool#75]
I leave IOT devices on an isolated network separate from my home bridge computer.  This is the first device that has had problems.  Login is ok and credentials get pulled, but I cannot operate the TP02.  Does this try to operate the fan directly, or can it command Dyson API to send commands from internet back to the fan much like the app?

**Comment by lukasroegner** [comment]
Hi @TheUglyKorean, the plugin uses the Dyson API only to get the credentials. Those are used to establish an MQTT connection to the devices.

**Comment by TheUglyKorean** [comment]
@lukasroegner I moved the TP02 purifier to the same network as my home bridge controller and it works perfect.  It does not work when the TP02 is on my IOT SSID which has client isolation.  Looks like the plugin requires the dyson be in the same network.

**Comment by lukasroegner** [comment]
@TheUglyKorean For the plugin to work, the host of the homebridge instance has to have access to the internet (for initial configuration and in case you do not store credentials). Moreover, to control the devices, it has to be able to communicate with the devices via MQTT. If you are able to configure your firewall properly (in case it is not a physical isolated network), you could get it to work.
