### ISSUE TITLE
Feature Request: Consolidate all device properties into a single entity

### ISSUE THREAD

**Issue by HammerAce42** [lukasroegner/homebridge-dyson-pure-cool#76]
As background, I originally transitioned over from the homebridge-dyson-link (https://github.com/joe-ng/homebridge-dyson-link) plugin since I am looking to get a PH01 in the near future and that plugin doesn't appear to be actively maintained anymore and hence it's unclear if and when it will get PH01 support.

One aspect of the other plugin which I found more convenient is that it grouped all the properties of the accessory into one entity (auto mode, fan speed, oscillation, thermostat, jet focus and night mode). This plugin has thermostat, night mode and jet focus as separate accessories from the air purifier/fan, which can add clutter to the Homekit UI and also not make it obvious that those things are associated with the purifier.

Would it be possible to have a config entry to optionally group everything into one entity like the aforementioned plugin does?

Thanks for your efforts in building and maintaining this!

**Comment by THX723** [comment]
@HammerAce42 The current Home app allows manually grouping of devices. Long press the device to bring up the control page and then click the gear/config icon at bottom-right corner. Look for 'Group with Other Accessories'.

**Comment by HammerAce42** [comment]
@THX723 Thanks for the pointer. I tried that and it doesn’t appear to allow me to group them together since the different accessory types don’t appear eligible for grouping (thermostat can’t be grouped at all, night mode switch can be grouped but only with other switches and not the air purifier entity.

**Comment by THX723** [comment]
@HammerAce42 That's a shame. Some devices are not supported.

**Comment by lukasroegner** [comment]
New version 1.7.5 has a new property in the configuration for a "single accessory mode".

**Comment by HammerAce42** [comment]
That’s an incredibly quick turn around - thanks so much!

**Comment by Soldiiier** [comment]
I only just decided to fiddle with these settings and I am loving the grouped services!
