### ISSUE TITLE
Add support for new TP06 model

### ISSUE THREAD

**Issue by bxlouis** [lukasroegner/homebridge-dyson-pure-cool#77]
Hello Lukas,

I recently bought the new [Dyson Pure Cool Cryptomic air purifier (TP06)](https://www.dyson.com/air-treatment/purifiers.html).
Would it be possible to support it in the upcoming versions?

I guess only the proper name should be added as it has the same features of its predecessor TP04.

**Comment by lukasroegner** [comment]
@bxlouis Just configure the plugin correctly and start it up. If your device is not supported, the model number is printed out in the logs. I can add the model number to the list of supported devices with the feature set of the TP04.

**Comment by bxlouis** [comment]
Hi @lukasroegner,
I tested the plugin thoroughly and it works fine.
Only the name of the device is not correct in the "Model" field.
Thanks for this great plugin.

**Comment by lukasroegner** [comment]
Ok, if it works out-of-the-box, then the TP06 does not have a different model number compared to the TP04.
