### ISSUE TITLE
Expose oscillation as a switch

### ISSUE THREAD

**Issue by HammerAce42** [lukasroegner/homebridge-dyson-pure-cool#79]
This is somewhat related to #72: would it be possible to expose a dedicated switch to control oscillation so it can be controlled/automated via the default HomeKit app?

Thanks!

**Comment by lukasroegner** [comment]
@HammerAce42 Can you provide more information on what you want to do?
* If you want to control oscillation via Home app, just open the accessory and toggle the oscillation switch.
* If you want to automate the oscillation, just create/edit automations with a third-party HomeKit app, those are way better when it comes to setting the properties that should be automated.

**Comment by HammerAce42** [comment]
@lukasroegner I mostly want to control the oscillation via the default HomeKit app. There is no oscillation switch/control currently visible.

**Comment by lukasroegner** [comment]
@HammerAce42 I assume you are using the single accessory mode? If you do so, the switch is not visible directly in the accessory settings in the Apple Home app. You have to click on the "X devices" entry in the settings of the accessory, then choose the air purifier. Here you can set the oscillation. 

That is the main reason I haven't grouped everything into one accessory in the first place.

**Comment by HammerAce42** [comment]
I don’t believe the grouped accessory is the problem. I don’t see the oscillate switch under the newly grouped accessory (see screenshot) and did not see the switch even prior to enabling that mode.
![ED017528-894D-4893-901A-46A8B15C3A86](https://user-images.githubusercontent.com/33810568/81504024-ee128a00-929b-11ea-93f8-400efef3e71e.png)

**Comment by lukasroegner** [comment]
![IMG_227B121C0E36-1](https://user-images.githubusercontent.com/16758848/81504102-b7faf780-92e7-11ea-80d6-a0638c4b4d24.jpeg)

**Comment by HammerAce42** [comment]
Ah, I see it now. I guess I was expecting a switch, but now that I know where to look, it resolves my concern.

**Comment by THX723** [comment]
@HammerAce42 [This](https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/72#issuecomment-623168358) should get what you wanted.
