### ISSUE TITLE
Air Quality Suggestions/Questions

### ISSUE THREAD

**Issue by Soldiiier** [lukasroegner/homebridge-dyson-pure-cool#80]
Hello,
I am wondering whether the 'Volatile Organic Compound Density' sensor can be renamed to VOC so that it can be inline with Dyson's reference and it doesn't impede on the value display
<img width="317" alt="Screen Shot 2020-05-11 at 10 14 13 am" src="https://user-images.githubusercontent.com/16224280/81514076-4ca93800-9370-11ea-9c00-a5fc23575e16.png">

<img width="646" alt="Screenshot 2020-05-11 at 10 16 24 am" src="https://user-images.githubusercontent.com/16224280/81514149-bcb7be00-9370-11ea-9a9c-e25913e7dd0f.png">

Secondly, is there a 'history' that is stored for HomeKit sensors?

thanks!

**Comment by lukasroegner** [comment]
The names of all service types, how they are displayed in the UI and the names of characteristics are not provided by the plugins, this is something the HomeKit apps take care of.

History is not supported by the Home app.
