### ISSUE TITLE
[Feature Request]: Group sensor data to a single accessory

### ISSUE THREAD

**Issue by keremerkan** [lukasroegner/homebridge-dyson-pure-cool#82]
Hi,

I see that you added a single accessory mode, which is great but I was wondering if you could add a mode that can group the air quality, humidity and temperature sensors in a single accessory instead of all options. That would be great to check all data in a separate accessory, while leaving mostly unused options out of the main accessory. I am attaching a similar approach by VELUX, which has a certified HomeKit accessory.

Cheers and thanks for your great work.

![IMG_3467](https://user-images.githubusercontent.com/1952491/81838208-7ddf5f00-954e-11ea-9ea9-d2ce502ed3db.PNG)

**Comment by lukasroegner** [comment]
New version 1.7.7 has the option `isSingleSensorAccessoryModeEnabled`. The following configuration should be used to achieve your desired configuration:

```
...
"isAirQualitySensorEnabled": true,
"isHumiditySensorEnabled": true,
"isTemperatureSensorEnabled": true,
"isSingleSensorAccessoryModeEnabled": true,
"isSingleAccessoryModeEnabled": false
...
```

**Comment by keremerkan** [comment]
Works great. Thanks!
