### ISSUE TITLE
TP02 not working or to old?

### ISSUE THREAD

**Issue by Flieger37** [lukasroegner/homebridge-dyson-pure-cool#85]
Hello Lukas,

in have installed 3 Dyson Pure Cool Link TP02 since 2016 and tried to run them with the plugin  "Homebridge Dyson Pure Cool" with either the Dyson App Account (mail address/password) or with the provided credentials after the first run in the config file - without success in both ways.

The tiles are displayed in Apple Home App, but all three Dysons don't show up with temperature, CO2 or other values and they can't be managed (started, stopped, ...) via Apple Home App. 

They all function with the plugin "Homebridge Dyson Link". The difference is, that in the plugin "Homebridge Dyson Link" the WLAN password of the Dysons is requested, which "Homebridge Dyson Pure Cool" does not ask for.

Are the devices to old to run with your plugin?

Regards
Martin

**Comment by lukasroegner** [comment]
Hi @Flieger37, the TP02 is supported by this plugin. The dyson-link plugin used a different serial number format, maybe that is the issue in your case. I would suggest to do the following:

- Clear the `devices` array in the config
- Restart homebridge. Now, all Dyson devices exposed to homebridge should
- Add a new entry for the TP02 in the `devices` array. Make sure that the entries for the `ipAddress` and `serialNumber` are correct. The serial number can be found in the Dyson app and has the format XXX-XX-XXXXXXXX, the IP address can be found in your router configuration.
- Restart homebridge. The TP02 should already work properly in HomeKit.
- If you want to, go to the logs and find the entry for `Credentials for device with serial number XXX-XX-XXXXXXXX are: XXXX...`. You can create a new `credentials` property for the device that matches the serial number printed out in this line in the logs.

**Comment by Flieger37** [comment]
Hi Lukas,
thank you for your quick response. I have cleared config / restarted Homebridge / installed the plugin again .. nothing helps.

You are right: the last three characters of the serial number have to be ignored in your plugin - I did so.

But Temperature, CO2, Humidity values are not displayed on the tiles - all values are Zero. Activating the Dyson via the Home App is not working ... the tile is highlighted but nothing happens.

In a second step I copied the credentials of all three Dyson from the Homebridge log to the config file (via CONFIG UI X) and restart Homebridge. Same result as above.

The fact that all expected tiles are displayed in Home App and the fact that three credentials can be found in the log according to the S/N means to me, that the plugin found and recognized the Dysons. (Is that right?) So for me, everything seems to be configured correctly (double checked).

Regards
Martin

**Comment by Flieger37** [comment]
This is how the plugin comes up (I just anonymized the S/N)... everything seems ok.

But the tiles in the Home App on my iPhone don't show any values nor have they any function when moving the switches to on or off:

5/20/2020, 9:44:58 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
2020-05-20 19:46:00 | [5/20/2020, 9:46:00 PM] [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform... 
2020-05-20 19:46:01 | [5/20/2020, 9:46:01 PM] [DysonPureCoolPlatform] Adding new accessory with serial number NN2-EU-xxxxxxxx and kind AirPurifierAccessory.
2020-05-20 19:46:02 | [5/20/2020, 9:46:02 PM] [DysonPureCoolPlatform] Adding new accessory with serial number NN2-EU-yyyyyyyy and kind AirPurifierAccessory.
2020-05-20 19:46:02 | [5/20/2020, 9:46:02 PM] [DysonPureCoolPlatform] Adding new accessory with serial number NN2-EU-zzzzzzzz and kind AirPurifierAccessory.
2020-05-20 19:46:02 | [5/20/2020, 9:46:02 PM] [DysonPureCoolPlatform] Got devices from config.

**Comment by Flieger37** [comment]
![Plugin Dyson Pure Cool](https://user-images.githubusercontent.com/65550366/82543110-5cd0cc80-9b53-11ea-882e-c00d5d8770d2.jpg)
![Plugin Dyson Link](https://user-images.githubusercontent.com/65550366/82543121-5fcbbd00-9b53-11ea-9213-3e564b19234c.jpg)
For comparison: the first picture shows the device information of the plugin "Dyson Pure Cool" the second on the information for the same device at the same moment of the "Dyson Link" (which also corresponds to the real state of the device).

**Comment by lukasroegner** [comment]
@Flieger37 Ok, the serial number is correct and the required model info has been retrieved and mapped successfully ("Hardware Revision" is "TP02"). As the accessory and services are all created correctly, I suspect the issue is that the plugin is not able to connect to the device. 

The communication is done via MQTT. When you start homebridge in debug mode (parameter `-D`), you can see alle MQTT events such as issues with connection and all messages that are exchanged. Please check the logs for messages that start with "MQTT", it should be easy to see whether it is a connection issue.

**Comment by Flieger37** [comment]
@lukasroegner OK, I restarted homebridge in debug mode and have filtered the log on MQTT. The result is: 3 connection requests for the the Dyson IP addresses and then lots of "MQTT disconnected" and "MQTT reconnecting" messages. Looks like frequent requests from the plugin but not like an error.
Some more information regarding my system: homebridge runs in an oznu/homebridge docker installation on a Synology NAS.

**Comment by lukasroegner** [comment]
@Flieger37 I have an assumption: in the early days of plugin development for the Dyson, I haven't closed open MQTT connections properly, which led to a "blocking" state of the device. I solved this issue by unplugging the Dyson completely from the AC, waiting some seconds, then plugging it into the AC again. The device restarts and is visible in the Dyson app after around a minute.

I would suggest to give that a try. Also, temporarily disable the dyson link plugin (if it is still running), so that the Dyson only has to deal with connections from the app and one plugin.

**Comment by Flieger37** [comment]
@lukasroegner I just have deleted one of the three Dyson ("Tobias") from the Dyson Link Plugin and unplugged it from AC for several minutes, restarted Homebridge and plugged the Dyson into AC again. Unfortunately with the same results - the switches on the Dyson tile from your plugin have nor function and no values are displayed. The Dyson App shows the real state and the plugin shows the state of the switches (that I can activate or move in the homebridge tile without any function) - see my screenshots.

![IMG_3041](https://user-images.githubusercontent.com/65550366/82764085-a8fa6600-9e0c-11ea-8b91-5d3c207d5123.png)
![IMG_3042](https://user-images.githubusercontent.com/65550366/82764095-bfa0bd00-9e0c-11ea-88af-9f6f5072057a.png)

**Comment by lukasroegner** [comment]
Ok, so that has not been the issue. 
The last thing I can think of is that the IP address configured for the device is not correct. Do your Dyson devices have static IP addresses? Have you double-checked the configured IP address?

If that also doesn't help, I'm really out of ideas.

**Comment by Flieger37** [comment]
@lukasroegner OK, seems to be a special situation and an individual problem. I think I will play a little around the next days or stay with the Dyson Link Plugin although I like yours more.. Thanks for your investigations in this case!
