### ISSUE TITLE
Dyson Pure Cool randomly commanded

### ISSUE THREAD

**Issue by catsartcox** [lukasroegner/homebridge-dyson-pure-cool#88]
Hi, I can’t quite catch it right when it happens ( so I can see it in the running log ), But I am noticing my Dyson fan randomly ( but only one a day in the late afternoon or evening ) is commanded to 80% fan speed. I feel like it is the home bridge server as I stopped it for three days and did not catch it randomly set to 80%.  This is also not because of air quality, as the fan’s log does not show it detecting any bad air quality. I don’t expect it to leave auto mode anyways unless it is commanded. It is a pure cool DP04. 
Thanks!  Not sure how easy to fix, but I wanted to report it.

**Comment by lukasroegner** [comment]
Hi @catsartcox, are you 100% sure that you don't have any automations that switch to 80%? There is no constant in the source code of the plugin that could (in any case) set the rotation speed to 80%, it has to be something either the device is doing or an automation.

If you can catch the error in the logs, post them here, so I can investigate further.

**Comment by catsartcox** [comment]
Thanks for replying. And yes, I actually have zero automations programed in. The tab in the home app is empty. But thanks, I’ll try to see if I can catch it.  Does home bridge anywhere save off the activity logs that I can pull?

**Comment by lukasroegner** [comment]
If you installed homebridge as a service (systemd), I think you can use `journalctl`.

**Comment by lukasroegner** [comment]
I'm closing this for now, feel free to re-open if you have further information.
