### ISSUE TITLE
[Feature Request] PH01 alternative operation mode for target humidity

### ISSUE THREAD

**Issue by CooperCGN** [lukasroegner/homebridge-dyson-pure-cool#89]
Hi Lukas,

Just got my new humidifier and got it working in HomeKit.

In the Dyson App I can set target values for the humidifier between 30 and 70 in steps of 10. In the Home app it allows to set to values between 0 and 100 in steps of 33. 33 sets the humidifier to 50, 66 to 60 and 100 to 70 percent.

Is that how it is intended?

**Comment by lukasroegner** [comment]
Hi @CooperCGN,

Nice...I'm also really really thinking about purchasing the new PH01. I really wonder whether the humidifier has an additional cooling effect in the summertime compared to a TP04 or DP04...I know you also have other Dyson devices, maybe you could share your thoughts? All reviews that I have watched/read don't really compare the cooling effect with other Dyson devices.

Back to your question: the plugin actually tells HomeKit the possible range and set size:

```
// Updates the humidity threshold         humidityService.getCharacteristic(Characteristic.RelativeHumidityHumidifierThreshold).setProps({
  maxValue: 70,
  minValue: 40,
  minStep: 10
});
```

Do you use the Apple Home app or a third party app? Maybe the settings are ignored?

**Comment by CooperCGN** [comment]
Well, can’t say yet if there is an additional cooling effect, it’s just running now for half an hour and my main reason to get it was my low humidity in the living room. But I will get back to it once it gets relay warm.

I am using Apple’s Home app.
![D47059A4-C8D2-4B67-8768-1C57FDFBB1A7](https://user-images.githubusercontent.com/29116509/83012096-3c08eb00-a01b-11ea-93cd-b1fe0b5ab397.jpeg)

**Comment by lukasroegner** [comment]
I'm just curious whether setting the properties is done too late: could you restart Homebridge and try again? If the steps don't work after the restart, I'll have to dig deeper.

**Comment by CooperCGN** [comment]
Tried that of course first before opening the issue. :)
0 by the way is 40 percent in the Dyson app. So HomeKit somehow doesn’t get the correct values.

**Comment by lukasroegner** [comment]
Now I see: the Home app translates the allowed range (40 - 70, all possible values when steps of 10 are allowed: 40,50,60,70) into a scale from 0 to 100:

40% Dyson -> 0% Home
50% Dyson -> 33% Home
60% Dyson -> 66% Home
70% Dyson -> 100% Home

**Comment by CooperCGN** [comment]
I just wonder, would it be possible to have the regular 0 to 100 scale and when I select 71 or higher in the home app it just bounces back to 70 percent? Same for let’s say 39 bounces back to 40.

**Comment by CooperCGN** [comment]
By the way, that thing is massive 😂

**Comment by lukasroegner** [comment]
Yes, could be done. As the PH01 is supported for quite some time, I would add this operation mode as a separate setting.

**Comment by e-vw** [comment]
Hi, first of all, thank you for your great plugin! I just got the PH01, and came here after installing your plugin and noticing the same 'problem' :-). I noticed the Dyson app allows values from 30-70 in steps of 10. But I also do like the option for setting it from 0-100 so the scale does not do a translation.

So I cloned your repo and started experimenting a bit, when using a scale of 0-100 in translates 1:1 tot the Dyson app. When you set the value below 30 or above 70 in Homekit, the value will be automatically set within the allowed range. So 20 wil be set to 30 and 80 to 70, this shows both in Homekit and the Dyson app.

After that I changed the step to 1, and the Dyson actually accepts this, so I can now set the humidity level to e.g. 47. And it also shows as 47 in the Dyson app.

**Comment by lukasroegner** [comment]
New option `isFullRangeHumidity` in 1.7.9 to disable the translation by the Apple Home app.

**Comment by malmentm** [comment]
> New option `isFullRangeHumidity` in 1.7.9 to disable the translation by the Apple Home app.

I don't think this is working anymore? All I get steps in home app in 25% steps.

**Comment by malmentm** [comment]
> Hi, first of all, thank you for your great plugin! I just got the PH01, and came here after installing your plugin and noticing the same 'problem' :-). I noticed the Dyson app allows values from 30-70 in steps of 10. But I also do like the option for setting it from 0-100 so the scale does not do a translation.
> 
> So I cloned your repo and started experimenting a bit, when using a scale of 0-100 in translates 1:1 tot the Dyson app. When you set the value below 30 or above 70 in Homekit, the value will be automatically set within the allowed range. So 20 wil be set to 30 and 80 to 70, this shows both in Homekit and the Dyson app.
> 
> After that I changed the step to 1, and the Dyson actually accepts this, so I can now set the humidity level to e.g. 47. And it also shows as 47 in the Dyson app.

Does this still works for you? I Can't only get it to accept steps in 25%, 0% = 30 25% = 40 and so on.
