### ISSUE TITLE
Incorrect Chareteristics?

### ISSUE THREAD

**Issue by Soldiiier** [lukasroegner/homebridge-dyson-pure-cool#91]
Hello, I did a re-install of the plugin and used my existing settings (manually put them each in the config set up),but this error has come up.
the error only comes up at the first initial set up.

[6/3/2020, 11:25:40] [DysonPureCoolPlatform] Adding new accessory with serial number xx and kind AirPurifierAccessory.
HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BB-0000-1000-8000-0026BB765291. Adding anyway.

**Comment by lukasroegner** [comment]
Yes, as some characteristics-service combinations are not "allowed" in the HomeKit standard, however, the characteristics are displayed correctly in the Home app.
