### ISSUE TITLE
problem with Dyson plugin

### ISSUE THREAD

**Issue by warz1017** [lukasroegner/homebridge-dyson-pure-cool#94]
i have installed Dyson plugin and configure it but I always have this error message : Error while signing in. Status Code: 400 [DysonPureCoolPlatform] API could not be reached. Retry is disabled.

I don't know the solution. my ID and password are good

**Comment by warz1017** [comment]
MY LOCATION is EU

**Comment by lukasroegner** [comment]
The country code has to be the code of the country, not EU.
