### ISSUE TITLE
Wrong pollution metrics after installing the plugin

### ISSUE THREAD

**Issue by stavtag** [lukasroegner/homebridge-dyson-pure-cool#95]
I have the Pure Humidifier+Cool and the moment I installed the plugin, VOC went really high. This made the device operate at a higher speed. When I deactivated the plugin, it all went back to normal. Any ideas why this is happening or how I can fix it?

EDIT
It seems that all the pollution metrics are displayed incorrectly.

In addition, although the scales for the humidifier are 30, 40, 60, 70, the plugin doesn't allow for anything other than 33 and 64.

**Comment by lukasroegner** [comment]
> I have the Pure Humidifier+Cool and the moment I installed the plugin, VOC went really high. This made the device operate at a higher speed. When I deactivated the plugin, it all went back to normal. Any ideas why this is happening or how I can fix it?

I haven't heard of other users having the same issue. I personally own a DP04 and TP04 and also haven't seen anything like that. The plugin doesn't (and cannot) change sensor data on the device.

> It seems that all the pollution metrics are displayed incorrectly.

What is "incorrectly"? Wrong numeric value? How large is the difference? No value at all? How do you compare the plugin value and the device value (Dyson app)?

> In addition, although the scales for the humidifier are 30, 40, 60, 70, the plugin doesn't allow for anything other than 33 and 64.
Unrelated to this issue. See #89.
