### ISSUE TITLE
Dyson Pure Cool Link TP03

### ISSUE THREAD

**Issue by dampney** [lukasroegner/homebridge-dyson-pure-cool#97]
Any plans or possibility for support for the TP03 model?

Everything seems to work in Hoobs and I can see the controls in Homekit but there is no response with the Dyson fan.

Thanks

**Comment by lukasroegner** [comment]
When you start homebridge, you should see log entries containing important information regarding model number (so that I can check whether it is already enabled) and possible issues with your Dyson credentials (serial number, email address, password).

**Comment by dampney** [comment]
Hope this is what you need:

> 21/06/2020, 6:10:24 pm - HOOBS listening on port 8080.
21/06/2020, 6:10:45 pm - Loaded plugin "homebridge-dyson-pure-cool".
21/06/2020, 6:10:58 pm - [DysonPureCoolPlatform] Device credentials not stored, asking Dyson API. If you want to prevent communication with the Dyson API, copy the credentials for each device from the coming log entries to the config.json.
21/06/2020, 6:10:58 pm - [DysonPureCoolPlatform] Signing in.
21/06/2020, 6:11:00 pm - [DysonPureCoolPlatform] Signed in.
21/06/2020, 6:11:01 pm - [DysonPureCoolPlatform] Credentials for device with serial number ###-AU-######### are:
**....redacted....**
21/06/2020, 6:11:01 pm - [DysonPureCoolPlatform] Got devices from the Dyson API.


Configuration:
> [
    {
        "ipAddress": "..:..:..:..:..:..",
        "serialNumber": "###-AU-########",
        "enableAutoModeWhenActivating": true,
        "isNightModeEnabled": true,
        "isJetFocusEnabled": false,
        "isTemperatureSensorEnabled": true,
        "isHumiditySensorEnabled": true,
        "isAirQualitySensorEnabled": true,
        "isSingleAccessoryModeEnabled": false
    }
]

**Comment by lukasroegner** [comment]
The TP03 seems to have the same model number as the TP02, as it is not rejected by the plugin. Thus, it should work without any changes to the plugin. Start homebridge in debug mode (parameter `-D`) and check out the logs of the MQTT messages.

**Comment by pyrmont** [comment]
Sorry to post to a closed issue but I wanted to report that I've set up a TP03 using this plugin and Homebridge. Thanks for all your efforts!
