### ISSUE TITLE
problem on change dyson

### ISSUE THREAD

**Issue by platini76** [lukasroegner/homebridge-dyson-pure-cool#99]
[2020-6-25 3:51:02] [DysonPureCoolPlatform] Signed in.
[2020-6-25 3:51:02] [DysonPureCoolPlatform] No IP address provided for device with serial number VW3-EU-XXXXXXX.

my config is correct I think:
V69-EU-XXXXXX
ip 192.168.0.44

**Comment by lukasroegner** [comment]
You can see in your post that the serial numbers (from your config and the output in the logs) do not match.

**Comment by platini76** [comment]
but the correct serial number is the config one... why it goes to take the previous one? how to slve?

**Comment by lukasroegner** [comment]
> why it goes to take the previous one

What do you mean with previous one.

I assume you have a single Dyson device in your Dyson account. If this is the case, then the correct serial number for the `config.json` is the one that has been printed out in the logs (`VW3-EU-XXXXXXX`).

**Comment by platini76** [comment]
uhmm the number is not the one that is visualized on the app?

**Comment by lukasroegner** [comment]
> uhmm the number is not the one that is visualized on the app?

But you only own a single Dyson? If so, try out the serial from the logs...maybe a refurbished device with new serial???
